- index.html
- js/index.js
#5 
This patch helps to give Susi the capabilities to answer with tables and pie charts. Used the highcharts for displaying the piecharts.
> Fixes #5 - Added Visualizations to Susi

- js/index.js
#12 
Resolved the type issue with susi chat. Now the interface doesnt break for visualizations. 
@sudheesh001 thanks for the help.
> Fixes #12: Resolved the type issue with the Susi chat

- index.html
- js/index.js
#7 
This patch supports the display of map links in tile, for quick view. 
Here's a sample.
> Fixes #7 Support for Display of Maps as map tile images

- index.html
Directed to [https://github.com/fossasia/susi_android/raw/apk/susi-release.apk](https://github.com/fossasia/susi_android/raw/apk/susi-release.apk) to download `susi-release.apk`
> Updating the link to directly download susi-release.apk

- chat.html
- css/style.css
Fixes #20
Live Demo: https://brainbuzzer.github.io/asksusi.com/chat
Desktop Version:
Tablet version:
Mobile Version:
> Redesigned Chat UI

- chat.html
There were a few problems with my last commit. Here is a fix to them.
> Fixed UI problems of web app

- chat.html
The previous commit was not making the page responsive on mobile so here's a fix for that. And the visual performance on computer is increased.
Live Demo: https://brainbuzzer.github.io/asksusi.com/chat
Image:
> Fix responsiveness on mobile

- index.html
- main.html
#46 Added Google Play Button into main.html and deleted the "PlayStore" footer button in index.html.
> Solved #46

- index.html
- main.html
Reverts fossasia/asksusi.com#47
Button not integrating into the design
> Revert "Solved #46"

- package.json
- src/App.css
- src/App.js
- src/index.js
- Added material UI
- Added Bootstrap to use grid system
- added simple UI (just a layout) followed the format of messenger  https://www.messenger.com
this resolve #65 
Preview Link: http://numerous-rabbit.surge.sh
> Fixes #65 add simple chat application UI

- package.json
- src/components/MessageListItem.react.js
Proccesses the responses from susi and replaces any urls with "Click Here" hyperlinking that url
> Fixes #79 - Proccessing susi response for hyperlinking urls

- src/components/MessageComposer.react.js
resolve #82 
focus the TextBox as soon as the page loads
preview link here : http://isuruab.surge.sh/
> fixes #82 focus the TextBox as soon as the page loads

- src/ChatExampleDataServer.js
- src/actions.js
- src/stores/MessageStore.js
- src/utils/ChatMessageUtils.js
- src/utils/ChatWebAPIUtils.js
- [Actions.js](https://github.com/fossasia/chat.susi.ai/pull/88/files#diff-7701bf42c0bcc36a1600dd1f7ec16030) handles all the API response and only creates an Action when the response is received.
- `NETWORK_LATENCY` is now reduced to 300 and is independent of the time of the response.
- This also fixes https://github.com/fossasia/chat.susi.ai/pull/87/files
- Added comments to ensure easier workflow for the future development process.
- Added message *Please check your internet connection* when the connection has timed out.
Demo Link: http://susi.surge.sh
> Fixes #84: SUSI does not respond until second message

- package.json
- public/index.html
- src/components/ChatApp.css
- src/components/MessageListItem.react.js
- src/utils/ChatMessageUtils.js
http://susimaps.surge.sh/ is the demo link.
Try querying "where is london" to check the response with mapsupport.
The marker icon is not rendering due to error in leaflet source code. Working on a workaround or a custom marker icon.
> Fixes #71 - Map support for webchat app

- src/components/MessageListItem.react.js
demo link : http://susitables.surge.sh/
sample query : universities in germany
> Fixes #77 - Table support for chat client

- package.json
- src/__tests__/components/ChatApp.js
- src/__tests__/components/MessageComposer.js
- src/__tests__/components/MessageSection.js
- src/__tests__/components/ThreadSection.js
- src/__tests__/utils/ChatMessageUtils.js
Added some test cases .
resolves #81
> Fixes #81 add test cases

- .eslintrc
- package.json
- src/ChatExampleDataServer.js
- src/__tests__/components/MessageSection.js
- src/__tests__/utils/ChatMessageUtils.js
- src/actions.js
- src/components/ChatApp.react.js
- src/components/MessageComposer.react.js
- src/components/MessageListItem.react.js
- src/components/MessageSection.react.js
- src/stores/MessageStore.js
- src/stores/ThreadStore.js
- src/utils/ChatMessageUtils.js
- src/utils/ChatWebAPIUtils.js
I have added some basic rules so that we can start linting, we can iterate from here.
> Fixes #100 : Add support for eslint

- src/components/ChatApp.css
Added css for marker icon
**Demo Link** : http://marker.surge.sh/
> Fixes #107 - Map marker not rendering in map tile

- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE
Fixes #105 
Added template for issues and pull requests
Please review.
Thanks
> Fixes #105: Added template for issues and pull requests

- src/ChatExampleDataServer.js
- src/components/MessageComposer.react.js
- src/components/MessageSection.react.js
- src/components/ThreadListItem.react.js
- src/components/ThreadSection.react.js
- src/stores/ThreadStore.js
- src/stores/UnreadThreadStore.js
Fixes issue #113 
Changes: changed few files in accordance with best practices.
> Fixes #113: Changed few files according to best practises

- public/index.html
- src/components/ChatApp.css
- src/components/MessageComposer.react.js
- src/components/MessageListItem.react.js
- src/index.css
**Fixes issue #104**
**Changes:**
- Lato Font Added
- Added chat bubbles
- New color scheme added for chat bubbles, background
- Placeholder for text input
**Demo Link:**
> Fixes #104:Modifications in the theme

- src/components/ChatApp.css
- src/components/MessageComposer.react.js
- src/index.js
Fixes issue #116
Changes: Added Button next to message box for sending message
Demo Link:  http://button.surge.sh/
> Fixes #116: Added send button next to message box

- src/ChatExampleDataServer.js
- src/actions.js
- src/components/ChatApp.css
- src/components/ChatApp.react.js
- src/components/MessageSection.react.js
- src/constants/ChatConstants.js
- src/stores/SettingStore.js
Fixes issue #118 
**Changes:**
Added a button to switch between two themes.
made a store for settings for future use.
Demo Link:  http://susi-patch-118.surge.sh/
> Fixes #118 dark theme and ability to switch

- src/components/ChatApp.css
Fixes issue #145 
Changes: change background to invisible
Demo Link: http://susi-patch-145.surge.sh/
screenshot:
> Fixes #145 change background to invisible

- src/components/ChatApp.css
- src/components/MessageSection.react.js
Fixes issue #143 
Changes:  add material UI App bar and option for switch between themes.
Demo Link: http://susi-patch-143.surge.sh/
> Fixes #143 Add Material UI App bar

- package.json
- src/actions.js
- src/components/MessageListItem.react.js
- src/components/MessageSection.react.js
- src/components/SearchSection.react.js
- src/constants/ChatConstants.js
- src/stores/SettingStore.js
Fixes issue #130 
**Changes:**
Added a new component SearchSection and actions and SettingStore variables to implement the search feature
PS: The feature is complete when we scroll into the currently matched search. I used  findDOMNode to implement that, but lint tests isnt allowing using findDOMNode. So I have commented the scroll part out. 
So currently the search feature doesnt scrollto the matched search. WIll be implemented by creating a new issue
**Demo Link:** 
http://chatmsgsearch.surge.sh/
> Fixes #130 - Message search feature

- package.json
- src/components/ChatApp.react.js
- src/components/MessageComposer.react.js
- src/components/MessageSection.react.js
- src/history.js
Fixes issue #120 
Changes: 
- Added routes to test any dream from query
Demo Link: 
http://susi.surge.sh/?dream=susi
Param dream can be changed to access any dream
@uday96 @isuruAb @madhavrathi Please review
> Fixes #120: Route for accessing dream

- package.json
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/components/MessageSection.react.js
- src/index.css
- src/index.js
Fixes issue #154 
Changes: 
- Routed Login Screen
- Static Login Page
Demo Link: 
Go to right most vertical dot icon and click Login
@uday96 @isuruAb @madhavrathi Please review and suggest changes
> Fixes #154: Create a Login Page

- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
- src/components/MessageSection.react.js
- src/index.js
Fixes #155 and part of the #144 
Changes:
Added SignUp page and Route to Sign Up page
Demo Link: http://patch-155.surge.sh/
Screenshot:
> Fixes:#144 (partially) and Fixes: #155 Created SignUp page and route

- README.md
Fixes issue #166 
Changes:
- Updated command for running on localhost
Please Review @uday96 @madhavrathi @isuruAb
> Fixes #166: Update README.md

- package.json
- src/components/MessageListItem.react.js
Fixes issue #160 
Changes: Added emoji support for the web chat
Demo Link: http://jumbled-sponge.surge.sh/
@uday96 @rishiraj824 @isuruAb Please Review
> Fixes#160: Added emoji support for susi web chat

- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/index.js
Fixes issue #171 
**Changes:**
Added a route from login page to forgot password
**Demo Link:** http://forgotpassword.surge.sh/
> Fixes #171 - Forgot Password Functionality Added

- src/components/MessageListItem.react.js
Fixes issue #187 
**Changes:**
Emojified after processing the text for images, marking and linkifying
**Demo Link:**  http://searchwithemoji.surge.sh/
> Fixes #187 - Fixes search option with emojify

- .eslintrc
- package.json
- src/actions.js
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
- src/components/MessageListItem.react.js
- src/components/MessageSection.react.js
- src/index.css
- src/index.js
Fixes issue #164 
Changes: 
- Added Login/Logout Feature
- Session Storage based on cookie
Demo Link: 
@uday96 @isuruAb @madhavrathi Please review
> Fixes #164: Login Functionality

- src/components/Auth/SignUp/SignUp.react.js
- src/index.js
Fixes issue #172 
Changes: 
- Connected the UI to server.
- Validated form fields.
Demo Link: http://susi-patch-172.surge.sh/
> Fixes #172 : connect SignUp page with server

- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #195 
Changes: Removed White spaces under each button which change the route of the application.
Demo Link: [Add here the link where you changes can be seen]
Screenshots for the change:  http://susi-patch-195.surge.sh/
> Fixes #195 remove white space under the button

- public/index.html
Fixes issue #205 
Demo LInk - http://seosusi.surge.sh
> Fixes #205: SEO Content

- docs/RetrievingHistory.md
Fixes issue #206 
**Changes:** Added documentation for retrieving chat history
> Fixes #206 - Added documentation for retrieving chat history

- src/components/MessageListItem.react.js
Fixes issue #201 
**Changes:** Mark text and then emojify content
**Demo Link:** http://searchwithemoji.surge.sh/
https://user-images.githubusercontent.com/13276887/26942295-246ac932-4c9f-11e7-9b38-b7040b7d9d17.png
> Fixes #201 - Fix search feature

- src/actions.js
- src/components/ChatApp.css
- src/components/MessageListItem.react.js
Fixes issue #184 
**Changes:**
*Implemented support for action type ```rss```
*Used same abstraction for websearch and rss results
*Used ```count``` from server response to limit the results
**Demo Link:** http://rssactiontype.surge.sh/
**Sample Queries:** 
rss : stock quotes
websearch : search for *  
> Fixes #184 - RSS Action type support

- package.json
- src/components/SearchSection.react.js
Fixes issue #150 
**Changes:** 
The search feature is now complete.
Chat window now automatically scrolls to the highlighted text.
**Demo Link:** http://searchscroll.surge.sh/
> Fixes #150 - Auto Scroll to highlighted text in search feature

- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
- src/components/MessageSection.react.js
Fixes issue #198
Changes: 
Form widths handled.
Demo Link: 
http://responsiveness.surge.sh
> Fixes #198 Login form responsive

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #218 
**Changes:**
Added form validation to login page
Disabled buttons until form is validated
**Demo Link:** http://disablebtn.surge.sh/
> Fixes #218 - disable buttons till accounting forms are validated

- package.json
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #176 
**Changes:**
Added a Password Field with an option to show or hide password in the login and signup forms
**Demo Link:** http://showpassword.surge.sh/
> Fixes #176 - Option to show or hide password

- src/actions.js
Fixes issue #226 
**Changes:**  
Changed the server call endpoint from api.asksusi.com to api.susi.ai
**Demo Link:**
http://serverendpoint.surge.sh/
> Fixes #226 - Changes server call from api.asksusi to api.susi.ai

- src/components/Auth/Logout.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageSection.react.js
Fixes issue #199 
Changes: Now login url on signup works fine. 
Demo Link: http://urlfix.surge.sh/
@isuruAb @rishiraj824 @uday96 Please review and suggest any changes.
> Fixes#199: Change the login URL on SignUp page

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageSection.react.js
Fixes issue #211
Change background and font colour of buttons when user switch between themes.
Demo Link: http://susi-patch-211.surge.sh/
> Fixes #211 : change button colours according to the theme

- .eslintrc
- src/actions.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
**Fixes issue #216**
**Changes:**
- Added Custom server configuration
**Demo Link:**
@uday96  @madhavrathi @isuruAb Please Review
> Fixes #215: Add custom server configuration

- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection.react.js
Fixes issue #245 
Changes: reduce extra width of Dialog-box
> Fixes: #245 reduce extra width of Dialog-box

- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #256 
Changes: Now signUp buttons is in disable state until user inserts valid data .
> Fixes: #256 keep signup button in disable state until form filled with valid inputs

- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageListItem.react.js
- src/components/ChatApp/SearchSection.react.js
Fixes issue #249 
**Changes:**
* Added an option to search case sensitively in the search feature
The method of selecting the case sensitive feature (I used a toggle in a popover) can be changed to a pop over over a case sensitive icon maybe. Will implement that in a seperate issue if needed.
**Demo Link:**  http://casesensitivesearch.surge.sh/
> Fixes #249 - Added Case Sensitive Option in Search Feature

- src/actions.js
- src/components/Auth/Login/Login.react.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/Settings.react.js
- src/constants/ChatConstants.js
- src/stores/UserPreferencesStore.js
Fixes issue #255
Changes: 
- Added URL of server in configuration store
- This will be used to push all the UserPreferances to the server
Demo Link: 
> Fixes #255: Add URL of server to configuration file

- src/components/ChatApp/MessageSection.react.js
Fixes issue #263 
Changes: Added a drop-down menu for changing themes
Demo Link:http://dropdown.surge.sh/
@rishiraj824 @uday96 @isuruAb @daminisatya  Please Review !
Thanks
> Fixes #263: Added dropdown menu for changing theme

- src/components/Auth/Login/Login.react.js
Fixes issue #251 
Changes: Width added in form of percentage.
Demo Link: http://compatible.surge.sh/
> Fixes #251: login now compatible with mobile

- src/actions/API.actions.js
- src/actions/History.actions.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #266 
**Changes:**
* Added custom server option in signup and forgot password
**Demo Link:** http://customserver.surge.sh/
**Sample Custom Server URL :** http://104.197.146.27
> Fixes #266 - Accounting with custom server

- deploy.sh
Fixes issue #221 
Changes: now users can go to routes directly
> Fixes: #221 can go to urls directly

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection.react.js
- src/components/ChatApp/SearchSection.react.js
Fixes issue  #278 
Changes: 
- Compared with standard apps and increased spacing for the bottom area,
- Fixed the button to accommodate the textarea
Demo Link:
> Fixes #278 Match bottom area to standard apps

- src/components/ChatApp/HardwareComponent.js
- src/components/ChatApp/MessageSection.react.js
Fixes issue #275 
Changes: 
- Added Dialog for entering Port Hardware
Changes pending
- Adding functionality to test with the Hardware
This also fixes https://github.com/fossasia/susi_hardware/pull/30
Demo Link: 
> Fixes #275(Partly): Create Settings to connect SUSI WebChat to SUSI Hardware

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection.react.js
Fixes issue #282 
Changes: Align dialog box content to center. and responsive
> fixes:#282 change width of dialog box and align center

- docs/Accounting.md
Fixes issue #270 
**Changes:**
* Added documentation about the accounting features providing a basic overview about the process involved with each
> Fixes #270 - Add documentation about accounting

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection.react.js
- src/components/ChatApp/SearchSection.react.js
Fixes issue #279 
Changes: reduce height of the app-bar  on search state and default satate
> Fixes:279 reduce app-bar size 

- src/components/ChatApp/MessageSection.react.js
Fixes issue #300
Changes: 
- Header color changes to dark color when in dark mode
Demo Link: 
> Fixes #300 - Header color not changing in dark mode

- src/components/ChatApp/MessageListItem.react.js
Fixes issue #288 
**Changes:**
* Added a check to validate a row before populating it in the table
**Demo Link:**  http://emptyrows.surge.sh/
> Fixes #288 - Remove empty rows in table

- src/components/NotFound/NotFound.react.js
Fixes issue #305 
Changes: add missing function that producer  
Demo Link: http://isuruab.surge.sh/asad
@rishiraj824 @madhavrathi @uday96  review this please
> Fixes:#305 gives 404 page instead of white page

- .gitignore
- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageListItem.react.js
- src/setupTests.js
Fixes issue #261 
Changes: 
- Removed Know more links
- Added responsive tiles
Demo Link: 
> Fixes #261: Make websearch rss results similar to android and IOS

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection.react.js
- src/components/ChatApp/Settings.react.js
Fixes issue #303 
Changes:
- Moved the option to connect to Hardware in Settings
Demo Link: 
> Fixes #303 Move Connect to SUSI Hardware option to Settings

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/SearchSection.react.js
Fixes issue #302 
Changes: made search text white
Demo Link: http://searchwhite.surge.sh/
@uday96 @rishiraj824 @isuruAb @daminisatya  Please review
Thanks
> Fixes #302: made search text white

- .eslintrc
- README.md
- src/actions/API.actions.js
- src/actions/HardwareConnect.actions.js
- src/actions/index.js
- src/components/ChatApp/HardwareComponent.js
Fixes issue #289 : Added the hardware connect functionality over websockets to Susi Hardware Device.
**Changes:** 
- Added connection Interface via websockets.
- Query received from Susi Hardware device after Speech Recognition is used to create a message in UI.
- Server Response from Susi API is send to Hardware Device for TTS,
**Demo Link:** N/A
Functionality based change, I will provide a Youtube video of working implementation soon.
> Added Hardware Connect functionality

- src/components/ChatApp/SearchSection.react.js
Fixes issue #327 
Changes: Now search field focus on search mode.
> Fixes:#327 focus search field on search mode

- src/components/ChatApp/Settings.react.js
Fixes issue #329 
Changes: Added flat button for add address for connection to hardware button
Demo Link: http://susimadhav.surge.sh/
> Fixes #329: Added flat button for connection to hardware address button

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/Dialog/LoginDialog.js
Fixes issue #331
Changes: remove extra spaces
> Fixes: #331  remove extra white space below header

- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/Dialog/LoginDialog.js
- src/components/ChatApp/MessageSection.react.js
- src/components/NotFound/NotFound.react.js
Fixes issue #322 
Changes: made separate component for login Dialog box
> Fixes: #322 - Make separate component for login Dialog box

- src/__tests__/components/MessageSection.js
- src/components/ChatApp/ChatApp.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #326 
Changes: Made Separate DialogSection made for all the dialogs in message section.
Demo Link: http://susimadhav.surge.sh/
@uday96 @rishiraj824 @daminisatya @isuruAb Please Review
Thanks
> Fixes #326: refactor message section

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
Fixes issue #165 
**Changes:**
* Made AppBar as a Seperate Component - TopBar
**Demo Link:** http://topbar.surge.sh/
@rishiraj824 @isuruAb @madhavrathi @daminisatya please review
> Fixes #165 - Seperate component for TopBar

- src/components/ChatApp/Dialog/LoginDialog.js
Fixes issue #347 
Changes: Removed constructor from LoginDialog as it was useles and was giving warnings
Demo Link: http://susimadhav.surge.sh
@uday96 @rishiraj824 @isuruAb Please review
Thanks
> Fixes #347: fixed warnings from LoginDialog.js

- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/Dialog/LoginDialog.js
- src/components/NotFound/NotFound.react.js
Fixes issue #349 
Changes: Login dialog-box closes after successfully login
> Fixes: #349 -Login dialog-box closes after successfully login

- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem.react.js
Fixes issue #335, #248 
Changes: 
- Fetching location based on the default navigator class.
- This also avoids the API call to http://ipinfo.io as mentioned in https://github.com/fossasia/chat.susi.ai/issues/248
Demo Link: 
http://get-geolocation.surge.sh
Please review now @isuruAb @uday96 @madhavrathi @daminisatya
> Fixes #335, #248- getLocation() does not work while a message from history is loaded.

- docs/Accounting.md
Fixes issue #356 
**Changes:**
* Added documentation about how user settings is pushed and fetched from server
> Fixes #356 - Added documentation about storing user data in server

- src/components/ChatApp/TopBar.react.js
Fixes issue #352 
Changes:
- Shows menu in top bar
- change state {open:false}
> Fixes: #352 - Shows menu in top bar

- src/actions/API.actions.js
- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/Dialog/LoginDialog.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
- src/index.js
Fixes issue #357
Changes:
- Removed Sign Up Route
- Added comments in the Dialog Section
- Removed unnecessary console.logs
Demo Link: 
http://signup-dialog.surge.sh
Please review @uday96 @madhavrathi @isuruAb @daminisatya
> Fixes #357 - Move the Sign Up into a dialog instead of a new route

- src/components/ChatApp/SearchField.react.js
Fixes issue #374 
Changes: Passing state instead of null in value in text field of search
@uday96 @rishiraj824 @isuruAb Please review
Thanks
> Fixes#374: fixed warnings from search field

- package.json
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/ChatApp.css
Fixes issue #380 
Changes: got password strength using https://github.com/dropbox/zxcvbn and show it visually in signup section.
Demo Link:http://susi-pass.surge.sh/
@rishiraj824 @uday96 @isuruAb Please Review.
Thanks
> Fixes#380 strength of password is now visible

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
Fixes issue #387 
Changes: send custom colour to the Top-Bar component to change the app-bar colour
Review please @rishiraj824  @madhavrathi  @uday96
> Fixes: #387 - can choose custom colour for app bar

- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #393
Changes: Application shows error message on unsuccessful login attempts
@rishiraj824  @uday96  @madhavrathi  please review
> Fixes: #393 - Shows error message on unsuccessful login attempts

- src/components/Auth/Login/Login.react.js
Fixes issue #395 
Changes: Password field now display the message on being active.
Demo Link: http://susimadhav.surge.sh/
Thanks
> Fixes#395: password field now display error message on being active

- .github/PULL_REQUEST_TEMPLATE
There was a typo in Pull Request Template. This is not an issue so i am just sending a PR to fix it.
Thanks
> Fix typo in Pull Request template

- package.json
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/VoiceRecognition.js
**Fixes issue #277**
**Changes:**
- Added Voice to text feature for Chrome
- Testing for all browsers handled, Mic will only appear for browsers supporting Speech Recognition API
- Added loading icon while STT is happening
- Mic will be off automatically after a pause
- Send button enabled as soon as one starts to type.
- Kept Mic as default following the other clients in the market
- Automatically sends the message after STT conversion.
**Demo Link:**
Use Chrome to test
http://susivoice.surge.sh
**Sceenshot**
> Fixes #277 - Implement Voice on Chrome

- src/components/Auth/Login/Login.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/NotFound/NotFound.react.js
Fixes issue #391 
**Changes:**
* Moved Forgot Password dialog into Login Dialog
**Demo Link:** http://forgotpasswordfix.surge.sh/
> Fixes #391 - Fixes Forgot Password dialog from Login Dialog

- src/components/ChatApp/MessageComposer.react.js
Fixes issue #405 
Changes: Now send button icon changes back to mic after sending message.
Demo Link: [Add here the link where your changes can be seen]
Screenshots for the change:http://susimadhav.surge.sh/
@uday96 @rishiraj824 @isuruAb @daminisatya Please Review.
Thanks
> Fixes#405: Send button icon changes properly

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #389 
Changes: Users can add image to body background of the application.
@uday96  @rishiraj824  @madhavrathi  please review
> Fixes: #389- Users can change background image

- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes issue #401 - 
Changes: 
- Added a Speak Now view after clicking on Mic
Demo Link: 
http://susivoice.surge.sh
> Fixes #401 - Implement a Speak Now view for Speech to Text

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #408
Changes: Added snackbar when theme changes with undo button.
Demo Link: http://susi-snack.surge.sh/
@rishiraj824 @uday96 @isuruAb @daminisatya  Please Review.
Thanks
> Fixes#408: added snackbar on theme change

- src/components/ChatApp/MessageSection/DialogSection.js
Fixes issue #411 
Changes: Add cancel button to Hardware connection Dialog box
Demo Link: http://isuruab2.surge.sh/
@madhavrathi  @rishiraj824  @uday96  @daminisatya please review
> Fixes: #411 -Add cancel button to Hardware connection Dialog box

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #416 
Changes: Added done button in place of cancel in custom theme dialog
Demo Link: http://susi-done.surge.sh/
@rishiraj824 @isuruAb @uday96 @daminisatya Please Review
Thanks
> Fixes#416: Added done button in custom theme dialog in place of cancel button

- src/components/ChatApp/MessageComposer.react.js
Fixes issue #414 
Changes: Fixed width of message composer by deleting an extra <div> tag
Demo Link:http://susi-fix.surge.sh/
@rishiraj824 @uday96 @isuruAb @daminisatya Please Review
Thanks
> Fixes#414 Fixed the width of message composer

- src/components/ChatApp/MessageComposer.react.js
Fixes issue #422 
Changes:  Added a close button to voice to text dialog box
@madhavrathi  @rishiraj824  @uday96  @daminisatya  please review
> Fixes: #422 - Added a close button to voice to text dialog box

- src/actions/API.actions.js
- src/actions/ChatApp.actions.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/ChatApp/TopBar.react.js
- src/utils/ChatMessageUtils.js
- src/utils/ChatWebAPIUtils.js
Fixes issue #403 
Changes:
- Voice outputs from SUSI for messages sent from Mic
Use Microphone for better results
Will add more intelligent replies in future PRs
Demo Link: 
http://susivoice.surge.sh
> Fixes #403 - Implement a Voice Reply for SUSIs answers when using Mic

- src/actions/API.actions.js
- src/actions/Settings.actions.js
- src/actions/index.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings.react.js
- src/constants/ChatConstants.js
- src/stores/UserPreferencesStore.js
Fixes issue #426 
**Changes:**
* Added a setting `mic input` to let user choose between keyboard input and mic input
* Stored the mic input setting on server if the user is logged in
**Demo Link:** http://mic-input.surge.sh/
> Fixes #426 - Added mic input setting

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/SearchField.react.js
Fixes issue #364 
Changes:  reduce width of the search field and gave a percentage of width.
> Fixes: #364 search field aligned correctly on mobile view

- src/actions/API.actions.js
- src/actions/ChatApp.actions.js
- src/actions/Settings.actions.js
- src/actions/index.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings.react.js
- src/constants/ChatConstants.js
- src/stores/MessageStore.js
- src/stores/UserPreferencesStore.js
Fixes issue #430 
**Changes:**
* Added `Speech Output` setting to choose speech output for speech input
* Stored speech output settings on server
**Demo Link:** http://speechsetting.surge.sh/
> Fixes #430 - Added Speech Output Setting

- src/components/Auth/ChangePassword/ChangePassword.css
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
Fixes issue #390 
**Changes:**
* Added option to `Change Password` when the user is logged in in the Top Bar Drop Down Menu
* Upon successfully changing password, user is prompted to login again and is logged out 
**Endpoint Used**
`BASE_URL+'/aaa/changepassword.json?         'changepassword=EMAIL&password=PASSWORD&newpassword=NEW_PASSWORD   &access_token=ACCESS_TOKEN'`
**Demo Link:**  http://changepwd.surge.sh/
> Fixes #390 - Added Change Password Option

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #432 
Changes: Added buttons to remove URL entered inside the text field. When the text field is empty a snackbar pops up saying "Please enter a valid URL first".
Demo Link: http://susi-remove.surge.sh/
Please Review @rishiraj824 @uday96 @isuruAb @daminisatya 
Thanks
> Fixes #432 Added remove button to remove url

- docs/Accounting.md
- docs/RetrievingHistory.md
Fixes issue #439 
**Changes:**
* Added documentation about change password feature
> Fixes #439 - added documentation about change password feature

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/TopBar.react.js
Fixes issue #443 
Changes: 
- Added glyphicons to menus
Demo Link: 
http://susi-glyphicon.surge.sh
> Fixes #443 - Add glyphicons to Menu Items

- src/actions/API.actions.js
Fixes issue #448
Changes: Commented out the lines. Not deleted as they might be required for testing in future
Demo Link: http://susi-console.surge.sh/
@rishiraj824 @uday96 @isuruAb @daminisatya Please Review
Thanks
> Fixes#448 removed speech inputs from console

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #358
Changes: 
- Added Like and Unlike Buttons for recording feedback
Changes Left
- Need to add the styling to the buttons
Demo Link: 
http://susi-feedback.surge.sh
Screenshot -
> [WIP] Fixes #358 - Make Elements in the UI for Feedback System

- src/actions/API.actions.js
- src/actions/Settings.actions.js
- src/actions/index.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings.react.js
- src/constants/ChatConstants.js
- src/stores/UserPreferencesStore.js
Fixes issue #434 
**Changes:**
* Added setting `Speech Output Always ON` to choose between getting a speech output regardless of input type or not
* Stored the settings on server
* Refactored UserPreferences Store settings related functions to reduce complexity
**Demo Link:** http://speechsetting.surge.sh/
> Fixes #434 - Added setting for speech output always ON

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #446 
Changes: Change the place of theme background image fields
> Fixes: #446- Text Fields added to appropriate places in custom theming dialog box

- docs/Accounting.md
Fixes issue #451 
**Changes:**
* Added the user settings notation, i.e the existing settings functionalities and their JSON key value pairs used to store on the server to docs
> Fixes #451 - Added documentation about user settings notations stored on server

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #452 
Changes: Message Pane colour changes now.
Screenshot:
@uday96  @rishiraj824  @madhavrathi  please review
> Fixes: #452 - Message Pane colour can be changed

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #467 
Changes: 
- change the extra image field.
- remove unwanted codes
@madhavrathi  @rishiraj824  @uday96  please review
> Fixes: #467 - remove extra image field in custom theme dialog-box

- package.json
- src/actions/API.actions.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/ChatApp/VoiceRecognition.js
- src/utils/ChatMessageUtils.js
Fixes issue #428 
Changes: 
- Enhanced Speak Now View (Interim Transcripts are now visible)
- Enhanced Voice Input
- Enhanced Voice Outputs
Demo Link: 
http://susi-voice.surge.sh
> Fixes #428 - Enhances Speech Output and Voice Input functionality

- src/components/ChatApp/TopBar.react.js
Fixes issue #457 
**Changes:**
* Changed the drop down style from `Icon Menu` to `Icon Button + PopOver` to fix the menu overlap
**Demo Link:**  http://susidropdown.surge.sh/
> Fixes #457 - Fixed drop down overlap

- src/__tests__/components/Auth/ChangePassword.js
- src/__tests__/components/Auth/ForgotPassword.js
- src/__tests__/components/Auth/Login.js
- src/__tests__/components/Auth/SignUp.js
- src/__tests__/components/HardwareComponent.js
- src/__tests__/components/SearchField.js
- src/__tests__/components/Settings.js
- src/__tests__/components/VoicePlayer.js
- src/__tests__/components/VoiceRecognition.js
Fixes issue #194
Changes:
- Added test cases for the latest components
> Fixes #194 - Write Test Cases for the App

- src/actions/API.actions.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings.react.js
- src/stores/UserPreferencesStore.js
Fixes issue #480 
Changes: 
- Now settings will reflect even if the user is in Anonymous Mode
- Settings will load according to the logged in state
- From Server when loggedIn
- From Cookies when not 
Demo Link: 
http://susi-localstorage.surge.sh
> Fixes #480 - Store Settings in localStorage for Anonymous Users

- src/actions/API.actions.js
Fixes issue #478 
**Changes:**
* Added a check to see if the response from listUserSettings contains `settings` attribute
**Demo Link:**  http://udaytheja.surge.sh/
> Fixes #478  - Handle corner cases while getting settings from server

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
Fixes issue #468 
Changes: Removed email field from change password dialog and added email to cookies
Demo Link: http://susi-email.surge.sh/
> Fixes#468 removed email field from changepassword dialog

- src/actions/API.actions.js
- src/components/ChatApp/Settings.react.js
- src/stores/UserPreferencesStore.js
Fixes issue #485 
**Changes:**
* Parsed the locally stored settings properly in UserPreferencesStore
**Demo Link:** http://susisettings.surge.sh/
> Fixes #485 - Fix Local storage of settings for anonymous user

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes issue #497 
Changes: Added animation on send button hover and aligned the button properly
Demo Link: http://susi-animation.surge.sh/
Thanks
> Fixes#497 Added animation on send button hover

- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes issue #495 
Changes: 
- Added check whether skill object present in the response.
Demo Link:
http://skill-object.surge.sh
> Fixes #495 - No check for availability of skill object in response

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #501 
Changes: Options Propover close after selecting  a option
@madhavrathi  @rishiraj824  @uday96  please review
> Fixes: #501 - Options Popover close after selecting a option

- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/utils/ChatMessageUtils.js
Fixes issue #494 and #504 
Changes: Got feedback from the server and showed it visually. After this, our feedback system will be complete
Demo Link: http://festive-bath.surge.sh/
@rishiraj824 @uday96 @isuruAb Please Review. Please Start by entering a query like "tell me a quote"
@mariobehling Please do not squash while merging as this PR solves two issues and we need both commit messages in our log
Thanks
> Fixes#494 get feedback data from server

- src/actions/API.actions.js
- src/actions/Settings.actions.js
- src/actions/index.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/constants/ChatConstants.js
- src/stores/UserPreferencesStore.js
Fixes issue #507 
**Changes:**
* Removed individual actions for each setting
* Created a single action for all settings updating only those which changed
**Demo Link:**  http://udaytheja.surge.sh/
> Fixes #507 - Refactored Settings Actions

- src/components/Auth/ChangePassword/ChangePassword.react.js
Fixes issue #522 
Changes: Fixed bug in change password component
Demo Link:http://susi-madhav.surge.sh/
@rishiraj824 @uday96 @isuruAb @DravitLochan Please review
Thanks
> Fixes 522: fixes bug in change pasword component

- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes issue #512 (UI fix)
Changes: Aligned thumbs to right of time/date and the count of feedback is not visible anymore.
Next steps: we need to change the method of putting feedback on the server. @uday96 is working on it, I would also like to help here.
Demo Link: http://fast-hall.surge.sh/
@rishiraj824 @uday96 @isuruAb @mariobehling Please review if the current design is acceptable or not
Thanks
> Fixes#512: Aligned feedback thumbs properly

- src/components/ChatApp/ChatApp.css
Fixes issue #493 
Changes:
- Added Animations to the chat bubbles
Demo Link: 
http://chat-animations.surge.sh
> Fixes #493 Add animations as Chat Appears

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #444 
Changes: Fixed bugs with opening of snackbar by aligning the code properly
Demo Link: http://madhavrathi.surge.sh/
Thanks
> Fixes#444 fixes bugs with snackbar

- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes issue #531
Changes: 
- Handled `parseSkill` function returning undefined object
Demo Link: 
http://skill-object.surge.sh
> Fixes #531 - Blank page after login 

- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #462 Partially
Changes: Remove radio button group and replace it with checkbox
@rishiraj824  @madhavrathi  @uday96  please review this
> Fixes: #462 (partially) Add checkbox instead of radio button group

- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes issue #464
Changes: Added toggle for custom server
Demo Link: http://susi-madhav.surge.sh/
@rishiraj824 @isuruAb @uday96 Please review
> Fixes#464 Fixes forgot password dialog

- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/stores/UserPreferencesStore.js
Fixes issue #506 
**Changes:**
* Stored Speech Rate and Pitch Settings on server for logged in user and in cookies for anonymous user
> Fixes #506 - Save rate and pitch settings on server and cookies

- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes issue #401, #526
Changes: 
- Enhance Speak Now Page, similar to google
- long text being cut off
Demo Link: 
http://susi-voice.surge.sh
> Fixes #401,#526 - Enhance Speak now, long text being cut off

- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/CustomServer.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
Fixes issue #475 
**Changes:**
* Added a new component for custom server
* Used this component in Login, SignUp and ForgotPassword
> Fixes #475 - Created a new component for custom server

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #541
Changes: 
- Now Special Characters are accepted in the password fields of
- Login
- Sign Up
- Change Password
Demo Link: 
http://special-password.surge.sh
> Fixes #541 - Passwords with special characters not being sent over the URL

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes issue #470 
Changes: 
- Added hover state similar to Messenger Feedback
Demo Link: 
http://susi-feedback.surge.sh
> Fixes #470 - Enhances Feedback ui

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Reverts fossasia/chat.susi.ai#539
> Revert "Fixes #470 - Enhances Feedback ui"

- README.md
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/HardwareComponent.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/index.js
Fixes issue #458 
Changes: change the theme styles according to the market leaders.
@madhavrathi  @rishiraj824  @uday96 please review
> Fixes: #458 - Lighten up the standard design

- src/components/Terms/Terms.css
- src/components/Terms/Terms.react.js
- src/index.js
Fixes issue #517 
Changes:  
- Added a term page. 
- referred the term page of LokLak . http://loklak.net/terms.
- used same terms list 
Demo Link: http://isuruab2.surge.sh/terms/
@mariobehling  @rishiraj824  @madhavrathi  @uday96  please review
> Fixes: #517 -Added a terms page

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/VoiceRecognition.js
Fixes issue #527 
Changes: 
- STT/TTS now working on both phones and on Web on chrome
- Added similar animations to the Mic container as on Google.
Demo Link: 
http://susi-voice.surge.sh
> Fixes #527 - Speech to text not working on Chrome browser on mobile phone

- src/components/Overview/Overview.react.js
- src/components/Terms/Terms.react.js
Fixes issue #551 
Changes: 
- add logo to the terms page
- Link logos of Overview and  Terms page to Home page of the app
Demo Link:  http://isuruab.surge.sh/
> Fixes: #551 - Add correct logo to terms page and link them to home page 

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
Fixes issue #437 
Changes:
- Voice Outputs for skills and responses containing text as answers.
- Map ( Text only without hyperlinks )
- Text Response
- Handled all other action types.
Demo Link: 
http://susi-voiceoutput.surge.sh
Sample Query - `universities in germany` `random gif` should give no voice output as there is no text whereas `where am i` and other text inputs will give the voice outputs
> Fixes #437 - Enhance the speech output

- README.md
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/HardwareComponent.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/components/Support/Support.react.js
- src/components/Terms/Terms.react.js
Fixes issue #500 
**Changes:**
* Changed Top bar color to #4285f4
> Fixes #500 - Use #4285f4 for top bar

- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.react.js
Fixes issue #557
Changes: Fixed the buttons according to different screen sizes
Demo Link: http://mysterious-wash.surge.sh/
Thanks
> Fixes #557: fixed buttons in 404 page

- src/components/Team/Team.css
- src/components/Team/Team.react.js
- src/components/Team/TeamList.js
- src/index.js
Fixes issue #513 
Changes:
- Added Team Page at `/team`
- Removed unnecessary folder `firefox_root`
Demo Link:
http://susi-team.surge.sh/team
> Fixes #513 - Propose and implement a team page with images of participating developers

- src/components/Overview/Overview.react.js
Fixes issue #[578]
Dark background wont be there anymore. Overview has only light theme, irrespective of theme set by user.
> Removes overview dark theme(#578)

- src/components/Auth/ChangePassword/ChangePassword.css
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/CustomServer.react.js
- src/components/ChatApp/HardwareComponent.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
- src/components/NotFound/NotFound.react.js
Fixes issue #582
Changes: 
- Changes the design of all popups similar to login pop up
- Added hover styles to all the text fields
- Added `Open Sans` font to headers
- Changed the close button to the top right corner as a symbol
Demo Link: 
http://susi-popups.surge.sh
> Fixes #582 - Improve the design of All Popups

- src/components/Blog/Blog.react.js
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.css
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
- src/index.js
Fixes issue #598 #553 #592
Changes:
Improve the UI of app bar 
make separate component for the app bar 
add new app bar to every static page
@mariobehling  @rishiraj824  @uday96  @madhavrathi  please review this.
> #598 #553 #592 - Improvements of App Bar , make a separate component for app bar

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
Fixes issue #579 
**Changes:**
* Removed `I found this on the web:` when no results are found for websearch
> Fixes #579 - Dont show I found this on the web for empty websearch rss response

- docs/FolderStructure.md
Fixes issue #618
Changes: 
- Added documentation about folder structure
@madhavrathi @uday96 @isuruAb Please review.
> Fixes#618 - Add documentation about the Folder Structure.

- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/NotFound/NotFound.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes issue #604 
Changes:
- The flow of pop ups `Sign Up > Login > Forgot Password` is now working
- Forgot Password works in ` Overview, Support, Team and NotFound pages`
- Preventing all overlaps in Dialogs
Demo Link:
http://susi-popups.surge.sh
> Fixes #604- Make Forgot Password work on the static pages

- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Team/TeamList.js
Fixes issue #619 
Changes: 
- Removed highlighting effect, added hover effect similar to http://api.ai
- Added same font size and style, modified colors
- Aligned the underline over the bar and the shadow below it.
Demo Link: 
http://susi-menu.surge.sh/overview
> Fixes #619-Improve effects of top menu bar

- src/actions/API.actions.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes issue #420 
**Changes:**
* Used `accepted` flag in response of ajax server calls to check the success in
- list user settings
- login
- signup
- forgot password
- change password
> Fixes #420 - Used accepted flag from response to check success status  of server calls

- src/components/Support/Support.react.js
Fixes issue #640 
**Changes:**
* Fixed Signup button in support page
**Demo Link:**  : http://udaytheja1.surge.sh/support
> Fixes #640 - Fix signup button in support page

- package.json
- src/components/Contact/Contact.react.js
- src/components/Overview/Overview.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
- src/index.js
Fixes issue #639, #636, #643
Changes:
Demo Link: 
http://susi-support.surge.sh
@mariobehling I have followed the style of http://chat.susi.ai/support for http://chat.susi.ai/contact, please tell what to add more
> Fixes issue #639, #636, #643 Fix bottom bar on all pages, link up broken links and packages

- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #584 
**Changes:**
* Added a scroll to bottom button in chat app
**Demo Link:** http://susiscrollbottom.surge.sh/
> Fixes #584 - Added Scroll To Bottom button in Chat window

- src/components/StaticAppBar/StaticAppBar.react.js
Fixes issue #650
Changes:  Logged in users get logout option instead of login and signup options
Demo Link: http://isuruab2.surge.sh/
> Fixes: #650 - Logged in users get the login and signup option instead of logout

- src/components/ChatApp/TopBar.react.js
Fixes issue #652 
Changes: 
- Added link to overview page when logged in
Demo Link: 
http://susi-overview.surge.sh
> Fixes #652 - Add link to Overview Page after user is logged in

- package.json
- src/actions/API.actions.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/Overview/Overview.react.js
Fixes issue #600 
Changes: 
- Added message from SUSI, to remind the user if there is no connectivity or connection gets lost, similar to all clients.
To test, please turn off your wifi and send a message. Also, reconnect and then send the message to test if the messages are working again.
Screencast :- 
Demo Link:
http://susi-internet.surge.sh
> Fixes #600- Proposal on how to handle connectivity loss

- src/components/Devices/Devices.css
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.react.js
- src/index.js
Fixes issue #621 
Changes: Removed Docs from top bar and added devices and skills
Demo Link: http://susi-devices.surge.sh/devices
Next Steps:
> Fixes #621 Added device page and skills in top bar

- src/components/Team/Team.css
- src/components/Team/Team.react.js
Fixes issue #659 
Changes: Fixed the cards to have same dimensions as earlier
Demo Link: http://hungry-knot.surge.sh/team
Thanks
> Fixes #659 Fixed the cards of team page

- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes issue #661 
**Changes:**
- Removed Progressive Image
@rishiraj824 @isuruAb @madhavrathi @mariobehling This should fix the site down problem. Please review
> Fixes #661 - Removed Progressive Img

- package.json
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes issue #550
Changes: Now height of message composer increases when it overflows
Screenshot:
> Fixes: #550 - Message composer height increases when it overflows

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
Fixes issue #633
Changes: 
- Add White and black as a custom colour.
- Apply custom colours to Top Bar
@madhavrathi  @mariobehling  @rishiraj824  @uday96  Please review this PR
> Fixes: #633 -Fix and enhance theme

- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.css
- src/components/Devices/Devices.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.css
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.css
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.css
- src/components/Terms/Terms.react.js
Fixes issue #654 
Changes: Fixed the responsiveness of all pages for smaller screens
Demo Link: http://susi-madhav.surge.sh/overview
@rishiraj824 @uday96 @isuruAb Please review and let me know if any component needs to fixed.
Thanks
> fix responsiveness of all pages for smaller screens

- src/components/ChatApp/Settings/Settings.css
- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.css
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes issue #673 
Changes: Remove unwanted CSS that hides the drawer and Left side icon buttons
Demo Link: http://isuruab1.surge.sh/overview/
@madhavrathi  @rishiraj824  @uday1201  please review this
> Fixes: #673 - Left Side drawer and icon button are appearing on small screens

- src/components/Overview/Overview.react.js
Quick typo fix. Interligent --> Intelligent.
> Fixed typo Overview.react.js

- src/components/StaticAppBar/StaticAppBar.react.js
Fixes issue #684 (Partially)
Changes: Fixed TopBar in firefox
Demo Link: http://susifirefox.surge.sh/overview
@rishiraj824 @isuruAb @uday96 Please run the demo link on firefox to review this PR.
Thanks
> Fixes #684 Fixed TopBar in firefox

- src/components/Blog/Blog.css
- src/components/Blog/Blog.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.css
- src/components/Terms/Terms.css
Fixes issue #586 
Changes: Added cards for all the latest blogs in the feed.
Demo Link: http://susi-madhav.surge.sh/blog
Next Steps : 
> Added blog page

- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #686 
Changes: 
- Removed redundant hamburger
Demo Link: 
http://susi-hamburger.surge.sh/settings
> Fixes #686 - Redundant hamburger on /settings to be removed

- src/components/Blog/Blog.react.js
- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #683 
**Changes:**
- Added scroll to top when a static page is opened
**Demo Link:**  http://udaytheja1.surge.sh/
**Screencast Link:**  https://vimeo.com/228680036
> Fixes #683 - Scroll to top when a static page is opened

- public/index.html
- src/components/Blog/Blog.react.js
- src/components/ChatApp/ChatApp.react.js
- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #691
Changes: Added suitable title tags to all pages.
Demo Link: http://susimadhav.surge.sh
Thanks
> Fixes #691 Added proper title to all pages

- package.json
- src/components/Blog/Blog.react.js
Fixes issue #702 
**Changes:**
- Added a loading component while blogs are fetched
**Demo Link:** http://udaytheja1.surge.sh/blog
**Screencast for the change:**
> Fixes #702 - Added a loading gif while blogs are fetched

- docs/Accounting.md
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #699 
**Changes:**
- Removed duplicate declarations of `componentDidMount` from static pages
- Updated the documentation for settings as discussed in https://github.com/fossasia/accounts.susi.ai/issues/125#issuecomment-320536671 and implemented in https://github.com/fossasia/chat.susi.ai/pull/689
Have not added custom theme settings in documentation as it's not finalized yet across all clients.
> Fixes #699 - Update documentation about settings

- src/components/Blog/Blog.css
- src/components/Blog/Blog.react.js
- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.react.js
- src/components/Footer/Footer.css
- src/components/Footer/Footer.react.js
- src/components/Overview/Overview.css
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #677
Changes: Added the previous footer and made a separate component for it
Next steps:
Demo Link: http://magenta-effect.surge.sh/overview
for screen width (1366px wide):
for screen width < 800px : 
for screen width < 300px: 
@rishiraj824 @uday96 @isuruAb Please review
Thanks
> Fixes #677 Added separate component for footer

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/StaticLayout/StaticLayout.react.js
- src/index.js
Fixes issue #700 
Changes: 
Added another set of colour bubbles to choose custom button colour. 
Save those data on server.
Demo Link:  http://isuruab.surge.sh/
@madhavrathi  @uday96  @rishiraj824  please review this
> Fixes #700 - Button colour is not change to dark colour after choosing custom colours

- README.md
- docs/AskSUSI.md
Fixes issue #710 
Changes: Fixed heading format
Demo Link: http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/3b8c1b39-64f4-4837-aee6-8e3648f6cd13_preview/
> Fixes #710 Fix markdown issues

- src/App.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.css
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/components/Terms/Terms.react.js
- src/index.js
Fixes issue #705 
Changes: 
- Implement Child routes for each static and non static pages.
- Remove unwanted codes
@rishiraj824  @uday96  @madhavrathi  @mariobehling  please review
> Fixes #705 - Update routes to perform faster

- src/components/ChatApp/MessageComposer.react.js
Fixes issue #714 
Changes: 
- Added multiline message on pressing `Shift+Enter`
Demo Link:
http://stiff-crown.surge.sh/
> Fixes #714 - Multiline Message

- src/App.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #718 
Changes: 
Demo Link: http://isuruab3.surge.sh/settings
> Fixes: #718 - hide custom theme option for anonymous users 

- src/components/Contact/Contact.css
- src/components/Footer/Footer.css
- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.css
- src/components/Support/Support.css
- src/components/Terms/Terms.css
Fixes issue #725
Changes: 
- Fixed footer  responsiveness
- Refactored and removed the redundant CSS
Demo Link:
http://susi-footer.surge.sh
> Fixes #725-Fix footer and ensure complete responsiveness

- src/components/ChatApp/Settings/Settings.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes issue #716   #713
Changes: 
- Used existing StatiAppBar component on settings page and reduces the complexity of Settings page.
- Previously Sign Up form was not working when we trying to open it from Login Dialog.
-options drop down comes under the correct position of the app bar
Demo Link: http://isuruab.surge.sh/settings
@sudheesh001  @madhavrathi  @uday96  please review this
> Fixes #716  #713 - Use existing Static App Bar on Settings page

- src/actions/API.actions.js
- src/actions/History.actions.js
- src/components/Blog/Blog.react.js
Fixes issue #744 
**Changes:**
- Fixed the bug to now show only the number of results denoted by `count` in the server response
**Demo Link:**  http://styleswipe.surge.sh/
> Fixes #744 - Limit rss results using count attribute

- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.react.js
Fixes issue #747 
Changes: 
- Fixed 404 page causing overlap with the footer.
Demo Link: 
http://exclusive-yak.surge.sh
> Fixes #747 Fix 404 Page

- src/__tests__/components/Blog/Blog.js
- src/__tests__/components/Contact/Contact.js
- src/__tests__/components/Devices/Devices.js
- src/__tests__/components/NotFound/NotFound.js
- src/__tests__/components/Overview/Overview.js
- src/__tests__/components/Privacy/Privacy.js
- src/__tests__/components/StaticAppBar
- src/__tests__/components/Support/Support.js
- src/__tests__/components/Team/Team.js
- src/__tests__/components/Terms/Terms.js
- src/__tests__/components/Translate.js
Fixes issue #741 
Changes:
- Added all test cases to remaining components
> Fixes #741 - Add all leftover test cases to new components

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes issue #750 
Changes: Fixed alignment of send button in Firefox.
Demo Link: http://firefoxfix.surge.sh/
Thanks
> Fixes #750 Fixed send button in firefox

- docs/FolderStructure.md
Fixes issue #745 
Changes: 
- Added docs about `src/components/Translate`
> Fixes #745 - Update docs about the latest folder updates

- src/components/ChatApp/CustomServer.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #736 
Changes: Added relevant comments.
> Fixes: #736 partially - Added relevant comments

- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
Fixes issue #762 
Changes: Added play store link for app in overview and devices page
Demo Link: http://appstoresusi.surge.sh/overview
@rishiraj824 @isuruAb @uday96 Please Review
Thanks
> Fixes #762 Added playstore link for app

- src/components/Blog/Blog.react.js
- src/components/Devices/Devices.react.js
- src/components/Footer/Footer.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/components/Privacy/Privacy.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #736 (Partially)
Changes: Added comments for all static pages.
Next Steps:
Thanks
> Fixes #736 Added comments for all static pages

- docs/TranslationsWithWeblate.md
Fixes issue #767 
Changes:
- Add docs about Weblate
> Fixes #767 Add docs about Weblate

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
Fixes issue #736 
**Changes:**
Added comments to : 
- Auth
- Settings
- Message List Items
> Fixes #736 partially - Added comments to Auth, Settings and MessageListItems

- src/actions/API.actions.js
- src/actions/History.actions.js
- src/actions/Settings.actions.js
- src/stores/MessageStore.js
- src/stores/UserPreferencesStore.js
- src/utils/ChatMessageUtils.js
Fixes issue #736 
Changes: 
Add comments to following components
- `actions`
- `stores`
- `utils`
- `stores`
> Fixes #736 (partially) Add relevant comments

- src/components/Team/TeamList.js
Fixes issue #779 
Changes: Fixed broken links
Thanks
> Fixes #779 Fixed broken links on team page

- src/components/Blog/Blog.css
- src/components/Blog/Blog.react.js
- src/components/Contact/Contact.react.js
- src/components/Team/Team.react.js
Fixes issue #777
Changes: Added a word break for long URLs
Demo Link: http://isuruab.surge.sh/blog
@madhavrathi  @rishiraj824  @uday96  please approve
> Fixes: #777 - added word breaks for long URLs

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #761 
Changes: Added Tab layout for settings
Next Steps: 
Screenshot : 
Demo Link: http://settings-susi.surge.sh/settings
> Added Tab layout for settings

- README.md
Fixes issue #775 
**Changes:**
- Updated ReadMe about Web Speech API  (https://github.com/fossasia/chat.susi.ai/issues/685) 
> Fixes #775 - Update ReadMe about Web Speech API browser compatibility

- src/components/Footer/Footer.react.js
Fixes issue #784 
Changes: added <Link> tags  to footer menu instead of anchor tags.
@uday96  @rishiraj824  @madhavrathi  please review
> Fixes: #784 - add <Link> to footer menu

- src/components/Team/Team.css
Fixes issue #788 
Changes: Fixed team page for smaller screens
Demo Link: http://susi-madhav.surge.sh/team
Thanks
> Fixes #788 Fixed team page for smaller screens

- README.md
Changes:
- Add Weblate badge to README.md from https://hosted.weblate.org/widgets/susi-ai/?component=chat
@isuruAb @madhavrathi @uday96 Please approve
> Add Weblate badge to project README.md

- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #785 
Changes: 
- added glyphicons
Link : http://shiny-iron.surge.sh/settings
@uday96 @madhavrathi @isuruAb Please review
> Fixes #785 : Added glyphicons to settings menu

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/components/Privacy/Privacy.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
Fixes issue #766 partially.
Changes: Background wallpapers option works correctly.
Further development: Need to store wallpaper data on server. will start work on that after endpoint is ready.
@madhavrathi  @rishiraj824  @uday96  please review
> Fixes: #766 partially - background wallpapers working correctly

- README.md
- src/components/ChatApp/Settings/Settings.react.js
Fixed issue #769 
Changes: Changed the theme dropdown menu to a radio button, because the theme value wasn't getting toggled in the dropdown menu. Works perfectly now.
Demo Link: http://crooked-adjustment.surge.sh/
> Fixed the theme bug in settings

- src/components/ChatApp/TopBar.react.js
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/stores/UserPreferencesStore.js
Fixes issue #792 
Changes: Changed server calls to https
Demo Link: https://murky-cord.surge.sh/
@rishiraj824 @isuruAb Please Review
Thanks
> Fixes #792 Changed requests to https

- src/components/ChatApp/Settings/Settings.react.js
Fixes issue  #800 
Changes:Changed the display of the radio buttons from non responsive (as in https://ibb.co/cjsb15) to responsive by changing them to block rather than inline ones (as in https://ibb.co/esQYG5)
https://ibb.co/cjsb15
to
https://ibb.co/esQYG5
> Made radio buttons responsive

- src/components/ChatApp/CustomServer.react.js
- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
- src/index.css
Fixes issue #796 - Enhance style and functionality of settings page 
Changes:
- Added save button to each page
- Aligned text on right side pages on the left and implement similar padding to twitter
- Reduced the margin between left and right section of settings panel. 
- Moved the "theme" option to a dedicated tab 
- Changes the background color to match with susi.skills.ai
Demo Link: http://well-made-value.surge.sh/
Screenshot:
> Fixes issue #796 - Enhance style and functionality of settings page

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/SearchField.react.js
- src/components/ChatApp/TopBar.react.js
Fixes issue #812 
Changes: 
- On clicking the search icon, the input field gets focused automatically
- When there is no result for a search query, a message "No Results!" is shown
- The search icon hides when the search is open
- On pressing Esc when the search is open, the search closes
- Increase padding in the case-sensitive toggle
Demo Link: [special-chairs.surge.sh](http://special-chairs.surge.sh/)
> Fixes issue #812 - Enhance search function

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #820 
Changes:
- The settings component made responsive.
- Added drop-down menu for smaller screen size.
Demo Link: http://thiyagaraj-susi.surge.sh/
> Make settings component responsive - fix issue 820

- docs/FolderStructure.md
> Update FolderStructure.md with minor spelling fixes #794

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #852 
Changes:
* There was a mistake where the background color was assigned. The background color was assigned before setting the value of the variable.
* The order of the code was corrected inside the render function.
[Demo link](http://cooperative-twist.surge.sh)
> Fixes #852 : Background color changes with theme change

- .eslintrc
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/stores/UserPreferencesStore.js
Fixes issue #835 
Changes: 
* Make correction in the state name that was responsible for setting the theme name
* Send correct key name to the request to the Server. It was incorrectly sent as **Theme**, instead of **theme**.
[Demo Link](http://cooperative-twist.surge.sh)
> Fixes #835 : Theme changes doesn't change Mic icon

- package.json
- src/components/ChatApp/Settings/Settings.react.js
- src/stores/UserPreferencesStore.js
#855 Fixes issue #797 
Changes: 
@madhavrathi  @rishiraj824  please review this
> Fixes: #797 -Settings Page Add mobile section

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/stores/UserPreferencesStore.js
Fixes issue #868 
Changes: Made the image changes to be saved in the backend server
[Demo Link](http://cooperative-twist.surge.sh)
> Fixes #868: Images can now be saved using theme changer

- README.md
- docs/Accounting.md
- docs/AskSUSI.md
- docs/FolderStructure.md
- docs/RetrievingHistory.md
- src/actions/HardwareConnect.actions.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/CustomServer.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/Contact/Contact.css
- src/components/Overview/Overview.css
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.css
- src/components/Team/Team.css
- src/components/Terms/Terms.css
Applies to issue #794. Combined pull request of PR #846, 847, 848, 849.
> Correct minor spelling issues

- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/index.css
Fixes issue #861 
Changes: 
* Remove input autofill yellow background
* Remove custom font family from loginForm h3
* Change login email field type from to email
* Show loading status while logging in
Demo Link: http://cold-lift.surge.sh/
> Fix #861 UI improvements in Login screen

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #869 partially
The font color is not maintained in the state or the settings. Will make a work on it and separately make the PR considering the high priority. This PR solves other problems as stated in the issue.
Changes:
-Change all text from "Change color of.." to "Color of..."
-In front of "Save" button add "Reset" to set colors to standard colors of SUSI.AI
-Delete "Done" button
Demo Link: http://susi-demo.surge.sh/
> Improve themes area interaction - fix partially #869

- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #869 
Changes: 
-Automatically change text colour according to the background colour.
Demo Link: http://obnoxious-death.surge.sh/
> Improve themes area interaction fix #869

- src/components/Auth/Login/Login.react.js
Fixes issue #882
Changes: Placed login and sign up side by side.
Demo Link:  [http://hanging-purpose.surge.sh/](http://hanging-purpose.surge.sh/)
> Improves UI of Login Popup.

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #899 
Changes: Added a back to login button on the ForgotPassword dialog.
Demo Link: [here](https://poor-friends.surge.sh)
>  Fixes #899, Added a 'back to login' button to the ForgotPassword dialog

- README.md
- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes issue #898
Changes: 
- Now thumbs down will have red color.
> Fixes #898 Thumbs up and down UI improvement

- src/components/ChatApp/Settings/Settings.react.js
- src/components/Translate/Translate.react.js
Fixes issue #913 
**Changes:** 
- Remove bug of language translation 
- Add 2 more languages in the drop-down menu of Language Settings
**Demo Link:** 
[lang-demo.surge.sh](http://lang-demo.surge.sh)
> Fixes #913 : Resolve language translation bug

- README.md
Fixes issue #916 
Changes: 
- Proper directions for deployment so that new contributors don't find face any problem while deploying using surge.
> Fixes#916 Surge deployment documentation

- src/components/ChatApp/Settings/Settings.react.js
Fixes issue #874 
Changes:
The countries with undefined country codes have been removed from the phone number list.
The changes can be viewed by going to Mobile tab in Settings.
Demo Link: solid-rainstorm.surge.sh
@mariobehling  @madhavrathi @isuruAb @rishiraj824 Please review :)
> Countries with undefined country codes removed as per #874

- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnFacebook.js
Fixes issue #798 
Changes: Added share on Facebook option.
Demo Link: http://obese-hate.surge.sh/
> Added Share on facebook option

- docs/INSTALLATION_LOCAL_TAMIL.md
- docs/INSTALLATION_SURGE_TAMIL.md
Second Step steps for issue #969
Changes:
-Tamil install instructions added
> Contributed to #969 : Added Install Instructions in Tamil

- src/components/ChatApp/Settings/ShareOnFacebook.js
- src/components/Translate/am.json
- src/components/Translate/de.json
- src/components/Translate/en.json
- src/components/Translate/es.json
- src/components/Translate/fr.json
- src/components/Translate/gr.json
- src/components/Translate/hi.json
- src/components/Translate/jp.json
- src/components/Translate/zh.json
Fixes issue #996 
Changes:
1. The background color and the label color of the share button was changed.
2. The fields for "Share" and "Share about SUSI on Facebook" were added to the JSON files of all languages.
3. onClick was changed to onTouchTap and keyboardFocused was set to True.
Demo Link: http://succinct-exchange.surge.sh
@madhavrathi @isuruAb @rishiraj824 Please review ASAP 😄
> Fixed the bugs in the share on Facebook section

- .github/CONTRIBUTING.md
Fixes issue #992 
Added `CONTRIBUTING.md` in the project.
Demo Link: [Add here the link where your changes can be seen]
@leto @anchepiece Please review. Thanks
> Fixes #992 Add CONTRIBUTING.md

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #859
Changes: First time users get Welcome message and Introductory video on a dialog box
> Fixes: #859 - First time users get Welcome message and introductory video

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes issue #1006 
Changes: changes color of dislike in dark theme
Demo Link: https://pr-1021-fossasia-susi-web-chat.surge.sh
> Fixes#1006 Like and dislike buttons shows same colour in dark theme

- docs/INSTALLATION_SURGE_ENGLISH.md
The process remains the same for MAC users in the terminal :D
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh
> (Documentation) Added Mac with Ubuntu, for mac users :D

- .github/PULL_REQUEST_TEMPLATE
Fixes #1014 
Changes: Changed PULL_REQUEST_TEMPLATE to close issues automatically when PR is merged
> close issue automatically when PR is merged

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes issue #1029
Changes: Changed the thumb styling for Scrollbar imported from react-custom-scrollbars library for message section to increase it's visibility.
Demo Link: https://pr-1030-fossasia-susi-web-chat.surge.sh
> Fixes #1029. Changed the thumb styling for Scrollbar in message section

- .gitignore
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #1041
Changes:
Adds option for writing a tweet about susi AI on the settings page,
share section.
Demo Link: https://pr-1043-fossasia-susi-web-chat.surge.sh
> Fixes #1041: Adds twitter sharing option to settings

- public/403.html
- public/css/style.css
- public/index.html
- public/less/style.less
- **_Built custom function/algorithm to detect Internet Explorer Users._** :heart_eyes: 
- **Integrated the algorithm intelligently to chat.susi.ai** :+1: 
- On success, Linked to a **403 ERROR Page**
> Reference : https://stackoverflow.com/questions/19795982/http-status-code-for-unsupported-browser
- Designed a custom 403 ERROR Page :sparkles:
> Fixes #959 : Implemented Error Page for users of Internet Explorer

- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #1044 
Changes: 
- Add Google plus share link
Demo Link: https://pr-1053-fossasia-susi-web-chat.surge.sh
> Adding Google + share Button

- README.md
A screencast made by me while deploying SUSI on surge
> Added a link to video, to improve surge deployment docs

- Dockerfile
- README.md
Fixes #1061 
Added `Dockerfile` and Auto deployment button for the same in `README.md`
Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh
@rishiraj824 @madhavrathi @mariobehling Please review. Thanks!!
> Fixes #1061 Dockerize chat.susi.ai and Auto deploy button for repo

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #930
Changes:
Fixes bug of not being to send and change feedback of old messages. Now
we can allow sending feedback of old messages as well.
Demo Link: https://pr-1054-fossasia-susi-web-chat.surge.sh
> Allows sending feedback on old messages as well

- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1086 
Changes:
- Fix bug on clicking Share button. Now, the content of Sharing tab appears.
- Extend Sharing to google,twitter in logged out state
Demo Link: https://pr-1087-fossasia-susi-web-chat.surge.sh
> Fixes 1086: Extend Sharing to google,twitter in logged out state

- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #1073 
Changes: 
Refer #1075 
Demo Link: robust-approval.surge.sh
Refer #1075
> Resolves #1073. Buttons no longer implicitly highlighted.

- src/components/ChatApp/ChatApp.css
Fixes #1110 
**Changes:** Changed the CSS of the feedback buttons so as to make them less clustered with the message time.
**Demo Link:** https://pr-1110-fossasia-susi-web-chat.surge.sh
**Current state:**
**Updated state:**
> Improves CSS of Feedback Buttons

- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes #1118 
Changes: Sharing of query and response now possible via Twitter
Demo Link: http://placid-language.surge.sh/
> Sharing of query and response via Twitter

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1098 
Changes: Added back to chat option on the settings page.
Demo Link: http://back-to-chat-01.surge.sh/
> Added back to chat option on the settings page

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1078 
Changes: Changed the colour of top to bottom button when theme is dark.
Demo Link: http://fix-1.surge.sh/
Before:
After:
> Changed the colour of bottom button when the theme is dark

- src/components/Auth/Login/Login.react.js
Fixes #1130 
Changes: 
Implemented Dialog box for error message and made password field empty when error message is displayed.
Demo Link: http://issue_1130-fossasia-susi-webchat.surge.sh/
Before:
After:
> Implemented Dialog box for error message 

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
Fixes #1146 
**Changes:** Added a toast message when the user doesn't give any speech input, or when the speech recognition returns false.
**Demo Link:** https://pr-1146-fossasia-susi-web-chat.surge.sh
> Adds a toast message when speech recognition returns false

- src/components/ChatApp/ChatApp.css
Fixes #1151
Changes: Improved the UI of ChatApp.
Demo Link: http://faint-month.surge.sh/
Before -
After -
> Improve ChatApp UI

- package.json
- src/components/Devices/Devices.react.js
Fixes #1126 
Changes: Adds AOS effects to the different sections of the About ---> Devices page.
Demo Link: https://pr-1126-fossasia-susi-web-chat.surge.sh
> Adds AOS to About ---> Devices page

- src/components/Auth/Login/Login.react.js
Demo Link: lean-sheep.surge.sh
> Add Icons for email and password fields #1149

- package.json
- src/components/Overview/Overview.react.js
Fixes #1124 
Changes: Adds AOS effects to the different sections of the Overview page.
Demo Link: https://pr-1124-fossasia-susi-web-chat.surge.sh
> Adds AOS to Overview page

- src/components/ChatApp/MessageComposer.react.js
Fixes #1171 
Changes:  Removed an unwanted block of code in ./src/components/ChatApp/MessageComposer.react.js
Demo Link: NA
NA
> Removed unwanted block of code

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #1189 
**Changes:** Fixed the rendering issues when a logged in User was not able to go to chat screen on clicking on the SUSI Logo.
> Fixes rendering of the view when you are logged in

- src/components/Auth/Login/Login.react.js
Fixes #1204 [Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: Corrected syntax in import action lock statement of login.react.js[Add here what changes were made in this issue and if possible provide links.]
> Fix syntax error in login.react.js

- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/SearchField.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
- src/components/ChatApp/VoiceRecognition.js
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
Fixes #1201 
Changes: Updated the share message on Twitter
> Changes share message on Twitter

- README.md
Fixes #1197 
**Changes:** Adds Component Colors info of Dark Theme in the Readme file.
> Updates Readme file with info of Component Colors of Dark theme

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #1211 Feedback thumbs are not working. 
Changes: Added network calls feedback buttons.
Demo Link: http://susi--chat.surge.sh/
NA
> Made the feedback thumbs functional

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1160 
Changes:
Search text persists when the case sensitivity switch in toggled.
Demo Link: https://pr-1185fossasia-susi-web-chat.surge.sh
> Fixes #1160: Persist search text when case sensitivity is toggled

- src/components/ChatApp/TopBar.react.js
Fixes #1196 
Changes: 
The SUSI logo now points to the about page
> Linking SUSI logo to Index page

- src/components/Team/TeamList.js
#1223 
Changes: Added my image in SUSI team
Demo Link: https://pr-1232-fossasia-susi-web-chat.surge.sh
> Added Sanskar in the Team

- src/components/ChatApp/TopBar.react.js
- src/components/Team/Team.react.js
- src/components/Team/TeamList.js
Fixes #1228 
Changes: Added a section of Alumni in the Team tab.
Demo Link: https://pr-1228-fossasia-susi-web-chat.surge.sh
> Added alumni section in team tab

- src/components/Overview/Overview.react.js
Fixes #1124 
Changes: Removed AOS from Overview page
Demo Link: https://pr-1124-fossasia-susi-web-chat.surge.sh
> Removed AOS from Overview page

- package.json
- src/components/Devices/Devices.react.js
Fixes #1126 
Changes: Removed AOS from Devices page in order to keep it consistent with #1124 
Demo Link: https://pr-1126-fossasia-susi-web-chat.surge.sh
> Removed AOS from Devices page

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1255 
Changes: Prevents reloading of Chat page when Back to Chat button is clicked
Demo Link: https://pr-1255-fossasia-susi-web-chat.surge.sh
> Prevents reloading of Chat page when Back to Chat button is clicked

- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1259 
Changes: Added menuItems on StaticAppBar comoponent
Demo Link: https://pr-1260-fossasia-susi-web-chat.surge.sh
> Fixes: 1259: Uniform hamburger menuItem across all routes

- src/components/ChatApp/Settings/Settings.react.js
Changes:Revert the changes from General to Accounts in settings tab as discussed in #1233 
Demo Link: http://thirsty-worm.surge.sh/
> Revert General with Account in settings tab

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1257 
Changes: 
Changes: 
Remove "Back To Chat" from Settings menu
Demo Link: https://pr-1262-fossasia-susi-web-chat.surge.sh
> Fixes #1257: Remove "Back To Chat" from Settings menu

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
Fixes #1273 
Changes: 
* Make Speech Settings functional
* Move Speech Output Settings to Speech Tab from Dialog Box
* Fix indentation
Demo Link: https://pr-1279-fossasia-susi-web-chat.surge.sh
> Fixes #1273 : Fix Speech Settings

- src/components/ChatApp/SearchField.react.js
- src/components/ChatApp/TopBar.react.js
Fixes #1138 
Changes: The bugs with the search bar are fixed.
Demo Link: https://pr-1278-fossasia-susi-web-chat.surge.sh
> Fixed bugs with search bar

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1274 
Changes: 
Changed css and fixed some indentation
Demo Link: https://pr-1275-fossasia-susi-web-chat.surge.sh
* Scroll enabled on small window
* Made the page responsive
> Fixes #1274 : Make Settings page responsive and enable scroll

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1273 
Extended the section instead of scroll
Demo Link: https://pr-1286-fossasia-susi-web-chat.surge.sh
> Fixes #1273 : Remove scroll from Speech Settings

- src/App.js
- src/components/ChatApp/TopBar.react.js
- src/components/NotFound/NotFound.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1285 
Changes: Now only the Logged In Users can access Settings
Demo Link: https://pr-1289-fossasia-susi-web-chat.surge.sh
> Provide Settings only for Logged In Users

- src/components/StaticAppBar/StaticAppBar.react.js
- src/index.js
Fixes #1287 
Changes: Remove themes option from other routes, some refactoring.
Demo Link: https://pr-1294-fossasia-susi-web-chat.surge.sh
> Fixes #1287: Do not show themes option on other routes

- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
Partially completes #1243 
Changes: Simplify login dialog, some refactoring
Demo Link: http://susi-chat-pr-1298.surge.sh/
> Simplify login Dialog

- src/App.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1305 
Changes: Fixed issues in Settings due to which User was unable to change most Settings.
Demo Link: https://pr-1306-fossasia-susi-web-chat.surge.sh
> Fixed issues due to which User was unable to change most of the settings

- src/components/Auth/ChangePassword/ChangePassword.css
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1234 
Changes: Implemented new UI for password tab as discussed in #1234  
Demo Link: https://pr-1314-fossasia-susi-web-chat.surge.sh
> Implement new Password Tab

- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1320 
Changes: Added Dashboard to Hamburger menu and removed Botbuilder
Demo Link: https://pr-1321-fossasia-susi-web-chat.surge.sh
> Add Dashboard to Hamburger menu and remove Botbuilder

- src/App.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1312 
**Changes:** Changed the component colors of dark theme to make them more suitable according to dark theme.
**Demo Link:** https://pr-1313-fossasia-susi-web-chat.surge.sh
**Before:**
**Now:**
> Changed component colors of dark theme

- src/components/Translate/Translate.react.js
Fixes #1315 
Changes: Changed the code of Translate.react.js in `/src/components/Translate/Translate.react.js`
Made the code smaller and cleaner
Demo Link: [naive-eggs.surge.sh](http://naive-eggs.surge.sh/)
> Translate code refactor

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1316
**Changes**: Added scroll to top functionality for users to go to top messages.
**Demo Link**: [flashy-bird.surge.sh](http://flashy-bird.surge.sh/) (Updated)
> Scroll To Top Messages

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #1334 
**Changes:** Now the social media share buttons are of equal width.
**Demo Link:** https://pr-1335-fossasia-susi-web-chat.surge.sh
**Before:**
**After:**
> Made the width of the Social media share buttons equal

- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
Fixes #1322 
Demo Link: https://pr-1339-fossasia-susi-web-chat.surge.sh
Changes: 
- Before:
- Now:
> Implement new UI for login Page

- src/components/ChatApp/MessageSection/DialogSection.js
Fixes #1351 
Changes: Fixed console errors due to use of unknown props in iframe tag
Demo Link: https://pr-1352-fossasia-susi-web-chat.surge.sh
> Fixed console errors due to use of unknown props in iframe tag

- src/components/Auth/SignUp/SignUp.react.js
Fixes #1356 
Changes: Implement UI of signup similar to login page.
Demo Link: https://pr-1369-fossasia-susi-web-chat.surge.sh
> Implement UI of signup similar to login page

- src/components/ChatApp/TopBar.react.js
Fixes #1374 
Changes: Do not hide dropdown when searching
Demo Link: https://pr-1375-fossasia-susi-web-chat.surge.sh
> Fixes #1374: Do not hide dropdown when searching

- src/actions/API.actions.js
- src/components/ChatApp/Settings/Settings.react.js
- src/stores/UserPreferencesStore.js
Fixes #1378 
Changes: 
- Fix issue with adding mobile number to server. Now we can successfully save our mobile to server.
- Change position of mobile tab just below password tab.
- Change the message to "In future, we will text a verification code to your number"
Demo Link: https://pr-1384-fossasia-susi-web-chat.surge.sh
> Fix issues with mobile tab

- package.json
- src/components/ChatApp/Settings/Settings.react.js
- src/components/MapContainer/MapContainer.react.js
Fixes #1361
Changes: Implemented Map view in Devices section.
Demo Link: https://pr-1387-fossasia-susi-web-chat.surge.sh
> Implemented Map view in Devices section

- .eslintrc
Fixes #1388 
* Ignored react/no-deprecated warnings.
Demo Link: https://pr-1389-fossasia-susi-web-chat.surge.sh
NA
> Fixes #1388: Fixes travis CI failure

- src/components/ChatApp/Settings/Settings.react.js
- src/config.js
Fixes #1400 
Changes: Moved API key required for Map View to `config.js` file
Demo Link: https://pr-1401-fossasia-susi-web-chat.surge.sh
> Moved API key to config.js file

- .travis.yml
Fixes #1413 
Changes: Upgrade node_js version in travis.yml file.
Demo Link: https://pr-1414-fossasia-susi-web-chat.surge.sh
> Upgrade node_js version in travis.yml

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1405 
Changes: Now, editing rows in the Table View will update Map View immediately.
Demo Link: https://pr-1429-fossasia-susi-web-chat.surge.sh
> Editing rows in Table View will now update Map View immediately

- src/actions/API.actions.js
Fixes #1420 
Changes: 
Changes the IP to GEO API to http://ip-api.com/json
Demo Link: http://susi-ai-chat.surge.sh/
> Changed the IP to GEO API

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1433 
Changes: Made the font size consistent for all subheadings in all tabs in Settings.
Demo Link: https://pr-1434-fossasia-susi-web-chat.surge.sh
> Made the font size consistent for all subheadings in all Setting tabs

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/utils/helperFunctions.js
Fixes #1326 
* Set cookies for entire SUSI subdomains
* Changed the domain attribute of cookies
Demo link not applicable. Changes made are in accordance to fossasia/susi_skill_cms#902
NA
> Fixes #1326: Set cookies for entire SUSI subdomains

- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/SearchField.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/Overview/Overview.react.js
Fixes #1436 
Changes: The main changes are in Settings, set default states and working fine without componentWillMount
Demo Link: https://pr-1436-fossasia-susi-web-chat.surge.sh
> Remove componentWillMount fixes #1436

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1404 
Changes: Add delete account option in account tab
Demo Link: https://pr-1444-fossasia-susi-web-chat.surge.sh
> Add delete account option in accounts tab in settings

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Blog/Blog.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #1431 
Changes: Removed unnecessary console logs.
Demo Link: https://pr-1449-fossasia-susi-web-chat.surge.sh
> Removed unnecessary console logs

- src/components/Footer/Footer.react.js
Fixes #1447 
Changes: Add api to footer
Demo Link: https://pr-1448-fossasia-susi-web-chat.surge.sh
> Fixes #1447: Add API to footer

- src/components/ChatApp/TopBar.react.js
- src/components/Contact/Contact.css
- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.css
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.css
- src/components/Team/Team.css
- src/components/Terms/Terms.css
Fixes #1437 
Changes: 
- Add some spacing to the right of menu like accounts
- Implement same top bar on all routes
Demo Link: https://pr-1440-fossasia-susi-web-chat.surge.sh
> Implement same top bar and fix spacing issue with menu

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1451 
Changes: Moved Map below Table in Devices tab
Demo Link: https://pr-1458-fossasia-susi-web-chat.surge.sh
> Moved Map below Table in Devices Tab

- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.react.js
Fixes #1445 
Changes: 
- Standardise Not found page on all routes similar to https://github.com/fossasia/accounts.susi.ai/pull/323
- Remove footer from Not found page
- Login button should redirect to home page instead of showing login dialog when already loggedIn
Demo Link: https://pr-1446-fossasia-susi-web-chat.surge.sh
> Standardise Not found page on all routes

- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1459 
Changes: Add link to admin panel in menu
Demo Link: https://pr-1465-fossasia-susi-web-chat.surge.sh
> Add link to admin in menu

- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/ChatApp/VoiceRecognition.js
Fixes #1439 
Changes: componentDidUpdate is the prefect hook which can used and works fine
Demo Link: https://pr-1439-fossasia-susi-web-chat.surge.sh
> Removes unsafe componentWillReceiveProps hook fixes #1439

- src/actions/API.actions.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
- src/components/ChatApp/TopBar.react.js
- src/components/Devices/Devices.react.js
- src/components/Footer/Footer.react.js
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.react.js
- src/stores/UserPreferencesStore.js
- src/utils/urls.js
Fixes #1474 
Changes: Implemented config file for URLs
Demo Link: https://pr-1474-fossasia-susi-web-chat.surge.sh
> Config file for hardcode URL #1474

- src/actions/API.actions.js
Fixes #1487
Changes: No CORS error for speech translate. 
Demo Link: https://pr-1487-fossasia-susi-web-chat.surge.sh
> Fixes Translate CORS error and warning #1487

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1489
Demo Link: https://pr-1489-fossasia-susi-web-chat.surge.sh
> Fix Console warning operator shorthand in Settings#1489

- src/config.js
Fixes #1495 
Changes: Fetch api keys from server instead of hard coding
Demo Link: https://pr-1496-fossasia-susi-web-chat.surge.sh
NA
> Fetch api keys from server instead of hard coding

- src/components/ChatApp/Settings/Settings.react.js
- src/components/MapContainer/MapContainer.react.js
- src/components/TableComplex/TableComplex.react.js
Fixes #1517 
Changes: Added inline documentation for Table View and Map View code
Demo Link: https://pr-1518-fossasia-susi-web-chat.surge.sh
> Added inline documentation for Table View and Map View code

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1526 
Changes: Remove theme changer from burger menu
Demo Link: https://pr-1526-fossasia-susi-web-chat.surge.sh
> Remove Theme from Drop-down menu #1526

- package.json
Fixes #1530 
Changes: Added missing fields in package.json
Demo Link: https://pr-1531-fossasia-susi-web-chat.surge.sh
NA
> Fixes #1530: Add missing fields in package.json

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1533 
Changes: Fixes body background color
Demo Link: https://pr-1533-fossasia-susi-web-chat.surge.sh
> Fix background color on custom theme #1533

- src/components/ChatApp/TopBar.react.js
Fixes #1544 
Changes: Removed the extra "%7D"
Demo Link: https://pr-1545-fossasia-susi-web-chat.surge.sh
> Fixes #1544: Removed extra `{` from URL

- src/components/ChatApp/Settings/PreviewThemeChat.css
- src/components/ChatApp/Settings/PreviewThemeChat.js
- src/components/ChatApp/Settings/ThemeChanger.js
Fixes #1547 
Earlier it was like, for small width devices: 
Changes: Changed some UI and made some fixes
Demo Link: https://pr-1547-fossasia-susi-web-chat.surge.sh
> UI Changes For Theme Changer #1547

- src/components/ChatApp/Settings/PreviewThemeChat.css
- src/components/Footer/Footer.css
Fixes #1551 
Changes: Susi logo in footer (https://chat.susi.ai/overview) of 'About' section is aligned properly .
Demo Link: https://pr-1566-fossasia-susi-web-chat.surge.sh
> Susi logo is aligned properly in footer 

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1569 
Changes: Fixed radio button misalignment on the Microphone and Chatapp tabs of the settings page.
Demo Link: https://pr-1571-fossasia-susi-web-chat.surge.sh
> Fixed radio button alignment for other settings tabs as well

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #1485 
Changes: [Made the loading icon work similar to susi skill CMS in forgot password form.]
Demo Link: https://pr-1556-fossasia-susi-web-chat.surge.sh
> Make forgot password form consistent with susi skill cms

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #1598 
Please refer issue for all details.
Demo Link: https://pr-1600-fossasia-susi-web-chat.surge.sh
> Replace undefined "status" with "textStatus"

- src/components/ChatApp/Settings/Settings.react.js
Fixes #1575 
Changes: The phone number field move down when screen width is reduced .
Demo Link: https://pr-1591-fossasia-susi-web-chat.surge.sh
> Fixed phone number input overlaps

- src/components/ChatApp/TopBar.css
Fixes #1565 
Changes: When the user has logged in then the search bar in top bar is aligned properly when screen is squeezed .
Demo Link: https://pr-1567-fossasia-susi-web-chat.surge.sh
> Search bar is aligned properly when screen is squeezed

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1602 
Changes: The problem was that when search changes from false to true, the messageComposer component re-renders which then triggers creation of a new message which happens in its componentDidMount function. When new message is created search is set from true to false, which again renders the messageComposer component and the message is created again. 
The messageComposer component re-renders when search state changes because of this line https://github.com/fossasia/chat.susi.ai/blob/master/src/components/ChatApp/MessageSection/MessageSection.react.js#L687
If we see the ternary statement on this line, the code for when the search is true and when its false is almost same and their is no need to re-render the messageComposer component whenever search state changes. Removing …
> fix search functionality when testing skills

- src/stores/MessageStore.js
Fixes #1456 
Changes: After giving a rating, it would not scroll to the latest chat automatically.
Demo Link: https://pr-1614-fossasia-susi-web-chat.surge.sh
> fixed scroll on feedback bug

- src/components/Overview/Overview.css
- src/components/Overview/Overview.react.js
Fixes #1553 
Changes:
- For 1081px - 1086px, the platform section is aligned properly
- Some code indentation
Demo Link: https://pr-1553-fossasia-susi-web-chat.surge.sh
> Alignment in platform section in overview #1553

- .gitignore
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes #1042 
Changes: The problem was that when strings starting with '<' or ending with '>' are passed through html-react-parser function it gives either an html element with no text inside it or an empty array. After handling these cases everything is working fine.
Demo Link: https://pr-1595-fossasia-susi-web-chat.surge.sh
> Handle angle brackets

- src/components/Auth/Login/Login.react.js
Fixes #1582 
Changes: 
* Changes invalid password message from `Enter a valid Password` to `Enter a valid password`
Demo Link: https://pr-1617-fossasia-susi-web-chat.surge.sh
> Change the invalid password message

- .github/CONTRIBUTING.md
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh
> Minor typo fix

- src/stores/UserPreferencesStore.js
Fixes #1619 
Changes: Fix complexity of UserPreferenceStore, reduced from 47 to below 20.
Demo Link: https://pr-1619-fossasia-susi-web-chat.surge.sh
> Fix complexity of UserPreferenceStore Fix#1619

- src/components/ChatApp/Settings/ThemeChanger.js
Fixes #1630 
Changes: Removed duplicate code from [ThemeChanger.js](https://github.com/fossasia/chat.susi.ai/blob/master/src/components/ChatApp/Settings/ThemeChanger.js) at line 93 and 108
> Remove duplicated code

- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes fossasia/susi_skill_cms#1635
Changes: In the pr #1595 i did not consider this case (where message can be made up of text and link). Now i have considered both cases. 
Demo Link: https://pr-1627-fossasia-susi-web-chat.surge.sh
> fix broken analyze text

- src/components/Auth/ChangePassword/ChangePassword.css
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/SignUp/SignUp.css
- src/components/Auth/SignUp/SignUp.react.js
Fixes #1639
Changes: While entering the password in signup modal the password strength is shown.
Demo Link: https://pr-1640-fossasia-susi-web-chat.surge.sh
> Added password strength on signup modal

- src/components/Auth/ChangePassword/ChangePassword.css
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.css
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #1558 
Changes: Fixed the forgot password link in Passwords tab of Settings page
Demo Link: https://pr-1615-fossasia-susi-web-chat.surge.sh
> forgot password fixed

- public/index.html
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
Fixes #1632
Changes:
**Performance**
- Make leaflet async as its non-critical css
**Accessibilty**
- Fix Meta Tags Used Properly
- Fix List `items <li> are not contained within <ul> or <ol> parent elements.`
Demo Link: https://pr-1632-fossasia-susi-web-chat.surge.sh
Previous Score:
New Score:
> Improve Lighthouse score #1632

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Blog/Blog.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
- src/components/ChatApp/ThreadListItem.react.js
- src/components/ChatApp/ThreadSection.react.js
Fixes #1650 
Changes: Uses arrow function across the app instead of explicit binding
Demo Link: https://pr-1650-fossasia-susi-web-chat.surge.sh
> Use arrow function(ES6) instead of bind #1650

- src/components/Devices/Devices.css
- src/components/Footer/Footer.css
Fixes #1672
Changes: I have removed the unused classes
Demo Link: https://pr-1673-fossasia-susi-web-chat.surge.sh
Let me know if somethings goes wrong @Akshat-Jain  @akshatnitd
> Unused classes leftDiv, rightDiv removed from Devices.css and Footer.css

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/SearchField.react.js
Fixes #1674 
Changes: Updated the code so that whenever the searchField is empty counter remains at zero.
Demo Link: https://pr-1675-fossasia-susi-web-chat.surge.sh
> Fixed minor problem in searchField

- src/components/NotFound/NotFound.react.js
Fixes #1693 
Changes: Following changes are made to make the component consistent with codebase:
- Ordered import statements
- constant declared before components to make it consistent
- Removed redundant closingStyleLogin
Demo Link: https://pr-1693-fossasia-susi-web-chat.surge.sh
> Code refactoring for NotFound.react.js#1693

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #1723 
Changes: Scrolltop button appears when list is scrolled down using scrolldown button
Demo Link: https://pr-1724-fossasia-susi-web-chat.surge.sh
GIF-
> Scrolltop button appears when list is scrolled down using scrolldown button

- src/components/MapContainer/MapContainer.react.js
Fixes #1718 
Changes: 
- ordered import statement
- moved style out of components
Demo Link: https://pr-1721-fossasia-susi-web-chat.surge.sh
> refactored MapContainer

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1708 
Changes: I have used the **withRouter** higher order component to pass the history props and thus using it to push **/logout** in the history stack.
**Before:**
**After:**
Demo Link: https://pr-1709-fossasia-susi-web-chat.surge.sh
> logout after password reset fixed

- src/utils/ChatMessageUtils.js
- src/utils/ChatWebAPIUtils.js
- src/utils/camelizeKeys.js
- src/utils/urls.js
Fixes #1683 
Changes: I have converted all the normal functions to arrow functions.
Demo Link: https://pr-1684-fossasia-susi-web-chat.surge.sh
> converting all normal functions to arrow functions in utils

- .eslintrc
- src/__tests__/components/Auth/Login/Login.js
- src/apis/index.js
- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/redux/actionTypes/index.js
- src/redux/actions/app.js
- src/redux/reducers/app.js
Fixes #1733 
Changes: 
* Integrate Redux into Login component
* Refactored component and removed unused code
Demo Link: https://pr-1734-fossasia-susi-web-chat.surge.sh
> Fixes #1733: Integrate Redux into Login component and refactor

- src/components/ChatApp/Settings/Settings.react.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Closed https://github.com/fossasia/chat.susi.ai/pull/1692 as its branch was old, having issues.
Fixes #1691 
Changes: Following changes are made to make the component consistent with codebase:
- Ordered import statements
- Arrow functions instead of normal functions
- constant declared before components to make it consistent
- Removed unwanted state (styling of raised buttons)
Demo Link: https://pr-1691-fossasia-susi-web-chat.surge.sh
> Refactor ShareOnSocialMedia.js

- public/index.html
- src/index.js
Fixes #1760 
Changes: 
* Integrate the Matzo web analytics
Demo Link: https://pr-1761-fossasia-susi-web-chat.surge.sh
> Fixes #1760: Integrate the Matzo web analytics

- src/__tests__/components/Auth/SignUp/SignUp.js
- src/apis/index.js
- src/components/Auth/SignUp/SignUp.react.js
- src/redux/actionTypes/index.js
- src/redux/actions/app.js
Fixes #1747 
Changes: I have integrated redux into signup component: 
Demo Link: https://pr-1748-fossasia-susi-web-chat.surge.sh
> Redux signup integration

- src/components/TableComplex/RemoveDeviceDialog.react.js
Initial workarounds for #1725
Made couple of workarounds within the ``` RemoveDeviceDialog.react.js ``` file removing JQuery from manipulating the DOM.
Demo link available at [surge](http://smoggy-duck.surge.sh/)
> Remove JQuery from DOM manipulation

- src/components/Translate/Translate.react.js
Fixes #1685 
Changes: I have fixed the language feature, and provided with a more efficient implementation. I have also made it so that in case a phrase is not available in the selected language, the system falls back to English for that particular phrase.
Demo Link: https://pr-1686-fossasia-susi-web-chat.surge.sh
> Language feature fixed

- src/__tests__/components/Auth/ForgotPassword/ForgotPassword.js
- src/apis/index.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/redux/actionTypes/index.js
- src/redux/actions/app.js
Fixes #1753 
Changes: The changes I made are:
Demo Link: https://pr-1755-fossasia-susi-web-chat.surge.sh
> Fixes #1753: Redux integration for Forgot password component

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/Settings/Settings.react.js
- src/utils/index.js
- src/utils/isEmail.js
- src/utils/isPhoneNumber.js
Fixes #1774 
Changes: 
*  Add utils for checking valid email and phpne number
Demo Link: https://pr-1775-fossasia-susi-web-chat.surge.sh
> Fixes #1774: Add utils for checking valid email and phone number

- src/components/Blog/Blog.react.js
- src/components/Devices/Devices.react.js
- src/components/Overview/Overview.react.js
- src/components/Privacy/Privacy.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
- src/utils/animateScroll.js
Fixes #1788, #1784 
Changes: 
1. Removed jQuery animation and added vanilla js animation
2. Fixed imports for Terms.react.js and Devices.react.js, and remove redundant document.style property
Demo Link: https://pr-1784-fossasia-susi-web-chat.surge.sh
> Fixes#1788, #1784, Remove jQuery scroll animation

- package.json
- src/components/Overview/Overview.css
- src/components/Overview/Overview.react.js
Fixes #1825
Changes: 
* Changed the line-height of watch text to match the height of the play SVG.
> Make play button and watch text vertically aligned.

- src/components/Blog/Blog.css
Fixes #1828 
Changes: 
- Changed the blog.css for solving the issue
- Tested the UI
Demo Link: https://pr-1829-fossasia-susi-web-chat.surge.sh
Before: 
The button cliping
The UI Shift in the blog Page
After:
Fixed button Clipping
Fixed UI shift
> Made the blog page more reseponsive

- src/components/ChatApp/Settings/ShareOnSocialMedia.js
Fixes #[1833](https://github.com/fossasia/chat.susi.ai/issues/1833#issue-390240446)
Changes:  Share on Google+ is now aligned
Before:
After:
> Share on Google+ is now aligned

- src/components/Auth/Login/Login.react.js
Fixes #1764 
Demo Link: https://pr-1766-fossasia-susi-web-chat.surge.sh
> Fixed #1764: Fixed login button activation

- src/components/Footer/Footer.css
Fixes #1754
Changes: Made footer consistent with other susi.ai sites
Demo Link: https://pr-1822-fossasia-susi-web-chat.surge.sh
> Footer consistent with other site

- src/components/Overview/Overview.react.js
Fixes #1843 
Demo Link: https://pr-1846-fossasia-susi-web-chat.surge.sh
> Fixes #1843: The map key error in OverView.js has been fixed

- src/apis/index.js
- src/components/Blog/Blog.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/Settings/PreviewThemeChat.js
- src/utils/helperFunctions.js
Fixes #1812 
Changes: 
Closed https://github.com/fossasia/chat.susi.ai/pull/1870 due to conflicts
1. Created **getBlogReponse**, **getSusiPreviewReply** using axios. **getSusiPreviewReply** is created for preview theme chat component.
2. Removed jQuery from MessageComposer, shifting urlParam to helper function.
Fixes this also:
Demo Link: https://pr-1878-1-fossasia-susi-web-chat.surge.sh
> Remove jQuery from PreviewThemeChat, Blog, MessageComposer #1812

- src/__tests__/components/ChatApp/MessageSection/MessageSection.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
- src/redux/reducers/messages.js
- src/redux/reducers/settings.js
- src/utils/invertColor.js
- src/utils/searchMessages.js
Fixes #1716
Changes: The changes I am working on are:
Demo Link: https://pr-1857-fossasia-susi-web-chat.surge.sh
> Redux integration and refactoring of MessageSection components

- src/__tests__/components/ChatApp/MessageComposer.js
- src/apis/index.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/VoiceRecognition.js
- src/utils/messageFilter.js
Fixes #1768
Changes: The changes I have made are as follows:
Here are few reasons for why I have made some drastic changes.
* I have created a new util file **messageFilter** that exports a function that is used to seave all the user messages from the list of messages currently available in store.
* As the messages are received via server call so there is a delay, thus I have introduced **componentsWillRecieve** props which when triggered for the first time by the incomming new messages from the server will check the **this.userMessageHistory** array's length. If this array is empty, we fill it using our util filter using the freshly recieved props. ( It is a key improvement that I have made that will ensure this performance heavy **filtering** task will never be done more than once. ). …
>  Fixes #1768: Integrate messageComposer with redux store  ( Fully functional )

- src/App.js
- src/__tests__/components/ProtectedRoutes/ProtectedRoutes.js
- src/components/ChatApp/Settings/Settings.react.js
- src/components/ProtectedRoute/index.js
Fixes #1876 
Changes: The changes I have made are: 
- Created a protected route and wrapped the setting component with it.
- Removed 404 page from settings component.
- Redirect unauthenticated users from protected routes to 404 page.
Demo Link: https://pr-1918-fossasia-susi-web-chat.surge.sh
> Fixes #1876: ProtectedRoute added, Settings component wrapped, tests added

- src/__tests__/components/ChatApp/MessageListItem/MessageListItem.js
- src/apis/index.js
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/ShareButton.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
- src/redux/actions/messages.js
Fixes #1713 
Changes: The changes I have made: 
- MessageListItems has now been connected to the redux store.
- The component now uses the help function to make API calls. ( $ dependency removed ).
- Removed redundant variables and re-structured code for easier readability.
- Fixed minor warning from ShareButton and style object mutation.
- Fixed minor code issues from share dialog. 
Note: While refactoring this component, we also found out that the api that fetches the default map data has been deprecated. One of the contributors will work on this. For now, I have just put some dummy values and updated the API call. The links below describe the issue in detail.
Note: There are also design flaws in the MessageListItem which cannot be addressed in a single PR and I'll probably work on it …
> MessageListItems.js connected to store and refactored

- src/components/Privacy/Privacy.react.js
Fixes #1936 
Changes: Fixed Grammatical errors on the privacy page. 
Demo Link: https://pr-1937-fossasia-susi-web-chat.surge.sh
> Fixed Grammatical errors on privacy page. 

- src/components/ChatApp/TopBar.react.js
Fixes #1873 
Changes: On clicking any element of popover it closes at that instant only.
Demo Link: https://pr-1927-fossasia-susi-web-chat.surge.sh
> Drop-down now closes instantly after clicking on its elements.

- src/App.js
- src/components/Auth/Login/Login.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #1942 
Changes: The changes I have made in this PR are:
Demo Link: https://pr-1944-fossasia-susi-web-chat.surge.sh
> Fixes #1942: Signup/ Login/ Forgotpassword popup fixed, StaticAppBar code simplified

- src/components/Auth/Login/Login.react.js
Fixes #1946 
Demo Link: https://pr-1949-fossasia-susi-web-chat.surge.sh
> Fixes #1946: User now always redirected to chat when he successfully logs in

- src/components/ChatApp/MessageListItem/helperFunctions.react.js
Fixes #1975 
Changes: The changes that I have made are:
Demo Link: https://pr-1980-fossasia-susi-web-chat.surge.sh
> Fixes #1975: ValidateDOM nesting error fixed

- src/components/Auth/ChangePassword/ChangePassword.react.js
Fixes #1970 
Changes: Fix UI in settings in change password when in dark theme
Demo Link: https://pr-1971-fossasia-susi-web-chat.surge.sh
> Fix UI in settings in change password when in dark theme

- src/components/Blog/Blog.css
Fixes #2014 
Changes: Fixed position of arrows in mobile screen and "Left arrow".
Demo Link: https://pr-2016-fossasia-susi-web-chat.surge.sh
> Fixed arrows in mobile screen.

- src/components/Auth/SignUp/SignUp.react.js
Fixes #1945 
Demo Link: https://pr-2005-fossasia-susi-web-chat.surge.sh
> Fixes #1945: User now notified if emailID is already taken

- src/components/Terms/Terms.react.js
Fixes #2013 
Changes: Fixed grammatical errors on the term page.
Demo Link: https://pr-2015-fossasia-susi-web-chat.surge.sh
> Fixed grammatical errors on Term page

- src/components/Auth/Login/Login.css
Fixes #2025
Changes: 
Added the underline feature when we hover on the "forgot password" and "sign up for susi".
Demo Link: https://pr-2026-fossasia-susi-web-chat.surge.sh
> added underline feature when we hover on it

- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
Fixes #2037 
Changes: In the speech demonstration example, SUSI now replies with 'Hi!, I am SUSI' instead of the word "undefined"
Demo Link: https://pr-2038-fossasia-susi-web-chat.surge.sh
> Fixes #2037: Added the message "Hi i am SUSI" to SUSI voice demonstration

- src/apis/index.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes #2006
Demo Link: https://pr-2031-fossasia-susi-web-chat.surge.sh
Screenshot:
> Fixes #2006: User now notified in real time if an email ID is already taken

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #1992 
Changes: Added 'email not found' based on statusCode
Demo Link: https://pr-1993-1-fossasia-susi-web-chat.surge.sh
> Fix Forget Password On Unsuccessful attempt #1992

- .github/PULL_REQUEST_TEMPLATE
Fixes #2021
Changes: Added description for Screenshots and made minor changes.
> Modified PR Template

- src/components/Auth/Login/Login.css
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Aligns Password placeholder..
Fixes #1989
Changes: Aligns placeholder for password.
> Solves #1989 : Aligns placeholder for password and Login button

- src/components/Blog/Blog.react.js
Fixes #2051 
Changes: Added a back to top button on the blog page at the bottom-right for quickly scrolling to the top
Demo Link: https://pr-2052-fossasia-susi-web-chat.surge.sh
> Add scroll to top button

- src/redux/actions/ui.js
- src/redux/reducers/ui.js
Fixes  #2058
Changes: The changes I have made are as follows:
Demo Link: https://pr-2059-fossasia-susi-web-chat.surge.sh
> ui reducer and actions misplacement fixed

- src/components/ChatApp/MessageSection/DialogSection.js
- src/components/ChatApp/Settings/ShareOnSocialMedia.js
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
Fixes #1922 
Changes: A share to LinkedIn button is added apart from already existing share on Facebook and Twitter.
Demo Link: https://pr-2048-fossasia-susi-web-chat.surge.sh
> Fixes #1922: Adds a LinkedIn share button

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #1996 
Changes: make delete account UI consistent with accounts.susi.ai
Demo Link: https://pr-2050-fossasia-susi-web-chat.surge.sh
> settings:modify delete account UI

- src/components/Team/constants.js
Fixes N/A
Changes: Fix jogendra's github and added blog link in **Team page**
Demo Link: https://pr-2073-fossasia-susi-web-chat.surge.sh
Screenshots of the change: N/A
> Fix jogendra's github and blog address

- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #2061, #2065 
Changes: 
- Fix setState warning
- Remove jQuery dependency for DOM manipulation
Demo Link: https://pr-2066-1-fossasia-susi-web-chat.surge.sh
> Fix setState warning#2061,remove jQuery#2065 in StaticAppBar

- src/components/Auth/Login/Login.react.js
Fixes #2045 
Changes: Login button becomes active only when 6 characters are added.
Demo Link: https://pr-2046-fossasia-susi-web-chat.surge.sh
> Fixed login button disabled issue. #2045

- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes #1986 
Changes: space added between the eye symbol and password textfield in login page
Demo Link: https://pr-2018-fossasia-susi-web-chat.surge.sh
> space added between the eye symbol and password textfield in login page

- src/apis/index.js
- src/components/ChatApp/Settings/Settings.react.js
Fixes #2086
Changes: Changed ajax call to promise based.
Demo Link: https://pr-2089-fossasia-susi-web-chat.surge.sh
> Use axios for calling API's in Settings

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/Settings/MobileTab.react.js
- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/TextToSpeechSettings.react.js
- src/utils/isMobileView.js
Fixes #2086 
Changes: Added margin to save button in mobile view. And made "play demonstration" button left align in mobile view.
Demo Link: https://pr-2087-fossasia-susi-web-chat.surge.sh
> Fix UI in Settings in mobile view

- src/index.js
- src/utils/helperFunctions.js
Fixes #2092 
Changes: Disables logging in production mode
Demo Link: https://pr-2093-1-fossasia-susi-web-chat.surge.sh
> Disable logging in production mode#2092

- src/components/ChatApp/MessageSection/MessageSection.react.js
When you will click on go to the top button or go to the bottom button, you will see it goes to the top abruptly. Which looks very bad and do not give the feeling of the scroll. I made it to the smooth scroll.
Demo Link: https://pr-2099-fossasia-susi-web-chat.surge.sh
Fixes #2097
> smooth scrolling

- src/components/Blog/Blog.css
- src/components/Blog/Blog.react.js
Fixes #2069 
Changes: -
1. Migrated Blog.react.js to a newer material UI version
2. Used style components and reused it for UI.
Demo Link: https://pr-2094-1-fossasia-susi-web-chat.surge.sh
> Migrate Blog to @material-ui/core

- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #2107 
Changes: Add Link component to ListItem.
Demo Link: https://pr-2111-fossasia-susi-web-chat.surge.sh
> Fix Sidebar(Overview,Devices,etc.) in Mobile View

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/redux/reducers/app.js
Fixes #2108, #2118
Changes: 
- Submit on Enter key in Login, SignUp, ForgotPassword
- Add Autofocus 
- Fix tour dialog popup #2118
Demo Link: https://pr-2119-1-fossasia-susi-web-chat.surge.sh
> Submit on enter key in Login, SignUp, ForgotPassword, add Autofocus #2108, tour#2118

- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/Settings/Settings.react.js
Fixes #2120 
Changes: 
- Migrated Left menu tab, dropdown to material UI
- Use a dynamic way of creating repeatable menu items.
With this, material UI for chat susi is completed.
Demo Link: https://pr-2120-1-fossasia-susi-web-chat.surge.sh
> Migrate Settings Left Menu Tab To Newer Material#2120

- public/index.html
- src/App.js
- src/__tests__/Admin/Admin.js
- src/__tests__/Admin/ListSkills/ListSkills.js
- src/__tests__/Admin/ListUser/ListUser.js
- src/__tests__/Admin/SystemLogs/SystemLogs.js
- src/__tests__/Admin/SystemSettings/SystemSettings.js
- src/__tests__/components/shared/Alert.js
- src/__tests__/components/shared/Lozenge.js
- src/components/Admin/Admin.css
- src/components/Admin/Admin.js
- src/components/Admin/AdminTab/AdminTab.js
- src/components/Admin/ListSkills/ListSkills.css
- src/components/Admin/ListSkills/ListSkills.js
- src/components/Admin/ListUser/ListUser.css
- src/components/Admin/ListUser/ListUser.js
- src/components/Admin/SystemLogs/SystemLogs.js
- src/components/Admin/SystemSettings/SystemSettings.js
- src/components/ChatApp/Settings/DevicesTab.react.js
- src/components/ChatApp/Settings/Settings.css
- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/shared/Alert.js
- src/components/shared/Lozenge.js
Fixes #2141
Changes: Migrate Admin from Skills CMS to Chat
Demo Link: https://pr-2142-fossasia-susi-web-chat.surge.sh
> Migrate Admin from Skills CMS to Chat #2141

- src/apis/index.js
- src/components/Admin/Admin.js
- src/components/Admin/SystemSettings/SystemSettings.js
Fixes #2156 
Changes: Added option to delete and create API keys in admin panel in system settings
Demo Link: https://pr-2167-fossasia-susi-web-chat.surge.sh
> Add Option to delete and create API keys in admin panel

- src/App.js
- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
Fixes #2161 
Changes: Change overview to home and chat to /chat route
Demo Link: https://pr-2168-fossasia-susi-web-chat.surge.sh
> Change overview to home and chat to /chat route

- src/App.js
- src/components/Admin/Admin.js
- src/components/Blog/Blog.react.js
- src/components/Contact/Contact.react.js
- src/components/Devices/Devices.react.js
- src/components/Footer/Footer.css
- src/components/Footer/Footer.react.js
- src/components/Overview/Overview.react.js
- src/components/Privacy/Privacy.react.js
- src/components/Settings/Settings.react.js
- src/components/Support/Support.react.js
- src/components/Team/Team.react.js
- src/components/Terms/Terms.react.js
- src/components/cms/BotBuilder/BotBuilder.js
- src/components/cms/BotBuilder/BotBuilderWrap.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillHistory/SkillHistory.js
- src/components/cms/SkillPage/SkillListing.js
- src/components/cms/SkillRollBack/SkillRollBack.js
- src/components/cms/SkillVersion/SkillVersion.js
Fixes #2158
Changes: Reuse Footer, StaticAppBar
Demo Link: https://pr-2159-fossasia-susi-web-chat.surge.sh
> Create AppShell layout, Reuse Footer, StaticAppBar #2158

- src/components/Auth/Logout.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/redux/reducers/app.js
Fixes #2160
Changes: Get userName from settings store
Demo Link: https://pr-2173-fossasia-susi-web-chat.surge.sh
> Get userName from settings store in StaticAppBar, TopAppBar #2160

- package.json
- src/App.js
- src/components/Button/ToTopButton.react.js
- src/components/ChatApp/TopBar.react.js
- src/components/Settings/Settings.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillCreator/SkillViews/TreeView.js
- src/components/cms/SkillVersion/SkillVersion.js
Fixes #2171, #2170
Changes:
1. Fix Priority of styled-components in Material UI
2. Upgrade React to: `16.8.6`, Material UI Version to `4.0.2`
3. Remove `&&` class bumps used earlier
4. Integrate styled component in ToTopButton.
Demo Link: https://pr-2172-fossasia-susi-web-chat.surge.sh
> Prioritize styled-components #2171, upgrade react, material#2170

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Settings/MobileTab.react.js
- src/components/Settings/TextToSpeechSettings.react.js
- src/components/cms/SkillCreator/SkillCreator.js
Fixes #2202, #1669 
Changes: 
- Remove isMobileView
- Integrate styled-components, CSS fix, cleanup
Demo Link: https://pr-2203-fossasia-susi-web-chat.surge.sh
> Remove isMobileView #2202, Integrate styled-components, css fix, cleanup #1669

- src/App.js
- src/components/cms/BrowseSkill/SkillStyle.js
- src/components/cms/CountryWiseSkillUsageCard/CountryWiseSkillUsageCard.css
- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillPage/SkillListing.css
- src/components/cms/SkillPage/SkillListing.js
- src/components/cms/SkillRating/SkillRatingCard.css
- src/components/cms/SkillRating/SkillRatingCard.js
- src/components/cms/SkillUsageCard/SkillUsageCard.js
Fixes #2200 
Changes: Fixed footer  being displayed in middle of the page
Demo Link: https://pr-2201-fossasia-susi-web-chat.surge.sh
> Fix Footer being displayed in middle of the page and skill listing page in mobile view

- src/components/Settings/Settings.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/cms/BrowseSkill/SkillStyle.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillPage/SkillListing.js
Fixes #2216, #2221
Changes:
- Fixed Scroll on top using a newer approach.
- Fix Popover menu, not close on the Dashboard click
Demo Link: https://pr-2222-fossasia-susi-web-chat.surge.sh
> Fix staticAppBar hide on scroll 

- src/components/Admin/Admin.js
- src/components/Admin/ListSkills/ListSkills.js
- src/components/Admin/ListUser/ListUser.js
- src/components/Admin/SystemLogs/SystemLogs.js
- src/components/Admin/SystemSettings/SystemSettings.js
Fixes #2196 
Changes: Left ListUser as data is not loading.
Demo Link: https://pr-2209-fossasia-susi-web-chat.surge.sh
> Integrate styled components admin

- src/App.js
- src/MUItheme.js
- src/__tests__/components/Auth/DeleteAccount/DeleteAccount.js
- src/__tests__/components/Auth/DeleteAccount/DeleteAccountModal.js
- src/apis/index.js
- src/components/Auth/DeleteAccount/DeleteAccount.react.js
- src/components/Auth/DeleteAccount/DeleteAccountModal.react.js
- src/components/Dialog/DialogSection.react.js
- src/components/Footer/Footer.react.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/SettingsTabWrapper.js
- src/components/shared/Container.js
- src/utils/urls.js
Fixes #2204,#2205,#2206,#2207
Changes: 
- Fix Footer Links
- Add missing links to staticAppBar
- Fix overview link, Shift CHAT_URL to newer URL
- Add Delete Account Modal
- Added Danger Zone
Screenshots
Demo Link: https://pr-2208-fossasia-susi-web-chat.surge.sh
> Bug fixes due to migration, Danger Zone, Delete Account

- src/components/cms/AuthorSkills/AuthorSkills.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillPage/SkillListing.js
Fixes #2215 
Changes:
If description is not provided or is `<description>` the text "No description provided will be show".
Similarly for terms and privacy will be shown on valid links.
Before by default author name was not shown, now by default the username will be shown as author name.
Demo Link: https://pr-2229-fossasia-susi-web-chat.surge.sh
> Fix issues on user created skills page

- package.json
Fixes #2239 
- Increase memory for surge build
Demo Link: https://pr-2241-fossasia-susi-web-chat.surge.sh
> Fixes #2239: Increase memory for surge build

- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/BrowseSkill/SkillStyle.js
- src/components/cms/BrowseSkill/custom.css
- src/utils/isMobileView.js
Fixes #2148 
Changes: Fix Category wise display of cards in mobile view
Demo Link: https://pr-2151-fossasia-susi-web-chat.surge.sh
> Fix Category wise display of cards in mobile view

- src/components/Settings/AccountTab.react.js
- src/components/Settings/Avatar.js
Fixes #2214 
Changes: Remove the need to click on cross to Upload Photo.
Make the process similar to github for upload photo.
Demo Link: https://pr-2230-fossasia-susi-web-chat.surge.sh
> Remove the need to click on cross to Upload Photo

- docs/Skill_Tutorial.md
- src/App.js
- src/components/ChatApp/TopBar.react.js
- src/components/Contact/Contact.css
- src/components/Overview/Overview.css
- src/components/StaticAppBar/StaticAppBar.react.js
- src/components/Support/Support.css
- src/components/Team/Team.css
- src/components/Terms/Terms.css
- src/components/cms/Dashboard/Dashboard.css
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/Dashboard/MyAnalytics.js
- src/components/cms/Dashboard/MyRatings.js
- src/components/cms/Dashboard/MySkills.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillUsageCard/SkillUsageCard.js
- src/components/shared/Link.js
- src/components/shared/PieChartContainer.js
- src/utils/urls.js
Fixes #2231, #2219, #2233
Changes: 
Demo Link: https://pr-2232-fossasia-susi-web-chat.surge.sh
> Skill Usage PieChart in Dashboard#2231, CSS Cleanup#2219, Dialog Transition #2233

- src/components/Dialog/DialogSection.react.js
Fixes #2248
Changes:
- Allow parent component to pass props to Dialog being rendered
Demo Link: https://pr-2250-fossasia-susi-web-chat.surge.sh
> Fixes #2248: Allow parent component to pass props to Dialog being rendered

- src/components/Settings/AccountTab.react.js
- src/components/Settings/SettingStyles.js
- src/components/Settings/Settings.react.js
- src/components/Settings/SettingsTabWrapper.js
- src/redux/reducers/settings.js
#2219 
Changes: 
- Make settings page responsive and resolve CSS bugs
Demo Link: https://pr-2245-fossasia-susi-web-chat.surge.sh
> Make settings page responsive and resolve CSS bugs

- src/App.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/Settings.css
Fixes #2252 
Changes: Removed footer from skillcreator and botbuilder pages. Also fixed select timezone bug in settings.
Demo Link: https://pr-2258-fossasia-susi-web-chat.surge.sh
> Fix footer appearance and select timezone bug in settings

- src/App.js
- src/apis/index.js
- src/components/Auth/VerifyAccount/VerifyAccount.js
Fixes #2266 
Changes: 
- Add Verify Account component for email verification
Demo Link: https://pr-2268-fossasia-susi-web-chat.surge.sh
> Fixes #2266: Add Verify Account component for email verification

- src/App.js
- src/components/ChatApp/TopBar.react.js
- src/components/CookiePolicy/CookiePolicy.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/redux/reducers/app.js
Fixes #2257, #2259
Changes: 
Demo Link: https://pr-2260-fossasia-susi-web-chat.surge.sh
> Fix Cookies policy,  Remove IconButton on User not logged in App Bar

- src/components/Support/Support.react.js
Fixes #2278 
Changes: Fixed sign up in support page.
Demo Link: https://pr-2286-fossasia-susi-web-chat.surge.sh
> Fix Signup in Support

- src/components/ChatApp/TopBar.react.js
- src/components/Settings/AccountTab.react.js
- src/components/StaticAppBar/StaticAppBar.react.js
- src/redux/reducers/app.js
- src/utils/getAvatarProps.js
Fixes #2284
Changes: Used different avatar size for topBar, Accounts settings.
Demo Link: https://pr-2291-fossasia-susi-web-chat.surge.sh
> Use thumbnail param for StaticAppBar, TopAppBar for avatar#2284

- package.json
Fixes #2309 
Changes: Fix Travis
Demo Link: https://pr-2310-fossasia-susi-web-chat.surge.sh
> Fix Travis Fail Error #2309

- src/components/Admin/Admin.css
- src/components/Admin/Admin.js
- src/components/Admin/SystemLogs/SystemLogs.js
- src/components/Admin/SystemSettings/SystemSettings.js
- src/components/shared/Alert.js
Fixes #2210  and part of #2219 
Changes: Improved the UI of system settings and logs in mobile view.
Demo Link: https://pr-2236-fossasia-susi-web-chat.surge.sh
> Fix System log and settings in Admin

- src/components/Settings/TextToSpeechSettings.react.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillRollBack/SkillRollBack.js
Fixes #2330, #2326 
Changes:
1. Fixed The Speech Output Language doesn't show the options if the user switches tabs and comes back to Speech Tab
2. After a skill is created, the skill creator redirects to newly skill created page.
Demo Link: https://pr-2331-fossasia-susi-web-chat.surge.sh
> Fix Speech Output Language Settings, redirect on create skill

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #2304 
Changes:
- Make changes to fix feedback to SUSI message reply
Demo Link: https://pr-2335-fossasia-susi-web-chat.surge.sh
> Fixes #2304: Make changes to fix feedback to SUSI message reply

- src/redux/reducers/skills.js
Fixes #2191
Changes: Enable checkbox Reviewed Skills by default
Demo Link: https://pr-2321-fossasia-susi-web-chat.surge.sh
> Enable checkbox Reviewed Skills by default

- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillPage/SkillListing.css
- src/components/cms/SkillPage/SkillListing.js
- src/components/cms/SkillRating/SkillRatingCard.js
- src/components/cms/SkillUsageCard/SkillUsageCard.js
Fixes #2280 
Changes: 
- Fixed mobile view in skills description.
- Removed scrolling
- Changed SVG of the edit icon
Demo Link: https://pr-2287-fossasia-susi-web-chat.surge.sh
> CSS Fixes in skill description

- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/SkillCardGrid/SkillCardGrid.js
- src/components/cms/SkillCardList/SkillCardList.js
- src/components/cms/SkillCardScrollList/SkillCard.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillHistory/SkillHistory.js
- src/components/cms/SkillRollBack/SkillRollBack.js
- src/components/cms/SkillVersion/SkillVersion.js
Fixes #2289, #2288
Demo Link: https://pr-2302-fossasia-susi-web-chat.surge.sh
Changes:
> Fix Notification and Skill Description Bug

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/Dialog/Tour.js
- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.react.js
- src/components/Overview/Overview.react.js
- src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.css
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
Fixes #2265 
Changes: Added title for every iframe tag (Removed warning after `npm start`) also removed warnings related to jsx-a11y/anchor-is-valid
Demo Link: https://pr-2273-fossasia-susi-web-chat.surge.sh
> Removed warnings from the console

- src/components/Auth/Login/Login.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2290 
Changes: Now there is no error if one searches something and clicks on the down arrow for one complete iteration.
Demo Link: https://pr-2316-fossasia-susi-web-chat.surge.sh
> Fix search in chat

- src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/Logout.react.js
- src/utils/helperFunctions.js
Fixes #2267 
Changes:
- Correct cookie domain logic based on production/demo link
Demo Link: https://pr-2349-fossasia-susi-web-chat.surge.sh
> Fixes #2267: Correct cookie domain logic based on production/demo link

- src/__tests__/components/shared/CircularLoader.js
- src/components/Admin/Admin.js
- src/components/Admin/AdminTab/AdminTab.js
- src/components/Admin/SystemLogs/SystemLogs.js
- src/components/Auth/VerifyAccount/VerifyAccount.js
- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/Settings/Settings.react.js
- src/components/cms/AuthorSkills/AuthorSkills.js
- src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/Dashboard/MyAnalytics.js
- src/components/cms/Dashboard/MyRatings.js
- src/components/cms/Dashboard/MySkills.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillCreator/SkillViews/ConversationView.js
- src/components/cms/SkillCreator/SkillViews/TreeView.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillHistory/SkillHistory.js
- src/components/cms/SkillPage/SkillListing.css
- src/components/cms/SkillPage/SkillListing.js
- src/components/cms/SkillRollBack/SkillRollBack.js
- src/components/cms/SkillVersion/SkillVersion.js
- src/components/shared/Alert.js
- src/components/shared/CircularLoader.js
Fixes #2261 
Changes: Create a common loader component
Demo Link: https://pr-2352-fossasia-susi-web-chat.surge.sh
> Create Common Loader Component #2261

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/Settings.react.js
Fixes #2342  
Changes: Removed white space and fixed mobile view in accounts and password tab
Demo Link: https://pr-2346-fossasia-susi-web-chat.surge.sh
> remove white space and mobile view

- src/App.js
- src/components/cms/BotBuilder/BotBuilder.js
- src/components/cms/BotBuilder/BotBuilderWrap.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/SkillCreator/SkillCreator.js
Fixes #2367 
Changes:
- Open login dialog on clicking Create when logged out
Demo Link: https://pr-2369-fossasia-susi-web-chat.surge.sh
> Fixes #2367: Open login dialog on clicking Create when logged out

- src/App.js
- src/__tests__/components/SkillHistory/SkillHistory.js
- src/components/Admin/SystemSettings/UpdateSystemSettingsDialog.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/SkillCreator/SkillCreator.js
- src/components/cms/SkillHistory/SkillHistory.js
- src/components/cms/SkillRollBack/SkillRollBack.js
- src/components/cms/SkillVersion/SkillVersion.js
- src/components/shared/CustomSnackbar.js
- src/redux/reducers/ui.js
Fixes #2305 
Changes: Migrated from antd notification to material ui snackbar.
Demo Link: https://pr-2344-fossasia-susi-web-chat.surge.sh
> Migrate to material ui notification

- src/components/Settings/DevicesTab/MapContainer.js
- src/components/Settings/DevicesTab/index.js
Fixes #2375 
Changes: 
- Show SUSI devices on a map in Devices settings tab
Demo Link: https://pr-2376-fossasia-susi-web-chat.surge.sh
> Fixes #2375: Show SUSI devices on a map in Devices settings tab

- src/components/cms/Dashboard/MySkills.js
- src/components/cms/SkillCreator/SkillCreator.js
Fixes #2340 
Changes: 
Fixed image upload on edit.
Removed addition of author_email and protected on each update.
Fixed link on image of skills in my skills in dashboard.  
Demo Link: https://pr-2380-fossasia-susi-web-chat.surge.sh
> Fix Bug in edit skill

- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Fixes #2372 
Changes: Integrate SoundCloud support in Chat App.
Demo Link: https://pr-2379-fossasia-susi-web-chat.surge.sh
> Implement SoundCloud support

- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.react.js
Fixes #2348
Changes: 
- Fix logo on "Page not Found"
- Fix alignment
Demo Link: https://pr-2389-fossasia-susi-web-chat.surge.sh
Desktop View:
Mobile View:
> Fix logo on Page not Found #2348

- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/Dashboard/MyAnalytics.js
- src/components/cms/Dashboard/MySkills.js
- src/components/shared/PieChartContainer.js
- src/components/shared/Typography.js
Fixes #2329 
Changes: Fixed Dashboard in mobile view
Demo Link: https://pr-2337-fossasia-susi-web-chat.surge.sh
> Fix Dashboard in mobile view

- src/components/ChatApp/ChatApp.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/TopBar.react.js
Fixes #2390 
Changes: Successfully directs to settings when clicked on the username
Demo Link: https://pr-2395-fossasia-susi-web-chat.surge.sh
> Fixes: #2390 Direct to settings in chat bug resolved

- src/components/ChatApp/ChatApp.css
- src/components/ChatApp/ChatApp.react.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/ChatApp/MessageListItem/helperFunctions.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/Dialog/Share.js
- src/components/NavigationBar/index.js
Fixes #2396, #2359 
Changes: 
- Fix color of the skills page
Note: I tried using other ways to achieve body color, didn't find any other cleaner way of doing it.
- Add styled components, remove redundant styles
Note: I will be combining TopAppBar with StaticAppBar next PR, so left some CSS styles.
Demo Link: https://pr-2397-fossasia-susi-web-chat.surge.sh
Screenshot:
> Fix color of skills page, cleanup

- src/components/Footer/Footer.react.js
- src/components/NavigationBar/TopMenu.js
- src/components/NavigationBar/constants.js
- src/components/NavigationBar/index.js
Fixes #2423 
Changes: Simplify and enhance menus #2423
- Make Menu clickable
Demo Link: https://pr-2428-fossasia-susi-web-chat.surge.sh
> Simplify and enhance menus #2423

- src/components/ChatApp/MessageListItem/ShareButton.js
- src/components/Dialog/Share.js
Fixes #2417 
Changes: Clicking on share icon in chat opens up a share message dialog.
Demo Link: https://pr-2444-fossasia-susi-web-chat.surge.sh
> Open up share dialog on clicking on share in Chat

- src/components/Settings/DevicesTab/MapContainer.js
Fixes #2418 
Changes: Made changes in MapContainer.js
Fixed map in devices in mobile view.
Demo Link: https://pr-2426-fossasia-susi-web-chat.surge.sh
> Fix map in devices in mobile view

- .env
- .gitignore
- src/utils/urls.js
Fixes #2437 
Changes: 
- Use .env for API_URL
Demo Link: https://pr-2438-fossasia-susi-web-chat.surge.sh
> Fixes #2437: Use .env for API_URL

- src/components/cms/BotBuilder/Preview/Preview.css
- src/components/cms/BotBuilder/Preview/Preview.js
- src/components/cms/SkillCreator/SkillWizard.css
- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2212
Changes: Fixed mobile view for create skill
Demo Link: https://pr-2405-fossasia-susi-web-chat.surge.sh
> Fixed mobile view for create skill

- src/App.js
- src/components/Footer/Footer.react.js
- src/components/NavigationBar/index.js
- src/components/Terms/Terms.react.js
- src/components/shared/ColorPicker.js
Fixes #2434 
Fixes #2435 
Fixes #2440 
Changes: 
-  Make footer stick to bottom
- Correct footer links
Demo Link: https://pr-2436-fossasia-susi-web-chat.surge.sh
> Fixes #2434: Make footer stick to bottom

- src/components/NavigationBar/TopMenu.js
Fixes #2444
Changes: 
- Fix Chat in TopMenu not highlighting on active
- Refactored code
Demo Link: https://pr-2445-fossasia-susi-web-chat.surge.sh
> Fix Chat underline link #2444

- src/App.js
- src/components/NavigationBar/constants.js
- src/components/NavigationBar/index.js
Fixes part of #2424 
Changes: Made `/` as browse skills page. And `/about/overview` for About.
Demo Link: https://pr-2450-fossasia-susi-web-chat.surge.sh
> Change Start Page

- src/components/NavigationBar/constants.js
- src/components/cms/BrowseSkill/BrowseSkill.js
Fixes #2483 
Changes: Fixed incorrect links as mentioned in the issue.
Demo Link: https://pr-2484-fossasia-susi-web-chat.surge.sh
> Fix incorrect links

- src/App.js
- src/components/cms/BotBuilder/BotBuilderWrap.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/Dashboard/MySkills.js
- src/components/cms/Dashboard/index.js
- src/components/cms/SkillCreator/SkillCreator.js
Fixes #2439 
Changes:
- Create Tabs on Dashboard page
Demo Link: https://pr-2486-fossasia-susi-web-chat.surge.sh
> Fixes #2439: Create Tabs on Dashboard page

- src/components/Admin/Admin.js
- src/components/Admin/AdminStyles.js
- src/components/Admin/ListSkills/ListSkills.js
Fixes #2456 
Changes: Deleted heading in admin area
Left aligned the tabs
Demo Link: https://pr-2467-fossasia-susi-web-chat.surge.sh
> Delete Heading in Admin area

- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2441 
Changes: Now user can select group, language and name in any order.
Demo Link: https://pr-2480-fossasia-susi-web-chat.surge.sh
> Fix bug in Skill Info in Skill Wizard

- src/components/shared/CircularLoader.js
Fixes #2492 
Changes: 
Fixed the bug.
Changes can be checked on skill specific pages and admin.
Demo Link: https://pr-2493-fossasia-susi-web-chat.surge.sh
> Fix Circular Loader Bug

- src/components/About/Support/index.js
Fixes #2487 
Changes: When clicked on signup, modal opens up.
Demo Link: https://pr-2497-fossasia-susi-web-chat.surge.sh
> Sign up modal opens now

- src/apis/index.js
- src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BotBuilder/Preview/Preview.js
- src/components/cms/SkillCreator/SkillWizard.js
- src/redux/actions/create.js
- src/redux/reducers/create.js
Fixes #2422, #2468, #2470
Changes:
- Bugs in upload image
- Fix preview height
- Persist data while changing tabs in Botbuilder, SkillCreator
- Set Preview Icon image from Botbuilder
Demo Link: https://pr-2464-fossasia-susi-web-chat.surge.sh
Try uploading images and switch tabs, the data persists now.
Screenshot for #2470
> Fix BotBuilder Bugs #2422

- src/components/Settings/Avatar.js
Fixes #2481
Changes: 
- Removed `choose file` button from settings->account
- fixed the bug when avatar image is removed
Demo Link: https://pr-2503-fossasia-susi-web-chat.surge.sh
> Removed unnecessary choose button and fixed the bug when avatar image is removed

- src/App.js
- src/components/Footer/Footer.react.js
- src/components/cms/BotBuilder/BotWizard.js
Fixes #2449
Changes: Fixed footer at the bottom of the page
Demo Link: https://pr-2466-fossasia-susi-web-chat.surge.sh
> Fixed footer

- src/components/NotFound/NotFound.react.js
- src/components/shared/ProtectedRoute.js
- src/redux/reducers/create.js
Fixes #2512
Changes: Show "You need to login.." for existing pages instead of 404
Demo Link: https://pr-2517-fossasia-susi-web-chat.surge.sh
> Show Login on protected routes#2512

- src/apis/index.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/BrowseSkill/SearchBar.js
- src/redux/reducers/create.js
- src/redux/reducers/skills.js
Fixes #2473
Changes: Enhance search functionality
Demo Link: https://pr-2478-fossasia-susi-web-chat.surge.sh
> Enhance search functionality #2473

- deploy.sh
Fixes #2495 
Changes: 
- Add "local pages" for smart devices to build script
Couldn't test it, it can be done only when this PR is merged
> Fixes #2495: Add "local pages" for smart devices to build script

- src/components/NavigationBar/Styles.js
- src/components/NavigationBar/index.js
- src/redux/reducers/app.js
Fixes #2513
Changes: Fix Alignment of Icon and name in nav bar
Demo Link: https://pr-2515-fossasia-susi-web-chat.surge.sh
> Fix Icon and name not portrayed as expected #2513

- src/components/NavigationBar/constants.js
- src/components/NavigationBar/index.js
Fixes #2505
Changes: 
- added a Dashboard (linking to /dashboard) icon
- deleted the "skills" dropdown menu
Demo Link: https://pr-2521-fossasia-susi-web-chat.surge.sh
> Add Dashboard icon and deleted dropdown of the skills

- src/components/Admin/SystemSettings/Slideshow/Dialog.js
- src/components/Admin/SystemSettings/Slideshow/Dropzone.js
- src/components/Admin/SystemSettings/Slideshow/constants.js
- src/components/Admin/SystemSettings/Slideshow/index.js
- src/components/NavigationBar/Popper.js
- src/components/NavigationBar/index.js
- src/components/cms/SkillSlideshow/index.js
Fixes #2545, #2542, #2544 
Changes: 
Demo Link: https://pr-2549-fossasia-susi-web-chat.surge.sh
> Fix TopMenu Popper#2545, Slider#2542, #2544

- src/components/ChatApp/ChatApp.css
- src/components/CookiePolicy/CookiePolicy.react.js
Fixes #2548 
Changes: 
- Show Cookies/Terns on top of chat icon
Demo Link: https://pr-2552-fossasia-susi-web-chat.surge.sh
> Fixes #2548: Show Cookies/Terns on top of chat icon

- src/components/NavigationBar/index.js
- src/components/cms/BrowseSkill/BrowseSkill.js
Fixes #2556
Changes: Fix SearchBar language search bug
On changing route, the language select menu doesn't open, fixed it
Demo Link: https://pr-2556-fossasia-susi-web-chat.surge.sh
> Fix SearchBar language search bug#2556

- package.json
- public/index.html
- src/components/Admin/ListSkills/ListSkills.js
- src/components/Admin/ListUser/index.js
- src/components/Admin/SystemSettings/ConfigKeys/index.js
- src/components/Admin/SystemSettings/Slideshow/index.js
- src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js
- src/components/cms/SkillCreator/SkillViews/CodeView.js
- src/components/shared/TableActionStyles.js
- src/index.css
Fixes #2553
Changes: Remove antd package, migrate related components to material ui
Demo Link: https://pr-2577-fossasia-susi-web-chat.surge.sh
> Remove antd package, migrate related components to material

- src/App.js
- src/__tests__/components/MyDevices/DevicesTable.js
- src/__tests__/components/MyDevices/MapContainer.js
- src/__tests__/components/MyDevices/RemoveDeviceDialog.js
- src/__tests__/components/MyDevices/index.js
- src/components/Dialog/DialogSection.react.js
- src/components/Settings/Settings.react.js
- src/components/cms/Dashboard/index.js
- src/components/cms/MyDevices/DeviceWizard.js
- src/components/cms/MyDevices/DevicesTable.js
- src/components/cms/MyDevices/MapContainer.js
- src/components/cms/MyDevices/RemoveDeviceDialog.js
- src/components/cms/MyDevices/index.js
Fixes #2488 
Changes: 
Clicking on the view icon i settings devices redirect to `/mydevices/:macId`
Demo Link: https://pr-2500-fossasia-susi-web-chat.surge.sh
> Device Page: Add configuration options

- src/components/About/Devices/index.js
- src/constants/about.js
- src/utils/urls.js
Fixes #2587
Changes: 
- Refactor devices page and remove code redundancy
Demo Link: https://pr-2588-fossasia-susi-web-chat.surge.sh
> Fixes #2587: Refactor devices page and remove redundancy

- .env
- deploy.sh
- src/App.js
- src/components/cms/MyDevices/DeviceWizard.js
- src/components/cms/MyDevices/DevicesTable.js
- src/components/shared/AppBanner.js
- src/redux/reducers/app.js
Fixes #2496 
Fixes #2495 
Changes: 
- Show banner in local env
- Disable device configuration settings in local env and overlay the section
Demo Link: https://pr-2594-fossasia-susi-web-chat.surge.sh
> Fixes #2496: Show banner and disable device settings in local env

- deploy.sh
Fixes #2603 
Changes: 
- Put all build files into root in local-pages
Demo Link: https://pr-2604-fossasia-susi-web-chat.surge.sh
> Fixes #2603: Put all build files into root in local-pages

- deploy.sh
- src/components/cms/SkillCreator/SkillWizard.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillPage/SkillListing.js
Fixes #2617 
Fixes #2619 
Changes:
- Fix delete skill bug from skill details & edit page
- Fix broken Skill feedback page
Demo Link: https://pr-2620-fossasia-susi-web-chat.surge.sh
> Fixes #2617: Fix delete skill bug from skill details & edit page

- src/components/Footer/Footer.react.js
Fixes #2613
Changes: Increased the gray area to show the menu above the chat icon when scrolling it up.
Demo Link: https://pr-2615-fossasia-susi-web-chat.surge.sh
> Footer: Increase gray area

- src/components/cms/SkillSlideshow/index.css
Fixes #2608 
Changes: Next arrow is not overlapping on chat window
Demo Link: https://pr-2629-fossasia-susi-web-chat.surge.sh
> Next arrow is behind chat window

- src/components/NavigationBar/SearchBar.js
- src/components/NavigationBar/index.js
Fixes #2494 
Changes: Added a onClose function.
Demo Link: https://pr-2632-fossasia-susi-web-chat.surge.sh
> Fix Cancel search in search bar

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2614
Changes: Stop currently playing audio from skill using 'stop', 'pause'  or 'abort' voice command
Demo Link: https://pr-2633-fossasia-susi-web-chat.surge.sh
> Option to stop a skill playing audio #2614

- src/components/Settings/ShareOnSocialMedia.js
- src/redux/reducers/app.js
- src/redux/reducers/settings.js
Fixes #2643 
Changes:
- Remove server url hardcoding
Demo Link: https://pr-2650-fossasia-susi-web-chat.surge.sh
> Fixes #2643: Remove server url hardcoding

- src/App.js
Fixes #2657
Changes: Fix Start page refreshes on login, opening chat, etc.
Demo Link: https://pr-2658-fossasia-susi-web-chat.surge.sh
> Fix Components Remounting due to HOC #2657

- src/components/Settings/Settings.react.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillCardList/SkillCardList.js
- src/redux/reducers/skills.js
- src/utils/appendQueryString.js
Fixes #2646, #2645, #2648, #2651
Changes: 
Demo Link: https://pr-2647-fossasia-susi-web-chat.surge.sh
Fixed this:
> Fix list highlight on Customer Review Select #2646

- src/__tests__/components/shared/Recaptcha.js
- src/apis/index.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/Avatar.js
- src/components/shared/Recaptcha.js
- src/utils/isPassword.js
- src/utils/isUserName.js
Fixes #2546, #2638, #2555, #2640
Changes: 
Demo Link: https://pr-2639-fossasia-susi-web-chat.surge.sh
> Fix validation #2546,#2555, searchbar bug #2640, avatar UI #2638

- src/components/Admin/AdminTab/AdminTab.js
- src/components/cms/SkillPage/SkillListing.js
- src/components/cms/SkillRating/SkillRatingCard.js
- src/components/cms/SkillUsageCard/SkillUsageCard.js
- src/components/shared/charts/LineChart.js
- src/index.css
- src/utils/mergeByDate.js
- src/utils/sortByDate.js
Fixes #2550, #2635
Changes:
Demo Link: https://pr-2666-fossasia-susi-web-chat.surge.sh
> Show user, Statistics in Admin #2550, Skill Example #2635

- src/components/ChatApp/MessageComposer.react.js
- src/components/Settings/ShareOnSocialMedia.js
- src/components/cms/BotBuilder/BotBuilder.js
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/Dashboard/MySkills.js
- src/components/cms/MyDevices/DevicesTable.js
- src/components/cms/MyDevices/index.js
- src/components/cms/SkillCreator/SkillCreator.js
Fixes #2578, #2682
Changes: Added loader in My Bots and made the specified changes in the issue.
Added missing heading `Share about SUSI` and increased the message composer font-size to 1rem.
Demo Link: https://pr-2683-fossasia-susi-web-chat.surge.sh
> Improve Dashboard Conformity across pages and fix minor bugs

- src/__tests__/Admin/ListSkills/SkillTable.js
- src/components/Admin/ListSkills/ListSkills.js
- src/components/Admin/ListSkills/SkillTable.js
Fixes #2477 
Changes: Add a system skills tab under skills
Demo Link: https://pr-2681-fossasia-susi-web-chat.surge.sh
> Add System Skills tab under Skill in Admin

- src/__tests__/Admin/ListDevices/index.js
- src/apis/index.js
- src/components/Admin/Admin.js
- src/components/Admin/ListDevices/constants.js
- src/components/Admin/ListDevices/index.js
Fixes #2611 
Changes: Added devices tab in admin
Demo Link: https://pr-2669-fossasia-susi-web-chat.surge.sh
> Admin: Add Devices Tab

- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/ChatApp/SearchField.react.js
Fixes #2686, #2700 
Changes: 
- Changed design of chat preview
- Change Message search Design
Demo Link: https://pr-2699-fossasia-susi-web-chat.surge.sh
> Enhance preview chat #1

- package.json
- src/components/NavigationBar/index.js
- src/components/cms/BrowseSkill/BrowseSkill.js
Fixes #2712 
Demo Link: https://pr-2717-fossasia-susi-web-chat.surge.sh
> Enhance Create Dropdown on start page and navigation bar

- src/__tests__/components/MyDevices/AddDeviceDialog.js
- src/components/cms/MyDevices/AddDeviceDialog.js
- src/components/cms/MyDevices/index.js
- src/components/shared/Dialog/index.js
Fixes #2716 
Demo Link: https://pr-2719-fossasia-susi-web-chat.surge.sh
> My Devices: Add button Add Device and Pop up Info about steps to do this

- src/App.js
- src/components/cms/MyDevices/DeviceWizard.js
- src/components/cms/MyDevices/DevicesTable.js
- src/components/cms/MyDevices/index.js
- src/components/cms/MyDevices/styles.js
Fixes #2715 
Demo Link: https://pr-2725-fossasia-susi-web-chat.surge.sh
> My Devices: Add submenu for added devices

- src/components/NavigationBar/index.js
Fixes #2718
Changes:
Fix chat icon in topbar
Demo Link: https://pr-2727-fossasia-susi-web-chat.surge.sh
> Fix chat icon in topbar

- src/apis/index.js
- src/components/Admin/ListUser/DevicePanel/index.js
- src/components/Admin/ListUser/index.js
Fixes #2692 
Changes: 
Demo Link: https://pr-2701-fossasia-susi-web-chat.surge.sh
> Fix Users Tab in Admin

- src/__tests__/Admin/ListBots/index.js
- src/apis/index.js
- src/components/Admin/Admin.js
- src/components/Admin/ListBots/constants.js
- src/components/Admin/ListBots/index.js
- src/components/cms/BotBuilder/BotBuilder.js
- src/components/shared/Dialog/index.js
Fixes #2551 
Changes: Add Bots tab in admin
Demo Link: https://pr-2654-fossasia-susi-web-chat.surge.sh
> Admin: Bots

- src/components/Auth/SignUp/SignUp.react.js
Fixes #2707 
Changes: Now the Signup button is enable when all the details are verified correctly.
Demo Link: https://pr-2731-fossasia-susi-web-chat.surge.sh
> Fix signup into SUSI.AI issue

- src/components/shared/Dialog/index.js
Fixes #2736 
Changes: Fixed rendering of full screen chat.
Demo Link: https://pr-2737-fossasia-susi-web-chat.surge.sh
> Fix Chat box: Full Screen Mode no longer working

- package.json
- src/components/Settings/MobileTab.react.js
Fixes #2641
Changes: Created styled Component in MobileTab.react.js
Demo Link: https://pr-2713-fossasia-susi-web-chat.surge.sh
> styled Component in MobileTab.react.js

- package.json
Fixes Travis
Demo Link: https://pr-2753-fossasia-susi-web-chat.surge.sh
> Fix travis

- package.json
> Revert "Fix travis"

- src/App.js
- src/components/cms/BotBuilder/BotBuilderPages/Configure.js
- src/components/cms/BotBuilder/BotBuilderPages/Deploy.js
- src/components/cms/BotBuilder/BotBuilderPages/Design.js
- src/components/cms/BotBuilder/BotBuilderPages/DesignViews/CodeView.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BotBuilder/Preview/Preview.js
- src/components/cms/BotBuilder/styles.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillCreator/SkillViews/CodeView.js
- src/components/cms/SkillCreator/SkillViews/ConversationView.js
- src/components/cms/SkillCreator/SkillViews/TreeView.js
- src/components/cms/SkillCreator/SkillWizard.js
- src/redux/reducers/create.js
- src/utils/avatars.js
Fixes #2738, #2644, #2694, #2755
Changes: 
Demo Link: https://pr-2740-fossasia-susi-web-chat.surge.sh
> SkillCreator, Botbuilder general improvements

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2711 
Changes: 
Demo Link: https://pr-2723-fossasia-susi-web-chat.surge.sh
> Fix chatApp bugs #2711

- src/components/cms/BotBuilder/BotBuilderPages/Configure.js
- src/components/cms/BotBuilder/BotBuilderPages/Deploy.js
- src/components/cms/BotBuilder/BotBuilderPages/Design.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BotBuilder/Preview/Preview.js
- src/components/cms/BotBuilder/styles.js
- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2761 #2760 
Changes: Made the changes as specified in the issue.
Demo Link: https://pr-2762-fossasia-susi-web-chat.surge.sh
<------>
<---------->
> Fix bugs in skill creator and bot builder

- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2741 
Changes: Create Skills and Bot: Minimized space needed for dropdown choices and improved (i) icon
Demo Link: https://pr-2765-fossasia-susi-web-chat.surge.sh
> Create Skills and Bot: Minimized space needed for dropdown choices and improved (i) icon

- src/components/Admin/ListUser/DevicePanel/EditDeviceDialog.js
- src/components/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
- src/components/Admin/Settings/Slideshow/Dialog.js
- src/components/Settings/ThemeChanger.js
- src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js
- src/components/cms/SkillCardScrollList/SkillCardScrollList.js
- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillPage/ReportSkillDialog.js
Fixes #2774 
Changes: 
- Use Outlined Input across app
Demo Link: https://pr-2775-fossasia-susi-web-chat.surge.sh
> Use Outlined Input across app

- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2718
Changes: Fix bug: On opening chat, it does not go to the end of the conversation
Demo Link: https://pr-2778-fossasia-susi-web-chat.surge.sh
> Fix scoll to bottom on opening of chat#2718

- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2763 
Changes: Used popover for it.
Demo Link: https://pr-2770-fossasia-susi-web-chat.surge.sh
> Create Skill: Add Slider button to offer choice of Open Source / Public Skill vs. Private Skill

- src/App.js
- src/components/ChatApp/MessageListItem/MessageBubbleStyle.js
- src/components/cms/BotBuilder/Preview/Preview.js
- src/redux/reducers/create.js
Fixes #2751 
Demo Link: https://pr-2773-fossasia-susi-web-chat.surge.sh
> Create Skills/Bots Page: Make Preview Consistent with Standard Chat Box

- src/components/cms/BrowseSkill/BrowseSkill.js
Fixes #2530
Changes: Fixes scroll bar for creating skill in browse skill
Demo Link: https://pr-2781-fossasia-susi-web-chat.surge.sh
> Fix create skill menu on left in browseSkill #2530

- src/components/Admin/Settings/ConfigKeys/index.js
- src/components/Admin/Settings/ConfigKeys/table-config.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/utils/isPassword.js
Fixes #2612
Changes: Standardise config keys table in the admin panel
Demo Link: https://pr-2782-fossasia-susi-web-chat.surge.sh
> Standardise config keys table #2612

- src/components/Admin/Messages/message-config.js
- src/components/Admin/Settings/ConfigKeys/index.js
- src/components/Admin/Settings/Mail/index.js
- src/components/Admin/Settings/Slideshow/index.js
Fixes #2710
Changes: Fix Email Form alignment
Demo Link: https://pr-2791-fossasia-susi-web-chat.surge.sh
> Fix Email Form #2710

- src/components/Admin/Settings/ConfigKeys/index.js
- src/index.js
Fixes #2801
Changes: Fix API Keys response types
Demo Link: https://pr-2802-fossasia-susi-web-chat.surge.sh
> Fix API Keys response types #2801

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2779
Changes: Added Space between message bubble and text area
Demo Link: https://pr-2799-fossasia-susi-web-chat.surge.sh
> Added Space between message bubble and text area

- src/App.js
- src/__tests__/components/Auth/ResetPassword/ResetPassword.js
- src/apis/index.js
- src/components/Auth/ResetPassword/index.js
- src/components/shared/Dialog/index.js
Fixes #2800
Changes: Add reset password component
Demo Link: https://pr-2803-fossasia-susi-web-chat.surge.sh
> Add reset password component #2800

- src/App.js
- src/apis/index.js
- src/components/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
- src/components/Admin/Settings/ConfigKeys/index.js
- src/components/Settings/Settings.react.js
- src/components/Settings/UserKeysTab.js
- src/redux/reducers/app.js
Fixes #2693 
Changes:
- Implement feature for User API keys
Demo Link: https://pr-2812-fossasia-susi-web-chat.surge.sh
> Fixes #2693: Implement feature for User API keys

- src/apis/index.js
- src/utils/urls.js
Fixes #2807, #2806
Changes: 
- Fix endpoint URLs for the control page #2806
- Fix setup endpoint while setting up device(reboot)
Demo Link: https://pr-2813-fossasia-susi-web-chat.surge.sh
> Fix submit reboot endpoint #2807, control server #2806

- src/utils/helperFunctions.js
Fixes #2814 
Changes: 
- Fix the bug in isProduction util
Demo Link: https://pr-2815-fossasia-susi-web-chat.surge.sh
> Fixes #2814: Fix the bug in isProduction util

- src/redux/reducers/create.js
Fixes #2816 
Changes: [Add here what changes were made in this pull request and if possible provide links showcasing the changes.]
Fix broken Skill edit page
Demo Link: https://pr-2817-fossasia-susi-web-chat.surge.sh
> Fix broken Skill edit page

- src/__tests__/components/Admin/ListDevices/EditDeviceDialog.js
- src/components/Admin/ListDevices/EditDeviceDialog.js
- src/components/Admin/ListDevices/constants.js
- src/components/Admin/ListDevices/index.js
- src/components/cms/MyDevices/DeviceWizard.js
- src/components/cms/MyDevices/MapContainer.js
- src/components/cms/MyDevices/index.js
- src/components/shared/Dialog/index.js
Fixes #2708, Fixes #2714 
Changes: Added device date, location map on hover and edit device.
Demo Link: https://pr-2805-fossasia-susi-web-chat.surge.sh
> Admin Dashboard: Device Tab - Add Device Added Date, Location Map and Edit Device

- src/components/About/Blog/index.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/Settings/Settings.react.js
- src/redux/reducers/app.js
> Revert "Add functionality to enable/disable captcha #2796"

- src/components/Admin/ListSkills/constants.js
- src/components/Admin/ListUser/constants.js
- src/components/Admin/Messages/index.js
- src/components/Admin/Messages/message-config.js
- src/components/Admin/Messages/table-config.js
- src/components/Admin/Settings/Slideshow/constants.js
- src/components/shared/Dialog/index.js
- src/components/shared/table.js
Fixes #2785, #2835
Changes: 
1. Admin: Enhance message table
2. Remove all table scrolls in admin panel
Demo Link: https://pr-2795-fossasia-susi-web-chat.surge.sh
> Admin: Enhance message table, remove all table scroll

- src/redux/reducers/app.js
Fixes #2836
Changes: Currently all external API related requests are failing like blog section. Fix it
Demo Link: https://pr-2837-fossasia-susi-web-chat.surge.sh
> Fix api keys failing bug #2836

- src/App.js
- src/components/Admin/Admin.js
Fixes #2786
Changes:
- Removed footer from admin section
- Added some padding
Demo Link: https://pr-2827-fossasia-susi-web-chat.surge.sh
> Fixed bottom page of the admin

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #2840 
Changes: Clicking on "Play Shakira" on the top slider show the videos entirely
Demo Link: https://pr-2844-fossasia-susi-web-chat.surge.sh
> Video show up entirely

- docs/ARCHITECTURE.md
- docs/RECOMMENDED_READING.md
Fixes #2845 
Changes: Fixed Directory in Architecture Documentation and Heading in Recommended Documentation 
> Directory in Architecture Documentation and Heading in Recommended Documentation [Fixes #2845]

- src/components/Admin/ListDevices/constants.js
- src/components/Admin/ListDevices/index.js
- src/components/shared/table.js
Fixes #2860
Changes: Remove devices tab table scroll
Demo Link: https://pr-2861-fossasia-susi-web-chat.surge.sh
> Fix devices tab table scroll

- src/components/Admin/ListDevices/constants.js
- src/components/Admin/ListDevices/index.js
- src/components/shared/table.js
> Revert "Fix devices tab table scroll"

- src/components/Admin/ListDevices/constants.js
- src/components/Admin/ListDevices/index.js
Fixes #2860
Changes: Multi-line break for devices table in admin
Demo Link: https://pr-2864-fossasia-susi-web-chat.surge.sh
> Fix devices tab table scroll #2860

- src/App.js
Fixes #2869
Changes: Fixed entry point due to a bug in https://github.com/fossasia/susi.ai/pull/2847
Demo Link: https://pr-2871-fossasia-susi-web-chat.surge.sh
> Fix entry point #2869

- deploy.sh
Fixes #2485 
Changes:
- Fix build for local-pages
Demo Link: https://pr-2872-fossasia-susi-web-chat.surge.sh
> Fix build for local-pages

- src/apis/index.js
- src/components/Admin/ListUser/constants.js
- src/components/Admin/ListUser/index.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/ChatAppTab.react.js
- src/components/Settings/MicrophoneTab.react.js
- src/components/Settings/MobileTab.react.js
- src/components/Settings/Settings.react.js
- src/components/Settings/SpeechTab.react.js
- src/components/Settings/ThemeChangeTab.react.js
- src/redux/reducers/settings.js
- src/utils/getAvatarProps.js
Fixes #2554 
Changes: Clicking on edit in users tab in admin redirects to settings page of user.
Demo Link: https://pr-2833-fossasia-susi-web-chat.surge.sh
> Admin: Provide more options to edit users

- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillCardList/SkillCardList.js
- src/redux/reducers/skill.js
- src/redux/reducers/skills.js
Fixes #2883 
Changes: Fixed error in loading of skills
Demo Link: https://pr-2884-fossasia-susi-web-chat.surge.sh
> Fix bug in loading of skills

- src/components/cms/SkillCreator/SkillWizard.js
Fixes #2888 
Changes: FIxed commit message
Demo Link: https://pr-2889-fossasia-susi-web-chat.surge.sh
> Fix Commit Message in Skill Wizard

- src/redux/reducers/app.js
Fixes #2879 
Demo Link: https://pr-2895-fossasia-susi-web-chat.surge.sh
> fix avatar bug

- docs/DEPLOY.md
Fixes #2901 
```$ yarn install -g surge``` is not a command , instead of ```$ yarn global add surge```  is command.
> Change in DEPLOY.md

- docs/PROJECT_INFORMATION.md
Fixes #2906
Changes: Fixed grammatical error in 'docs/PROJECT_INFORMATION.md'
> Improve Documentation #2906

- src/components/NavigationBar/index.js
Fixes #2691 
Changes: When all the languages are deselected it displays english as default language
Demo Link: https://pr-2921-fossasia-susi-web-chat.surge.sh
> Set english language selected by default

- package.json
- src/components/About/Blog/index.js
- src/components/About/Devices/index.js
- src/components/About/Overview/index.js
- src/components/About/Privacy/Privacy.react.js
- src/components/About/Team/index.js
- src/components/About/Terms/Terms.react.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillPage/SkillListing.js
- src/components/shared/ScrollTopButton.js
Fixes #2994 
Changes: 
1) Implemented a new "ScrollTopButton" component in the shared folder and added it to pages that have excessive amounts of vertical scrolling. 
Updated pages include - SkillListing, BrowseSkill, Blog, Devices, About, Privacy, Team, Terms.
2) Removed the previously used "ToTopButton" component used in the Blog and the Teams pages which was not styled properly (It was clashing with the Chat component as shown in the following image) and also didn't place properly when the browser was resized.
Demo Link: https://pr-2995-fossasia-susi-web-chat.surge.sh
> Fixes 2994 - Implementation of Scroll to top Floating Action Button

- src/components/cms/Dashboard/MyRatings.js
Fixes #2987
Changes: Added in the rating widget used in the SkillCard component, to the MyRatings component.
Demo Link: https://pr-2993-fossasia-susi-web-chat.surge.sh
> Fixes 2987 - Improved My Ratings sections

- src/components/NavigationBar/index.js
Fixes #2902
Changes:1) Fixed language selector in the navigation bar
Demo Link: https://pr-3010-fossasia-susi-web-chat.surge.sh
> Fixed language selector in navigation bar

- deploy.sh
Fixes #2896 
Changes: Changes made in the deploy.sh file
> fixed local pages build files

- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
Fixes #2808 
Changes:
**SkillFeedbackpage.js** 
- Added the skillratingcard component to the skillfeedback page.
- Removed the reference created to the feedback component to stop scrolling on page load.
Demo Link: https://pr-3029-fossasia-susi-web-chat.surge.sh
> Fixes #2808 - Adding rating to skill feedback page

- public/susi-chatbot.js
Changes: 
- Add chat bot script file to public folder
> Add chat bot script file to public folder

- src/components/NavigationBar/index.js
Fixes #3046
Changes: Gap adjusted between EN and drop down arrow
Demo Link: https://pr-3049-fossasia-susi-web-chat.surge.sh
> updated language select box in mobile view

- src/components/shared/Container.js
Fixes #3004 
Changes:  1) Fixed alignment in mobile view.
Demo Link: https://pr-3011-fossasia-susi-web-chat.surge.sh
> Alignment fixed in mobile view.

- src/components/cms/SkillVersion/SkillVersion.js
Fixes #2949 
Changes:
/src/components/cms/SkillVersion/SkillVersion.js: Placed the back button at top right corner.
Demo Link: https://pr-2950-fossasia-susi-web-chat.surge.sh
> fix for back button being hidden in skill version page

- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
Fixes #3001 
Changes: Made changes to fetch `previousFeedback` when user opens `editFeedback`
Demo Link: https://pr-3061-fossasia-susi-web-chat.surge.sh
> resolved edit feedback issue with feedbackPage

- src/components/shared/Dialog/index.js
Fixes #2947 
Changes: Added padding to dialog box.
Demo Link: https://pr-3071-fossasia-susi-web-chat.surge.sh
Before: 
After:
> Added padding in the dialog to fix the scroll bar issue

- src/components/Settings/TextToSpeechSettings.react.js
Fixes #3077
Error while compiling is removed. Proposed better matching.
> Compilation Error removed

- package.json
- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Fixes #3039 
Changes: 
1) When a youtube video is requested using the play command, a popout button will now appear underneath the video. If the user wants he/she can click on this popout button to view the video on a much larger popout.
2) This popout button is only available in larger screen sizes and is not available on smaller devices.
Demo Link: https://pr-3047-fossasia-susi-web-chat.surge.sh
Screenshots:
> Implements #3039 - Improved video player

- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Fixes #3026 
**Note:** _This PR is a follow up and implements the requested changes at https://github.com/fossasia/susi.ai/pull/3027  Unfortunately I had a change of PC's and I decided to start off with a new remote and a local repository, hence this new PR. Apologies for any inconvenience caused._
Changes: Handles map actions as requested in https://github.com/fossasia/susi.ai/pull/3027 
Demo Link: https://pr-3080-fossasia-susi-web-chat.surge.sh
> Fixed #3026 -  Handling map responses in chat

- package.json
- src/components/cms/Dashboard/MyRatings.js
- src/components/cms/Dashboard/MySkills.js
Fixes #2997
**Note:** _This PR is a follow up and implements the requested changes at https://github.com/fossasia/susi.ai/pull/3000 Unfortunately I had a change of PC's and I decided to start off with a new remote and a local repository, hence this new PR. Apologies for any inconvenience caused._
Changes:
1) Re implemented the tables using material-table package.
Demo Link: https://pr-3078-fossasia-susi-web-chat.surge.sh
> Fixes #2997 - Reimplemented tables using material-table

- src/components/NavigationBar/index.js
- src/redux/reducers/skills.js
- src/utils/localStorageService.js
Fixes #3074 
Changes: Have added a localStorageService which would protect the website from going blank when user has blocked localstorage. Moreover directly use of localStorage can cause the website to blank. Read more about it here -> https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/
Demo Link: https://pr-3084-fossasia-susi-web-chat.surge.sh
> fix(localStorage): added try catch to local storage

- src/components/Settings/ShareOnSocialMedia.js
fix to https://github.com/fossasia/susi.ai/issues/3019
> remove outline from share buttons

- src/components/Settings/ShareOnSocialMedia.js
- src/components/cms/Dashboard/Dashboard.js
- src/components/cms/Dashboard/MySkills.js
Fixes #3097 
Changes: Changed padding and added dynamic removal of first and last page button from pagination depending on the screen size
Demo Link: https://pr-3101-fossasia-susi-web-chat.surge.sh
- When screen width is above 500px
- When screen width is below 500px
> Scaling Optimization for Dashboard Page

- src/components/cms/SkillPage/SkillListing.js
Fixes #3100 
Changes: Now all the examples are shown instead of 'show more or less examples' buton
Demo Link: https://pr-3102-fossasia-susi-web-chat.surge.sh
> Now all example messages are shown in skill description

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #3110 
No errors  ✅
Following best practices 🚀
Passed all tests 😃
https://drive.google.com/file/d/1PKIrBgvkiDx8gS9TkKbjHvO-Q-SpOWHM/view
From above video, changes can bee seen in action.
> Add login link in Forgot Password Model

- src/components/cms/SkillCreator/SkillWizard.js
Fixes #3103 
Demo Link: https://pr-3105-fossasia-susi-web-chat.surge.sh
Screenshots of the change: [Add screenshots depicting the changes.
> add Edit Skill heading

- src/components/About/Overview/index.js
Fixes #3126 
Now the switching and styling works correctly 😄
Demo Link: https://pr-3132-fossasia-susi-web-chat.surge.sh
> Fixed the gif switching issue in About section

- src/components/Settings/AccountTab.react.js
Fixes #2980 - Fixing issues with the empty username field in Account tabcreenshots of the change: 
Demo Link: https://pr-3129-fossasia-susi-web-chat.surge.sh
> Fixes 2980 - Fixing issues with the empty username field in Account tab

- src/components/Settings/ShareOnSocialMedia.js
Fixes #3142
Demo Link: https://pr-3143-fossasia-susi-web-chat.surge.sh
> Added share to WhatsApp button in share menu

- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
Fixes #3140
Changes: 
function to get correct skill name has been utilized
Demo Link: https://pr-3141-fossasia-susi-web-chat.surge.sh
**Actual Behaviour**
**Expected Behaviour**
> Naming of skills in feedback Section fixed

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
- src/components/Auth/DeleteAccount/DeleteAccount.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/ResetPassword/index.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/MobileTab.react.js
Fixes #3150 
Changes:
used  disabled prop of frorm component( If true, the label, input and helper text should be displayed in a disabled state.)
Demo Link: https://pr-3153-fossasia-susi-web-chat.surge.sh
> Disabled input fields during Logging in process

- src/components/About/Contact/Contact.react.js
Fixes #3138
Changes: New fossasia address has been inserted as per  https://github.com/fossasia/labs.fossasia.org/issues/407
Demo Link: https://pr-3139-fossasia-susi-web-chat.surge.sh
> Added new fossasia address

- src/components/Settings/ShareOnSocialMedia.js
- src/components/shared/Dialog/dialogTypes/Share.js
Fixes #3169 
Changes: 
- Added WhatsApp web share button in `Share.js` as used in `ShareOnSocialMedia.js`
Demo Link: https://pr-3170-fossasia-susi-web-chat.surge.sh
**After Changes**
> Added whatsapp share button in share about susi.ai

- src/components/NavigationBar/index.js
Fixes #3112 
Demo Link: https://pr-3113-fossasia-susi-web-chat.surge.sh
> align shadow centered

- src/components/About/Blog/BlogLoader.js
- src/components/About/Blog/index.js
Fixes #3165
Changes: Added content Loader to Blog page too.
these are responsive with device
Demo Link: https://pr-3166-fossasia-susi-web-chat.surge.sh
> Added content Loader to blog Page

- src/apis/index.js
- src/components/About/Blog/index.js
Fixes #3154 #3179 
Changes: 
- Add navigation buttons.
- Render data using paginated ajax calls.
Demo Link: https://pr-3174-fossasia-susi-web-chat.surge.sh
> Load blog posts with paginated ajax calls

- src/components/shared/Dialog/dialogTypes/Share.js
Fixes #3172
Changes: Added share to telegram in dialog
Demo Link: https://pr-3173-fossasia-susi-web-chat.surge.sh
**Earlier**
**Now**
> added share to telegram in dialog

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #3114
Changes: Fixed smooth scrolling and disappearance of down button
Demo Link: https://pr-3190-fossasia-susi-web-chat.surge.sh
> fixed smooth scrolling and disappearance of down button

- README.md
Fixes #3167 
**Changes:**
Added local installation steps in README.md
> chore: Update README.md (Add Local Installation Steps)

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes #3196
Changes: modified login method to allow email in capital letters
Demo Link: https://pr-3197-fossasia-susi-web-chat.surge.sh
> Fixes #3196 : Modified Login

- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/SkillPage/SkillListing.js
Fixes #3232
Changes:
Removed unnecessary ScrollTopButton
Demo Link: https://pr-3231-fossasia-susi-web-chat.surge.sh
> Removed unnecessary ScrollTopButton

- src/__tests__/components/ChatApp/MessageListItem/VoicePlayer.js
- src/__tests__/components/ChatApp/VoiceRecognition.js
Fixes https://github.com/fossasia/susi.ai/pull/2078#issuecomment-490404368 https://github.com/fossasia/susi.ai/pull/2078#pullrequestreview-237023623
Changes:
Added tests for VoiceRecognition and VoicePlayer
Demo Link: https://pr-3241-fossasia-susi-web-chat.surge.sh
> Added tests for VoiceRecognition and VoicePlayer

- src/components/About/Blog/index.js
Fixes #3188
Changes: 
<ul>
<li>Fixed rendering of empty Blog page
</li>
<li>Also implemented mechanism for fetching next posts and using them efficiently 
</li>
</ul>
Demo Link :
https://pr-3237-fossasia-susi-web-chat.surge.sh/blog
> rendering of empty Blog page fixed

- src/components/Settings/AccountTab.react.js
Fixes #3235
Changes: 
Trimmed username before saving
Demo Link: 
https://pr-3236-fossasia-susi-web-chat.surge.sh
> Trim username before submitting

- src/__tests__/components/SkillFeedbackPage/EditFeedbackDialog.js
- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
Fixes #3256
Changes: 
Removed Unnecessary error messages
Fixed infinite loading while editing a feedback to an empty value
Disabled form while submission 
Demo Link: https://pr-3257-fossasia-susi-web-chat.surge.sh
> Fixed feedback form

- src/components/ChatApp/MessageSection/MessageSection.react.js
Fixes #3264
Changes: 
added date in chat
Demo Link: https://pr-3266-fossasia-susi-web-chat.surge.sh
> added date in chat

- src/components/Admin/ListUser/index.js
- src/components/ChatApp/MessageComposer.react.js
- src/components/ChatApp/MessageListItem/MessageBubbleStyle.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/NavigationBar/SearchBar.js
- src/components/Settings/PreviewThemeChat.js
- src/components/Settings/Settings.react.js
- src/components/cms/BotBuilder/Preview/Preview.js
- src/components/cms/BrowseSkill/skillLoader.js
- src/components/cms/SkillCreator/SkillWizard.js
- src/components/shared/CircleImage/index.js
- src/components/shared/ColorPickerComponent/index.js
Fixes #3239 
Changes: 
- Renamed css properties such as `backgroundColor` , `borderRadius` etc. to `backgroundcolor` , `borderradius` to avoid conflict of `styled-components`styles with react styles.
- Link to the issue: https://github.com/mui-org/material-ui/issues/13957
- Used `onCancelSearch` function prop to be used when `<CloseIcon/>` is clicked in `material-ui-search-bar`.
- Added `key` to the list in `skillloader.js`
Demo Link: https://pr-3248-fossasia-susi-web-chat.surge.sh
> Resolved browser console errors

- package.json
- src/components/cms/CountryWiseSkillUsageCard/CountryWiseSkillUsageCard.js
Fixes #3271
Changes: Added country flags in Country wise Usage of a skill
Demo Link: https://pr-3272-fossasia-susi-web-chat.surge.sh
> Fixes #3271 : Added country flag

- src/components/cms/BotBuilder/Preview/Preview.js
Fixes  https://github.com/fossasia/susi.ai/issues/3212
Changes: change message var after click send
Demo Link: https://pr-3287-fossasia-susi-web-chat.surge.sh
Screenshots of the change: in issue
> clear textbox

- src/components/Auth/Login/Login.react.js
Fixes #[Error message from password in login window removed #3277]
**Changes:**
Changes were made in Login.react.js . The conditional statement for checking length of password was removed from the code.
**Before**
**After**
> Error messsage while entering password fixed

- package.json
- src/components/Settings/AccountTab.react.js
- src/components/Settings/Avatar.js
- src/components/shared/Dialog/dialogTypes/CropDialog.js
- src/components/shared/Dialog/index.js
- src/utils/helperFunctions.js
Fixes #3269 
Changes: 
- Added crop image dialog to crop an avatar uploaded by the user.
Demo Link: https://pr-3274-fossasia-susi-web-chat.surge.sh
**new changes**
> Added crop image dialog to crop avatar

- src/components/ChatApp/MessageListItem/MessageBubbleStyle.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Fixes #3284
Changes: 
Addded Gif preview
Demo Link: https://pr-3294-fossasia-susi-web-chat.surge.sh
> Addded Gif preview

- src/components/About/Blog/index.js
- src/components/ChatApp/MessageSection/MessageSection.react.js
- src/components/Footer/Footer.react.js
- src/components/shared/CircleImage/index.js
- src/components/shared/charts/LineChart.js
Fixes #3292 
Changes: fixed Console errors
Demo Link: https://pr-3293-fossasia-susi-web-chat.surge.sh
> fixed Console errors

- package.json
- src/components/cms/BrowseSkill/BrowseSkill.js
Fixes #3008
Changes:  Sorting skill by Name(A-Z) fixed
Demo Link: https://pr-3295-fossasia-susi-web-chat.surge.sh
> Fixes #3008 : Sorting skill by Name(A-Z) fixed

- src/components/cms/SkillCardList/SkillCardList.js
- src/components/cms/SkillCreator/SkillWizard.js
Fixes #3303  #3306
Changes: 
Demo Link: https://pr-3307-fossasia-susi-web-chat.surge.sh
> Fixed minor bugs/Added enhancements

- src/components/Admin/ListDevices/index.js
Fixes #3314
Changes: replaced GoogleApiWrapper with HOC
Demo Link: https://pr-3313-fossasia-susi-web-chat.surge.sh
> replaced GoogleApiWrapper with HOC

- src/components/Admin/ListBots/index.js
- src/components/Admin/ListDevices/index.js
- src/components/Admin/ListSkills/ListSkills.js
- src/components/Admin/ListSkills/SkillTable.js
- src/components/Admin/ListUser/index.js
- src/components/Admin/Messages/index.js
- src/components/Admin/Settings/ConfigKeys/index.js
- src/components/Admin/Settings/Slideshow/index.js
Fixes #3316
Changes:
turned each action to a function 
Reference Link : https://github.com/mbrn/material-table/issues/657#issuecomment-515088181
Demo Link: https://pr-3317-fossasia-susi-web-chat.surge.sh
> fixed material tables

- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
- src/components/Auth/ForgotPassword/ForgotPassword.react.js
- src/components/Auth/Login/Login.react.js
- src/components/Auth/SignUp/SignUp.react.js
Fixes #3242
Changes: For the purpose of this pull request I have added the feature of trimming to various parts the website depending on when they become operational. I have added the trimming feature to only some of the times but in other cases due to security have not added them as in case of deleting the account or while resetting the password.
Demo Link: https://pr-3336-fossasia-susi-web-chat.surge.sh
@akshatnitd Sir please review.
> Feature to Trim Email added to SUSI.AI

- src/components/Settings/ShareOnSocialMedia.js
Fixes #3321 
Changes: Made the social profile icons responsive with the web page
Demo Link: https://pr-3323-fossasia-susi-web-chat.surge.sh
> Fixed the alignment of social profile icons

- src/components/NotFound/NotFound.react.js
Fixes #3308
Changes:
Improved NOt found page
Demo Link: https://pr-3325-fossasia-susi-web-chat.surge.sh/dsadsa
Earlier:
Now:
> Improved NOt found page

- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/BrowseSkill/skillLoader.js
Fixes #3315 
Changes: 
- Improved content-loader to show only when skills are searched.
Demo Link: https://pr-3318-fossasia-susi-web-chat.surge.sh
**After changes**
> Improved content-loaders for skill search

- src/components/Admin/ListDevices/EditDeviceDialog.js
- src/components/Admin/ListSkills/EditSkillDialog.js
- src/components/Admin/ListUser/DeleteDialog.js
- src/components/Admin/ListUser/DevicePanel/EditDeviceDialog.js
- src/components/Admin/ListUser/EditUserRoleDialog.js
- src/components/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
- src/components/Admin/Settings/Slideshow/Dialog.js
- src/components/Auth/ChangePassword/ChangePassword.react.js
- src/components/CookiePolicy/CookiePolicy.react.js
- src/components/Settings/AccountTab.react.js
- src/components/Settings/ChatAppTab.react.js
- src/components/Settings/MicrophoneTab.react.js
- src/components/Settings/MobileTab.react.js
- src/components/Settings/SpeechTab.react.js
- src/components/Settings/ThemeChangeTab.react.js
- src/components/Settings/ThemeChanger.js
- src/components/cms/BotBuilder/BotWizard.js
- src/components/cms/BrowseSkill/BrowseSkill.js
- src/components/cms/Dashboard/MySkills.js
- src/components/cms/SkillCreator/SkillWizard.js
- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillPage/ReportSkillDialog.js
- src/components/shared/Button.js
- src/components/shared/Dialog/dialogTypes/ConfirmDialog.js
- src/components/shared/Dialog/dialogTypes/CropDialog.js
- src/components/shared/Dialog/dialogTypes/StandardActionDialog.js
- src/components/shared/Dialog/dialogTypes/confirmDeleteWithInput.js
Fixes #3319 
Changes: 
- Used `Circular Progress` in Modals while loading.
- Set a common `Button` ui to all modals.
Demo Link: https://pr-3327-fossasia-susi-web-chat.surge.sh
> Added circular progress to various modals

- src/components/About/Blog/Blog.css
Fixes #3073 
Demo Link: https://pr-3322-fossasia-susi-web-chat.surge.sh
**BEFORE**
**AFTER**
> fix blog images witdh on small screens

- src/components/ChatApp/SearchField.react.js
Fixes #3345 
Changes: Date doesn't overlap search bar now
Demo Link: https://pr-3346-fossasia-susi-web-chat.surge.sh
> Date doesn't overlap searchbar now

- src/__tests__/components/Admin/Admin.js
- src/__tests__/components/Admin/ListBots/index.js
- src/__tests__/components/Admin/ListDevices/EditDeviceDialog.js
- src/__tests__/components/Admin/ListDevices/index.js
- src/__tests__/components/Admin/ListSkills/EditSkillDialog.js
- src/__tests__/components/Admin/ListSkills/ListSkills.js
- src/__tests__/components/Admin/ListSkills/ReportPanel.js
- src/__tests__/components/Admin/ListSkills/SkillTable.js
- src/__tests__/components/Admin/ListUser/DeleteDialog.js
- src/__tests__/components/Admin/ListUser/DevicePanel/EditDeviceDialog.js
- src/__tests__/components/Admin/ListUser/DevicePanel/index.js
- src/__tests__/components/Admin/ListUser/EditUserRoleDialog.js
- src/__tests__/components/Admin/ListUser/index.js
- src/__tests__/components/Admin/Messages/RecaptchaOptions.js
- src/__tests__/components/Admin/Messages/index.js
- src/__tests__/components/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
- src/__tests__/components/Admin/Settings/ConfigKeys/index.js
- src/__tests__/components/Admin/Settings/Mail/index.js
- src/__tests__/components/Admin/Settings/ReCaptcha/index.js
- src/__tests__/components/Admin/Settings/Slideshow/Dialog.js
- src/__tests__/components/Admin/Settings/Slideshow/Dropzone.js
- src/__tests__/components/Admin/Settings/Slideshow/index.js
- src/__tests__/components/Admin/Settings/index.js
- src/__tests__/components/Admin/SystemLogs/SystemLogs.js
- src/__tests__/components/Auth/DeleteAccount/ConfirmDeleteAccount.js
- src/__tests__/components/Auth/DeleteAccount/DeleteAccount.js
- src/__tests__/components/Dialog/DialogSection.js
- src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
- src/components/cms/SkillSlideshow/index.js
Fixes #3354
Changes: 
fixed all tests 
NOw:
https://travis-ci.org/fossasia/susi.ai/jobs/640424390?utm_medium=notification&utm_source=github_status
before:
https://travis-ci.org/fossasia/susi.ai/jobs/639162158?utm_medium=notification&utm_source=github_status
>  fixed all tests

- src/components/ChatApp/MessageListItem/MessageListItem.react.js
- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
- src/components/Settings/ThemeChanger.js
Fixes #3360
Changes: 
Demo Link: https://pr-3361-fossasia-susi-web-chat.surge.sh
> fixed reset to Light theme

- src/components/NavigationBar/SearchBar.js
- src/components/NavigationBar/index.js
Fixes #3048 
Changes: Navigation bar is responsive for all media devices.
Demo Link: https://pr-3352-fossasia-susi-web-chat.surge.sh
> Fixed issues with navigation bar

- src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #33474
Changes: Back to login option is not visible anymore.
Demo Link: https://pr-3348-fossasia-susi-web-chat.surge.sh
> Fixed forgot password modal

- public/index.html
- webpack.config.js
- webpack.config.production.js
Fixes build failure
Demo Link: https://pr-3391-fossasia-susi-web-chat.surge.sh
> Fix build failure

- public/index.html
- webpack.config.js
- webpack.config.production.js
Fixes #3286 
Changes: Copied files that were not being copied earlier by webpack-production-config. Webpack dev server and build both are in working state.
Demo Link: https://pr-3395-fossasia-susi-web-chat.surge.sh
> chore(): changed webpack configs

- src/components/shared/Container.js
Fixes #3392 Fixes Date Break in mobile view.
Changes: 
Changed the width from 100% to auto.
Before Fix: 
After Fix:
> Fixes Issue #3392. Fixes Date breaking to new line in mobile view.

- src/index.css
Fixes #3332
Changes: Fixed the overlapping issue of subheadings in the left menu on scroll.
Demo Link: https://pr-3405-fossasia-susi-web-chat.surge.sh
> Fixed the overlapping of subheadings

- src/components/Admin/ListSkills/SkillTable.js
- src/components/NavigationBar/TopMenu.js
- src/components/cms/BotBuilder/BotBuilderPages/Configure.js
- src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/CodeView.js
- src/components/cms/BotBuilder/BotBuilderPages/Deploy.js
- src/components/cms/BotBuilder/BotBuilderPages/Design.js
- src/components/cms/BotBuilder/BotBuilderPages/DesignViews/CodeView.js
- src/components/cms/SkillCardGrid/SkillCardGrid.js
- src/components/smart-speaker/Configure.js
Fixes #3406 
Changes: 
- Turned class-based stateless components into functional components for faster component rendering.
Demo Link: https://pr-3408-fossasia-susi-web-chat.surge.sh
> Turned many state-less class-based components into functional

- public/susi-chatbot.js
Fixes #3404
Changes:  eliminated the use of jQuery
Demo Link: https://pr-3407-fossasia-susi-web-chat.surge.sh
> fixes #3404 : refactored susi-chatbot.js to ES6 and eliminate the use of jQuery

- src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Fixes #3415
Changes:
removed blank message
Demo Link: https://pr-3146-fossasia-susi-web-chat.surge.sh
> fixes #3415  : removed blank message

- src/components/ChatApp/MessageListItem/Feedback.react.js
Fixes #3441
Changes: fixed error in chat with susi 
Demo Link: https://pr-3440-fossasia-susi-web-chat.surge.sh
> fixed error in chat with susi

- src/components/Admin/ListSkills/EditSkillDialog.js
- src/components/Auth/ResetPassword/index.js
- src/components/Auth/SignUp/SignUp.react.js
- src/components/ChatApp/MessageListItem/Feedback.react.js
- src/components/ChatApp/MessageListItem/VoicePlayer.js
- src/components/Settings/TextToSpeechSettings.react.js
- src/components/cms/BotBuilder/BotWizard.js
Fixes #3439
Changes: Used class field declarations for javascript
Demo Link: https://pr-3443-fossasia-susi-web-chat.surge.sh
> Used class field declarations for javascript

- src/components/Settings/Settings.react.js
Fixed double scrollbar in settings menu
Fixes #3436
Changes : Changed overflow to auto
Demo Link: http://pr-issue-3436-foss-susi-web-chat.surge.sh/
> Fixed unnecessary scrollbar in settings page

- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
Fixes #3432 
Changes: 
- Sorted Skill feedbacks according to the timestamps in DESC order.
- Used `concat` method to avoid mutating the `skillFeedbacks`.
Demo Link: https://pr-3433-fossasia-susi-web-chat.surge.sh
**Before**
**After**
> Sorted the skill feedbacks wrt timestamps

- src/components/cms/SkillCreator/SkillCreator.js
- src/components/shared/Dialog/dialogTypes/ConfirmDialog.js
Fixes #3119 
Changes: 
- Added a new feature to delete any skill the user has created.
Demo Link: https://pr-3462-fossasia-susi-web-chat.surge.sh
> Added functionality to delete user's skill

- public/susi-chatbot.js
Fixes #3446
Changes: 
fixed chatBot Script
Demo Link: https://pr-3452-fossasia-susi-web-chat.surge.sh
> fixed chatBot Script

- src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
- src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
- src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
- src/components/cms/SkillRating/SkillRatingCard.js
- src/components/shared/FiveStarRatingWidget.js
- src/constants/ratingHints.js
- src/redux/reducers/skill.js
Fixes #2181 
Changes: 
- Integrated rating and feedback.
- Rating is necessary but the feedback is optional 
To be merged after https://github.com/fossasia/susi_server/pull/1451 
Demo Link: https://pr-3442-fossasia-susi-web-chat.surge.sh
> Integrated rating and feedback

- src/components/cms/SkillCardGrid/SkillCardGrid.js
Fixes #3455
Changes: Added link to the skill-card 
Demo Link: https://pr2-3457-fossasia-susi-web-chat.surge.sh
> Fixed skillcard

- docs/ACCOUNTING.md
- docs/Skill_Tutorial.md
- src/components/About/Privacy/Privacy.react.js
Fixes #3471 
**Changes:** 
Corrected the typo in `privacy page`
_`feeback` to `feedback`_
> Removing Spelling error in the file.

- package.json
- src/components/Settings/MobileTab.react.js
Fixes #3511 
Changes: Added react-emoji-render. Please run the command npm install react-emoji-render --save 
or yarn add react-emoji-render according to your package manager. I have added 
package.json which consistes the dependency for that.
Demo Link: https://pr-3514-fossasia-susi-web-chat.surge.sh
> [Feat] added country flags

- src/components/Admin/AdminTab/AdminTab.js
- src/components/Admin/ListSkills/SkillTable.js
Fixes #3515
Changes: 
Noticed the response from the table API and made changes accordingly
Demo Link: https://pr-3516-fossasia-susi-web-chat.surge.sh
> Edit Popup appears now for Admin Skills view

- src/components/Footer/Footer.react.js
- src/components/NavigationBar/index.js
Fixes #3532 
Changes: Changes the Link tag in footer and header hyperlink tag.
Demo Link: https://pr-3532-fossasia-susi-web-chat.surge.sh
> Fixed: Home page doesn't renders on clicking Susi Icon #3532

- src/apis/index.js
Fixes #3547 
Changes:
Used Axios in place of ajax. On using ajax, access token is added in the url when the user is logged in due to which contributors section gets empty.
Demo Link: https://pr-3547-fossasia-susi-web-chat.surge.sh
> Fixed:Contributors section is empty in the Team Page when a user is logged in

- src/components/Settings/ShareOnSocialMedia.js
- src/utils/CopyWithButton.js
Fixes #3527 
Changes: 
- Center aligned items using flexbox
- Increased text area width and centered it.
Demo Link: https://pr-3536-fossasia-susi-web-chat.surge.sh
> fix(share-susi-modal): aligned the modal items - I3527

- src/components/About/Devices/index.js
Fixes #3559
Changes: 
- Fixed the grammatical errors on ```devices/index.js```
Demo Link: https://pr-3560-fossasia-susi-web-chat.surge.sh
> fix(devices/index.js): corrected subtitle grammar - I3559

- src/components/NavigationBar/index.js
- webpack.config.js
Fixes #3554 
Demo Link: https://pr-3556-fossasia-susi-web-chat.surge.sh
> Move search bar in navigation bar to center

- src/components/About/Team/index.js
- src/components/Footer/Footer.react.js
- surge_deploy.sh
Fixes #3557  
Changes: Changed the Link tags in the footer with the hyperlink tags.
Demo Link: https://pr-3557-fossasia-susi-web-chat.surge.sh
> Fixed: About,Devices,Support,Blog page doesn't renders from footer through Team Page 

- src/components/About/Contact/Contact.react.js
Fixes #3573
Changes: removed gMap from the contact page
Demo Link: https://pr-3574-fossasia-susi-web-chat.surge.sh
> Delete Google Maps from https://susi.ai/contact

- src/components/NavigationBar/index.js
Fixes #3565 
**Changes:** CheckBox icons are added in Language Menu which changes according to the selections.
**Screenshot of the change:**
> Checkbox icon added to language select menu

- src/components/cms/BrowseSkill/SideDrawer.js
Fixes #3580 
Changes: Add an icon for showing category menu
Demo Link: https://pr-3581-fossasia-susi-web-chat.surge.sh
> added a icon for category menu

- .gitignore
Fixes #3591 
Changes: Added package-lock.json to gitignore.
> added package-lock,json to gitignore

- README.md
> This will make it look a lot cleaner and readable.
**Related Issue:** #3599
> feat(docs): Update README.md

- Dockerfile
- README.md
- package.json
Fixes #3610
Changes: 
* Dockerfile is fixed and  a script with host 0.0.0.0 is added to package.json
* Installation with docker instructions has been added to readme file
Before:
Now:
> susi.ai is made functional with docker

- src/apis/index.js
- src/components/cms/BotBuilder/BotWizard.js
Fixes #3507 
Changes: 
- Destructured the skill data object and used it as payload.
- Corresponding changes in server https://github.com/fossasia/susi_server/pull/1458
Demo Link: https://pr-3508-fossasia-susi-web-chat.surge.sh
> Resolved save drafts issue in bot wizard
