fossasia/susi.ai

index.html

This is resolve to the issues #29 and included some changes based on the pull request #32
My Changes here:
-Move things from the right menu to the left menu
-add to the right menu an download button
-add comments to the index.html that beginners at html will better understand your html code
-add footer to the website
-add metaData for google etc.
Hope you like it and will use it! :)
My Screenshots: https://drive.google.com/file/d/0Bz2QPxTFlhAhYy14aG1qTnhldVk/view?usp=sharing
https://drive.google.com/file/d/0Bz2QPxTFlhAhWERneTJ3NTJ3anM/view?usp=sharing
As you can see I add on the right an download button so the user can easier download it without searching for it. But to make place for it I move the items from the right to the left. Additional I add a footer which include links to: this …

Changes to #32 and the issue #29

---

css/style.css

**Before**
After applying - changed margin values for .chat .chat-history .message-data

Fixes Issue #56 : Inconsistency with time stamp alignments.

---

src/actions.js
src/components/ChatApp.css
src/components/MessageListItem.react.js
src/utils/ChatMessageUtils.js

Demo Link: http://susiwebsearch.surge.sh/
Sample Queries: 'Germany', 'Marvel', 'artificial Intelligence' etc which give action type websearch
For few queries like 'find me restaurants', even duckduckgo doesnt give any response. How to handle such cases?
Also the css can be changed. And the number of results too.
Right now, Im displaying all results without 'Name' attribute i.e popular results and one from each category (when 'Name' attribute is present).
I refactored MessageListItem.js as I added actions attribute to message. I know its not related to this issue, will take care from next time :)
Also added the abstract if present as the first tile - but needs css support

Fixes #78 (partly) - Websearch support

---

public/index.html

Fixes **Issue #110**
**Changes:**
Zooming is disabled now to ensure responsiveness of the chat on phones.
**Demo Link:**
Please test in phones.

Fixes #110 - Disables zoom feature in the mobile site

---

src/components/MessageListItem.react.js

Fixes issue #102 
**Changes:**
Matched response text with a regex to parse image URLs and replace with img tags.
**Demo Link:** http://imagesupport.surge.sh/
**Sample Query:** 
- random gif 
- get me a meme

Fixes #102 - Parse response to show images

---

src/components/ChatApp.css
src/components/MessageListItem.react.js

Fixes issue #125 
**Changes:**
Added overflow checks to maintain the websearch tiles size and a image container to display images without stretching.
**Demo Link:**  http://websearchcss.surge.sh/ 
**Sample Query:** search for *

Fixes #125 - Rectifies websearch tiles css

---

src/components/MessageListItem.react.js

Fixes issue #128 
**Changes:**
If the websearch results are empty, display NO Results Found message
**Demo Link:** http://noresults.surge.sh/
**Sample Query:** baseless args

Fixes #128 - Shows no results found after websearch

---

package.json
src/components/MessageListItem.react.js

Fixes issue #132 
**Changes:**
Used react-swipe to make the websearch results tiles horizontally swipable
**Demo Link:**  http://webtileswipe.surge.sh/
**Sample Query:** search for *

Fixes #132 - Makes websearch result tiles horizontally swipable

---

src/__tests__/utils/ChatMessageUtils.js

**Fixes issue #137**
**Changes:**
- Removed check for id causing Travis failures
@isuruAb @uday96 @madhavrathi Please review

Fixes #137 : Check for message id fails due to timestamp suffix

---

src/actions.js

**Fixes issue #60**
Changes:
- Fetches ISO 639-1 of the browser and send it to fetch reeponse
**Demo Link: http://susi.surge.sh**
Watch out for console. to see the response generated
Sample response
```
Object {query: "hi", count: 1, client_id: "aG9zdF8xNDEuMTAxLjk5LjE0NQ==", query_date: "2017-06-03T18:36:51.982Z", answers: Array(1)…}
answer_date
:
"2017-06-03T18:36:51.983Z"
answer_time
:
1
answers
:
Array(1)
client_id
:
"aG9zdF8xNDEuMTAxLjk5LjE0NQ=="
count
:
1
language
:
"en"
query
:
"hi"
query_date
:
"2017-06-03T18:36:51.982Z"
session
:
Object
```
@isuruAb @uday96 @madhavrathi Please review

Fixes #60: Send ISO 639-1 to server

---

src/components/ChatApp.css
src/components/MessageListItem.react.js

Fixes issue #151 (partly)
**Changes:**
Instead of combining the data from all action elements and displaying a single response, we loop through each action element and render it.
As of now, every element is displayed with 0 delay.
Delay can be implemented creating a different issue.
**Demo Link:** http://loopactions.surge.sh/
**Sample Queries :**
1. Where is *
2. Search for * 

Fixes 151 - Loop Through Actions and display msgs

---

src/components/MessageListItem.react.js

Fixes issue #162 
**Changes:**
Client now handles the case when the coloumns returned in table action type is an array or a key value object.
**Demo Link:** http://tablecolsarray.surge.sh/

Fixes #162 - Handle coloumn names as array in table action

---

src/components/MessageListItem.react.js

Fixes issue #185 
**Changes:**
Used count attribute from server response to limit the table rows
count = -1 => infinite or show all results
**Demo Link:**  http://tablelimit.surge.sh/
**Sample Query:** universities in germany (returns count = -1)

Fixes #185 - Using count from server response to limit results for table

---

src/components/MessageListItem.react.js

Fixes issue #174 
**Changes:** Removed the redundant text being displayed along with table
**Demo Link:** http://removetexttable.surge.sh/
Query: Susi, Please read the RSS feed from https://news.ycombinator.com/rss

Fixes #174 - Remove text displayed along with table

---

src/actions.js

**Fixes issue #193**
Changes-
- Now History will be fetched, to maintain a consistent chat history across all devices.
Demo Link: 
@uday96 @madhavrathi @isuruAb Please review

Fixes #193:Fetch old messages as soon as one is logged in

---

src/actions.js
src/index.js
src/utils/ChatWebAPIUtils.js

Fixes issue #179 
**Changes:**
Added an action to get location info of the client based on IP address.
Used API : http://ipinfo.io/ (similar to android client)
**Demo Link:** http://clientlocation.surge.sh/
**Screenshot:** 

Fixes #179 - Sending location info of client

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/ChatApp/ChatApp.react.js
src/components/ChatApp/MessageSection.react.js

Fixes issue #224 
**Changes:**
Upon forgot password success, the user is now redirected to the landing page with the login dialog opened.
**Demo Link:**  http://loginroute.surge.sh/

Fixes #224 - Fix route from forgot password to login

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes issue #240 
**Changes:**
* Added a cancel button to redirect from forgot password page to landing page
* Fixed chat anonymously route in login dialog
If we dont reload the window, we get a setState error, so i added window.reload() after redirecting to "/"
**Demo Link:**  http://cancelbtn.surge.sh/

Fixes #240 - Add cancel button to forgot password form

---

src/components/ChatApp/MessageListItem.react.js

Fixes issue #253 
**Changes:**
* Added `<abbr> tag` to elements in table to show the entire cell content on hover
**Demo Link:**  http://tablehover.surge.sh/

Fixes #253 - Show table content on hover

---

src/actions/Settings.actions.js
src/actions/index.js
src/components/ChatApp/Settings.react.js
src/stores/UserPreferencesStore.js

Fixes issue #272 
**Changes:**
* Added action to set default server
Now upon clicking `reset defaults` in settings dialog, we can see the defaults printed in console.log and there is no error.
**What needs to be implemented yet:**
To actually test the default settings, the support to push and pull userdata to and from server and accordingly updating the userpreferences store must be implemented first which is still not implemented.
**Demo Link:**   http://setdefserver.surge.sh/

Fixes #272 - Fix default server option in settings dialog

---

src/actions/Settings.actions.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/ChatApp/HardwareComponent.js
src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/MessageSection.react.js
src/components/ChatApp/SearchSection.react.js
src/components/ChatApp/Settings.react.js
src/stores/SettingStore.js
src/stores/UserPreferencesStore.js

Fixes issue #295 
**Changes:**
* Removed theme from SettingsStore and all the actions related to it
* Used theme in UserPreferencesStore to store theme upon every theme change action
**Needs to be implemented:**
* Pushing and pulling the user data (UserPreferencesStore data) to and from server so that the changes  are maintained upon refreshing the page or login logout.
**Demo Link:**  http://changethemesetting.surge.sh/

Fixes #295 - Remove Change Theme as drop down and include it in settings

---

src/actions/Settings.actions.js
src/actions/index.js
src/components/Auth/Logout.react.js
src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageSection.react.js
src/components/ChatApp/Settings.react.js
src/constants/ChatConstants.js
src/index.js
src/stores/UserPreferencesStore.js
src/utils/ChatWebAPIUtils.js

Fixes issue #294 
**Changes:**
* Removed redundant actions related to server
* Changed the settings dialog similar to android client (The sub headings and headings)
* In logged in mode, Now, the option change server prompts the user to login again
**Needs to be implemented:**
* Change server option in Chat anonymously mode (https://github.com/fossasia/chat.susi.ai/issues/293)
**Demo Link:**  http://serversettings.surge.sh/

Fixes #294 - Propmt logout on choose server in logged in mode

---

src/components/ChatApp/SearchSection.react.js

Fixes issue #310 
Changes: 
- now it does not trim the search keyword.
- it gives users to search for words and word phases.

Fixes:#310 search allows spaces

---

package.json
src/components/ChatApp/MessageListItem.react.js

Fixes issue #307 
**Changes:**
* Added a module to parse all kinds of html special chars and entities
**Demo Link:** http://htmlsplchars.surge.sh/
**Etherpad Link:** http://dream.susi.ai/p/splhtmlchars

Fixes #307 - Handle All types Of HTML Special Entities Parsing

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageListItem.react.js

Fixes issue #323 
**Changes:**
* Removed the anchor tag styling for tile text - the tile content wont show any underline but the entire tile is hyperlinked.
**Demo Link:**  http://websearchrss.surge.sh/

Fixes #323 - Remove the anchor styling for tile text

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/Settings.react.js

Fixes issue #337 
**Changes:**
* Styled settings dialog for mobile screens
* Fixed the padding - making it closer to the left of the dialog
**Demo Link:** http://mobilesettings.surge.sh/

Fixes #337 - Fix settings dialog content alignment in mobile screens

---

src/components/ChatApp/MessageSection/DialogSection.js
src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #376 
**Changes:**
* Initialised `showSignUp` in state as `false`
* Changed `open` into `showLogin` to maintain code readability
* Addded missing `showForgotPassword` prop to `Login` in Dialog Section
**Demo Link:** http://dialogwarnfix.surge.sh/

Fixes #376 - Remove warning for missing initialised prop in dialog section

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/helperFunctions.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #382 
**Changes:**
* Added indicators for messages sent by user where
1. Messages for which server response is already obtained, has a `tick` symbol
2. Message just sent by user waiting for server response, has a `clock` symbol
* Created a new function `renderMessageFooter` in helperFunctions.js to render time and status indicator
**Demo Link:** http://messagestatusindicators.surge.sh/

Fixes #382 - Added status indicators to user messages

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #412 
Changes: Now user can choose background for message section as well.
Demo Link: http://susimadhav.surge.sh/
@rishiraj824 @uday96 @isuruAb @daminisatya Please Review
Thanks

Fixes#412: user can now add background image to message section

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #402 
Changes: 
- Adding snackbar to notify if the user is offline
- Added snackbar to notify if the user is online
Testing - 
Try to disconnect your Internet connection and connect back.
Demo Link 
http://susiinternet.surge.sh

Fixes #402 - Show No connectivity when no Internet connection is there

---

src/components/ChatApp/ChatApp.css

Fixes issue #429
Changes: Remove the Horizontal scroll bar when the message bubble is too small .
Demo Link:  http://isuruab.surge.sh/
Screenshots:

Fixes: #429- remove the scroll bar when the message bubble is too small .

---

package.json
src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes issue #445 
**Changes:**
* Added a new library [html-react-parser](https://www.npmjs.com/package/html-react-parser) to convert HTML strings into React elements and also handle Special HTML entities
**Demo Link:** http://htmlsupport.surge.sh/
**Etherpad Link** http://dream.susi.ai/p/anchortest
**Sample Queries**:
-  html demo
- html text

Fixes #445 - Support to convert HTML strings to React elements

---

src/actions/API.actions.js
src/actions/ChatApp.actions.js
src/actions/index.js
src/components/ChatApp/MessageListItem/Feedback.react.js
src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/helperFunctions.react.js
src/constants/ChatConstants.js
src/stores/MessageStore.js

Fixes issue #469
**Changes:**
* Users can now like or dislike the responses
* Moved feedback UI to a new component to maintain like dislike state and highlight the icons accordingly
* Store the feedback until the user sends another message so as to enable the user to change his feedback and not make multiple calls for every change and only send the final feedback once to the server i.e when the user sends a new message, send the feedback of previous response to the server
**Demo Link:** http://susifeedback.surge.sh/

Fixes #469 - Added functionality to skill rating UI

---

src/__tests__/components/Settings.js
src/actions/Settings.actions.js
src/actions/index.js
src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/VoicePlayer.js
src/components/ChatApp/MessageSection/DialogSection.js
src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/Settings/TextToSpeechSettings.react.js
src/constants/ChatConstants.js
src/stores/UserPreferencesStore.js

Fixes issue #477 
**Changes:**
* Added settings for text to speech
* User can now adjust rate and pitch for speech output
* User can also listen to example speech synthesis output for selected rate and pitch
**Needs to be implemented:**
* Push the settings to server for logged in user
* Store the settings in cookies for anonymous user
**Demo Link:**  http://speechsetting.surge.sh/

Fixes #477 - Added settings to adjust rate and pitch for text to speech

---

src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes issue #482 
**Changes:**
* Convert response content to string in `proccessText` function to handle other data Types from JSON response to for rendering

Fixes #482 - Convert all response content to text for processing

---

src/actions/API.actions.js
src/components/ChatApp/MessageListItem/VoicePlayer.js
src/stores/MessageStore.js
src/utils/ChatMessageUtils.js

Fixes issue #492 
Changes: 
- Now getting voice outputs based on the lang property in message
```
{
"query": "hello",
"count": 1,
"client_id": "aG9zdF84NC4xODEuMTEyLjEzOA==",
"query_date": "2017-07-15T21:31:09.833Z",
"answers": [{
"data": [{
"0": "hello",
"1": "",
"token_original": "hello",
"token_canonical": "hello",
"token_categorized": "hello",
"timezoneOffset": "-120",
"language": "en"
}],
"metadata": {"count": 1},
"actions": [{
"type": "answer",
"language": "en",
"expression": "Hello!"
}],
"skills": ["/susi_server/conf/susi/en_0700_ai_play.json"]
}],
"answer_date": "2017-07-15T21:31:09.855Z",
"answer_time": 22,
"language": "en",
"session": {"identity": {
"type": "host",
"name": "xx.xx.xx.xx",
"anonymous": true
}}
}
```
Demo Link: 
http://susi-voice.surge.sh

Fixes #492 - implement text-to-speech with correct language

---

src/components/ChatApp/TopBar.react.js

Fixes issue #508 
**Changes:**
* Removed `Options` tooltip for toolbar drop down

Fixes #508 - removed options tooltip

---

src/actions/API.actions.js
src/actions/History.actions.js
src/components/ChatApp/MessageListItem/Feedback.react.js
src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/helperFunctions.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js
src/stores/MessageStore.js
src/utils/ChatMessageUtils.js

Fixes issue #512 
**Changes:**
* Maintains the feedback of messages throughout the conversation
* Only for the latest SUSI Response, the user can toggle feedback for the previous messages the feedback is already recorded so the user cannot change it - toggle is disabled
* For messages loaded from the server as history when the app is initialised, the feedback buttons are disabled.
**Next Steps:**
* Improve the UI for feedback buttons - @rishiraj824 is working on it - https://github.com/fossasia/chat.susi.ai/issues/470
**Demo Link:** http://susifeedback.surge.sh/

Fixes #512 - Show feedback for the entire conversation

---

src/components/ChatApp/ChatApp.css

Fixes issue #534
Changes:
- Fixed text-area width for Mac Chrome
- Fixed grammarly auto-sizing the textbox
Demo Link: 
http://susi-textarea.surge.sh

Fixes #534 - Chat input field insufficient width

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageListItem/MessageListItem.react.js

Fixes issue #537 
**Changes:**
* Unified Map response to show text and Map in a single bubble

Fixes #537 - Unify map response and use full width

---

src/components/ChatApp/ChatApp.css

Fixes issue #569 
**Changes:**
* Break line to prevent overflow

Fixes #569 - Break word for message text

---

public/index.html
src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/ChatApp/CustomServer.react.js
src/components/ChatApp/MessageSection/DialogSection.js
src/components/Overview/Overview.react.js
src/components/Support/Support.react.js
src/components/Terms/Terms.react.js

Fixes issue #460 
Changes: 
- Removes useless call to fetch `Lato font`
- Removed the scrollbar
- Using space in the dialog like Facebook login
- Hover states added to Forgot Password and focused color change to Input fields
- Changes made to all login components in `Support, Terms, Overview Pages`
Demo Link: 
http://susi-login.surge.sh

Fixes #460 - Improve Login Popup

---

src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #588 
**Changes:**
* Reset `voice:true` for all messages after VoicePlayer speech output ends to prevent repeated output on re render
**Demo Link:**  http://udaytheja.surge.sh/

Fixes #588 - Fix repeated speech output on re render

---

src/components/Overview/Overview.react.js
src/components/Terms/Terms.react.js

Fixes issue #560 
**Changes:**
* Fixed Drop Down overlay in Top bar for overview page and terms page
* Adjusted height of top bar in overview to be same as landing page of chat

Fixes #560 - Fix drop down overlap in overview and terms page

---

src/components/Overview/Overview.css
src/components/Overview/Overview.react.js

Fixes issue #611 
Changes: increase the height of "Safe and Secure" area on mobile screen
@uday96  @rishiraj824  @madhavrathi  please review

Fixes: #611 - Improve the mobile view of overview page

---

src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes issue #605 
**Changes:**
*  Show feedback thumbs only for the last bubble of susi response as all the bubbles correspond to the same skill so we must collect response only once
**Demo Link:**  http://susifeedback.surge.sh/

Fixes #605 - show feedback thumbs only once for multi action responses

---

src/components/Support/Support.css
src/components/Support/Support.react.js

Fixes issue #637 
Changes: Fixed size of chat examples image in overview page.
Demo Link: http://susisizefix.surge.sh/overview
@mariobehling @rishiraj824 @uday96 @isuruAb Please review.
Thanks

Fixes #637 Fixed size of chat examples images in overview page

---

package.json
src/components/Auth/Login/Login.react.js
src/components/ChatApp/MessageSection/DialogSection.js
src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/TopBar.react.js
src/components/Overview/Overview.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes issue #657 
Changes:
- About -> Overview
- Chat -> /chat app
- Skills -> / skills app
- Settings -> /settings
- Login -> login
- About -> Overview
- Chat -> /chat app
- Skills -> / skills app
- Settings -> /settings
- [Themes -> theme popup (only in chat app)]
- Changed Password 
- Logout -> logout
Demo Link:
http://susi-menu.surge.sh
`/settings` will be added in https://github.com/fossasia/chat.susi.ai/pull/625

Fixes #657-Fix Dropdown menu structure and views across apps and pages

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageComposer.react.js

Fixes issue #668 
Changes: 
- Removed the text overlap with button
- Made the text-area close to WhatsApp
Demo Link: 
http://susi-textarea.surge.sh

Fixes #668 - Improve text area overlap with send button

---

src/components/ChatApp/MessageListItem/MessageListItem.react.js

Fixes issue #537 
**Changes:**
- Made map use full width irrespective of text content in chat bubble
**Demo Link:**  http://susimaps.surge.sh/

Fixes #537 - Make use of full width for map

---

package.json
src/actions/API.actions.js
src/actions/History.actions.js
src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageListItem/helperFunctions.react.js
src/components/ChatApp/Settings/Settings.react.js
src/index.js
src/stores/UserPreferencesStore.js

Addresses issue #575
Changes: 
- Fetching local browser language and passing as props to the application.
- All Message `Time/Date and Dates` follow Internationalization based on formats in [https://formatjs.io]FormatJS)
- Added feature to send preferred language to the server and storing it in cookies as well for anonymous users.
Default value is  `PrefLang:en-US` 
- Translation for the Message section enabled, Messages shown and History will be rendered based on Preferred Language.
Demo Link - 
http://susi-international.surge.sh
Screenshots: 
Head over to `/settings` and select language from the `Language Settings` from the dropdown and change your preferred language to get responses from different languages and see all text in the preferred language.
Example for Italian
`France Format` …

[WIP] Fixes #575 - Propose and implement internationalization support

---

src/actions/API.actions.js
src/actions/Settings.actions.js
src/actions/index.js
src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/TopBar.react.js
src/constants/ChatConstants.js
src/stores/UserPreferencesStore.js

Fixes: #664 - Store Custom theme settings in server

---

src/components/ChatApp/Settings/Settings.react.js
src/stores/MessageStore.js

Fixes issue #679 
Changes: 
- Voice List being added once the component is being rendered in `/settings`
- Enabled all options for Speech after detecting the SpeechSynthesis.
Demo Link: 
http://susi-settings.surge.sh/settings

Fixes #679 - Going to settings route shows Speech Settings disabled

---

src/actions/API.actions.js

Fixes issue #695 
Changes: 
- Handled the case where the user is anonymous and settings are initialized from cookies, where the values of cookies were not set.
- Now, `/settings` would work as all values are set by defaults.
Steps to test -
- Make sure to delete any previous cookies
- Go to Application in Dev Console in anonymous mode and check if the `settings` key is set as shown in the image. 
Demo link -
http://susi-cookies.surge.sh

Fixes #695 - /settings not working, set defaults in the settings even for localStorage

---

src/components/Blog/Blog.css
src/components/Blog/Blog.react.js
src/components/Contact/Contact.css
src/components/Devices/Devices.css
src/components/Devices/Devices.react.js
src/components/StaticAppBar/StaticAppBar.css
src/components/StaticAppBar/StaticAppBar.react.js
src/components/Support/Support.css
src/components/Team/FourButtons.react.js
src/components/Team/Team.css
src/components/Team/Team.react.js
src/components/Terms/Terms.css
src/components/Terms/Terms.react.js

Fixes issue #723 
Changes: 
a) Support b) Contact c) Terms pages uses the same font color as other pages e.g. the overview page
Demo Link: http://isuruab2.surge.sh/

Fixes: #723 - Fixes small design issues

---

src/App.js
src/components/Footer/Footer.react.js
src/components/Privacy/Privacy.react.js

Fixes issue #742 
Changes: 
Demo Link
http://susi-privacy.surge.sh/privacy

Fixes #742 - Add Page "Privacy" and take out "Settings" from Footer

---

src/components/Overview/Overview.css

Fixes issue #748 
Changes: Reduced space between store icons for smaller screens
Demo Link: http://susimadhav.surge.sh/overview
Thanks

fixes #748 reduce space between store icons for smaller screens

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes issue #754 
**Changes:**
- Since other browsers do not support webkit clamp, used css to show a fadeout for multi line overflow in firefox.
**Demo Link:**  http://styleswipe.surge.sh/

Fixes #754 - Prevent card text overflow in firefox

---

src/components/ChatApp/ChatApp.css
src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes issue #771 
**Changes:**
- Removed text decoration for table entries caused due to abbr tag
- Fixed top bar drop down direction on static pages similar to landing chat page
**Demo Link:** http://topbar.surge.sh/

Fixes #771 - Remove decoration for abbr and fix top bar pop over direction

---

src/components/ChatApp/CustomServer.react.js

Fixes issue #809 
Changes: Enable clicking on the text "Use Custom Server" in the Login popup to toggle the option.
Demo Link: [spectacular-writing.surge.sh](http://spectacular-writing.surge.sh/)

Fixes issue #809 - Enable click on the toggle label in Login popup

---

src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js

Further enhancements for issue #796 
Changes: 
-Added Chevron in settings list like twitter
-Fixed the bug in theme selection(was displayed at two tabs)
-Fixed the overflow of div on hover in Logged In state
Demo Link: http://horrible-cakes.surge.sh/

Add more enhancements to settings page #796

---

src/components/ChatApp/MessageComposer.react.js

Fixes issue #825 Colour of send button will turn white only if theme is dark. 
Demo link: http://rahul-singh.surge.sh/
Changes:After changing theme send button colour won't turn into white until changed theme is dark.
To see the work 
1.   login
2.   Select themes 
3.   change  theme
4.   check arrow
In chat.susi.ai site arrow is white that is barely visible
In demo link its blue and clearly visible.
S

Fixes: #825 - changed colour of message send button 

---

src/components/ChatApp/CustomServer.react.js

Fixes issue #829  
Changes: The custom-server button has been center-aligned
Demo Link: near-shoe.surge.sh
Before:
After:

Center-aligned the Custom Server element

---

src/components/Auth/Login/Login.css
src/components/ChatApp/ChatApp.css
src/components/ChatApp/HardwareComponent.js
src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js

Fixes issue #830
Changes: 
1. The 'Add address to connect to hardware' button has been given some margin from the left.
2. The font has been changed to sans-serif from Open Sans in the title of the dialog box on clicking the button mentioned in 1.
3. The connect button has been given margin from the top.
Demo Link: classy-knife.surge.sh
Before:
After:

Appearance improvements in SUSI Hardware Tab in Settings

---

src/components/ChatApp/Settings/Settings.react.js

Fixes issue #819 
Changes:
- Show save button in active stage only when something can be saved
- Show save button inactive when there is nothing to save
- Stay on the same tab after user presses "Save"
- Hide save button from the following tabs, since they are redundant : 
- Server Settings (when logged in)
- Account Settings (when logged in)
- Connect to SUSI Hardware
- Load Initial settings when user changes the tab
- select the theme option based on the actual value rather than having an initial value
- Set the document title in settings page
**Demo Link:** [sneaky-education.surge.sh](http://sneaky-education.surge.sh/)

Fixes issue #819 - Improve save button actions in settings

---

src/actions/API.actions.js
src/actions/History.actions.js

Fixes issue #838 
Changes: Removed multiple calls to google translate API on load of chat app.
Demo Link: http://neat-sack.surge.sh/ (updated)
As the network tab shows, gtranslate only gets called when sending or receiving messages.

Remove unnecessary api calls to gtranslate

---

src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #818 
Changes:
- Copy the user's previous message on pressing 'up' key
- Copy the user's next message on pressing 'down' key
Demo :[overjoyed-skin.surge.sh](http://overjoyed-skin.surge.sh/)

Fix #818 - Copy previous messages on pressing 'up' and 'down' arrow keys

---

src/actions/API.actions.js
src/actions/Settings.actions.js
src/actions/index.js
src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/ChatApp/CustomServer.react.js
src/components/ChatApp/HardwareComponent.js
src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.react.js
src/components/Translate/de.json
src/components/Translate/en.json
src/constants/ChatConstants.js
src/stores/UserIdentityStore.js
src/stores/UserPreferencesStore.js

Fixes issue #840 
Changes:
- Fix bug in saving dark theme while signed in - fixes #841 
- Show User's email address
- Remove unnecessary popups in Settings page
- Disable refreshing after changing settings
- Save changes only for the changed settings of the current tab
- Enable dark theme in Settings page
- Integrate Mobile page
Demo Link: [clammy-park.surge.sh](http://clammy-park.surge.sh)

Restructure Settings, enable dark theme - Fix #840

---

src/components/ChatApp/MessageSection/DialogSection.js
src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #879
**Changes:**
- have a state variable `prevThemeSettings` to store the previous theme on opening of the dialog
- apply the theme from `prevThemeSettings` on closing the dialog
- avoid applying the above step when user "saves" a new theme
**Result:** On closing the change theme dialog, the previously saved settings in applied instead of the unsaved changes.
**Demo Link:** [saveprevtheme-susi.surge.sh](http://saveprevtheme-susi.surge.sh)
@isuruAb @rishiraj824 @madhavrathi Please review.

Fix #879 - set previous theme on exit

---

src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/SearchField.react.js

Fixes issue #823 
Changes:
- Display bottom text field when search is activated 
Demo Link: http://ashamed-care.surge.sh/

Retain bottom text field when search is activated - fixes #823

---

src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes issue #856 
Changes:
-Disable scroll wheel zoom for the map so it doesn't disturb while scrolling through the conversation, instead, the user can use map controls to zoom.
Demo Link: http://substantial-impulse.surge.sh/

Disable scroll wheel zoom for map - fix #856

---

src/actions/API.actions.js

Fixes issue #885 
Changes:
- Make ajax requests for fetching translated example text  asynchronous
Demo Link: http://victorious-run.surge.sh/
Before 
After

Make ajax requests for fetching translated example text  asynchronous

---

src/components/ChatApp/MessageComposer.react.js
src/components/ChatApp/VoiceRecognition.js

Fixes issue #863 #808 
Changes: 
**#863** : Remove event listener onspeechend function which was listening to the wrong event onspeechend instead of speechend. Listening to the correct event speechend would result in two speech to text results generated since onspeechend was calling onEnd, but that is not required in this case since onEnd is automatically invoked when speech recognition ends.
**#808** : Close the speak dialog after 5 seconds of inactivity in speech,(close speak dialog after 5 seconds of a user clicking the mic button if the user does not speak anything till that time.)
Demo Link: https://wiggly-range.surge.sh/

Reduce wait time for Speech and remove onspeechend listener

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes issue #887
Changes: 
- The dialog closes on clicking "Restore to default" button
- The default theme is saved in flux and server after applying
- Erase the previous theme's settings in state on applying the default theme
Demo Link: [bouncy-nut.surge.sh](http://bouncy-nut.surge.sh/)

Improve restoring default theme in theme changer dialog - Fix #887

---

package.json

Fixes issue #903 
Changes: **Removed *react-hljs* from dependencies since it is now deprecated.**
Demo: https://fierce-arm.surge.sh/

Fixes #903, Removed react-hljs from dependencies

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js

Fixes #920 
Changes: Right click won't trigger the login button anymore.
Demo Link: http://susi920.surge.sh/

Fixes #920, Right click won't trigger login button anymore on ForgotPassword component

---

src/components/StaticAppBar/StaticAppBar.react.js

Fixes issue #911 
Changes:
The login button, on clicking Forgot password in the Overview tab, works properly now.
Demo Link:
http://cynical-paint.surge.sh/
Steps to view the changes:
1. Click on About in the main menu.
2. Then click on Login, and then Forgot Password.
3. Click on the Login button, and it should work properly now.
@mariobehling @rishiraj824 @madhavrathi @isuruAb Please review this ASAP :)

Back to Login button fixed in Overview

---

src/components/ChatApp/Settings/Settings.react.js

Fixes issue #873 
Changes:
The titles of some tabs in Settings were not getting changed earlier. Some examples are:
1. Clicking on Account tab after clicking on Password tab or vice versa
2. Clicking on Mobile tab after clicking on Connect to SUSI Hardware tab or vice versa
3. Clicking on ChatApp Settings tab after clicking on Theme tab or vice versa
I've put the titles inside a span element, and now the titles change properly.
Demo Link:  http://dazzling-jellyfish.surge.sh
Please review ASAP :)

Tabs in settings are correctly titled now

---

src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1025 
Changes: Added dark theme style in header of settings.
Before-
After-

Solve header bar issue in dark theme in settings

---

src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js

Fixes issue #1007
**Changes:**
1) Removed height of 550px from style of right menu in Settings.react.js.
2) Added height of 300px under @media constraint for mobile size and 550px otherwise. These changes are made in Settings.css for right menu.
**Demo Link:** https://pr-1012-fossasia-susi-web-chat.surge.sh

Fixes #1007: Removed extra white space on Settings page

---

.travis.yml

Parallelizes the travis ci build into multiple vm instances.
The instances are:
- Testing and getting code coverage matrix
- Deploying pr to surge
- Deploying non-prs
Also added functionality to build from all branches.
Fixes #1051
Demo Link: See the travis ci build (https://travis-ci.org/fossasia/chat.susi.ai/builds/328650006)

Parallelize the travis CI build

---

src/components/ChatApp/Settings/Settings.css

Fixes #1037 
Changes: The Menu options style was getting changed to dropdown after screen got smaller than 1000px horizontally. Now the limit is 1060px.
Demo Link: http://secretive-spot.surge.sh/
Before- (Between 1000px to 1060px horizontally)
Now it'll get changed to dropdown after this point - (at 1060px horizontally)

Fix menu dimension issue in settings

---

src/components/ChatApp/Settings/Settings.css

Fixes #1039
Changes: Changed the height of the box enough so that it can fit all the text properly.
Demo Link: http://living-condition.surge.sh/
Before-
After-

Fix text fit issue in settings

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1067 
Fixes #1068 
Changes: Simply corrected spelling.
Now the "Share on social media" option is working.
Demo Link: http://selfish-curtain.surge.sh/settings (Please login to see changes)

Fixed issue with share on social media in settings

---

README.md

Two dead links fixed, pointing to installation steps of local and surge setup.
Fixes #1094 
Changes: Two dead links fixed, pointing to installation steps of local and surge setup.

Corrects the location of 2 links in readme

---

src/components/ChatApp/MessageSection/DialogSection.js

Fixes #1143 
**Changes:** Removes the horizontal scrollbar from the iframe that loads at the starting of the website using JavaScript so that it still renders perfectly on all browsers.
**Demo Link:** https://pr-1143-fossasia-susi-web-chat.surge.sh
**Current state:**
**Updated state:**

Removes horizontal scrollbar from the iframe

---

src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js

Fixes #1070
Changes: Now switch will be toggled only when we click on the switch and not when we click on the text.(Please refer issue)
Demo Link: http://burly-hole.surge.sh/
Open this link and go to settings.
The toggle switches in menus "ChatApp Settings", "Mic Settings" and "Speech settings" are now triggered only when we click on the switch and not when we click on the text with it.

Solve toggle switch issue in settings

---

src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/Settings/TextToSpeechSettings.react.js

Fixes #1100 
Changes: 
- add header and action buttons in the dialog
- disable the "save" button when the user has not changed any settings in the dialog
- use `RaisedButton` for the Reset buttons and change their texts
- Change "Play Demonstration" button
- remove unnecessary code
Demo Link: https://pr-1101-fossasia-susi-web-chat.surge.sh

fix #1100 - improve Text-to-Speech Dialog

---

src/components/ChatApp/MessageComposer.react.js

Fixes #1154 
Changes: The maximum limit of the message composer box was reduced and now no overlapping takes place
Demo Link: annoying-knee.surge.sh

Adds control to the enlargement of the message composer.

---

src/components/ChatApp/ChatApp.css

Fixes #1102 
**Changes:** Changed the color scheme of the chat messages so as to improve readability in Dark Theme.
**Demo Link:** https://pr-1102-fossasia-susi-web-chat.surge.sh
**Current state:**
**Updated state:**

Changes color scheme of chat messages for Dark Theme

---

src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #1080 
Demo Link: http://frightening-fowl.surge.sh/
Before-
After-

Correct spacing between options under reset password menu

---

src/actions/API.actions.js

Fixes #1104 
Changes: encode user's query by using `encodeURIComponent` built-in function
Demo Link: https://pr-1105-fossasia-susi-web-chat.surge.sh
Before:
After:

encode users query - fix #1104

---

src/components/Auth/Login/Login.css

Fixes #1108 
**Changes:** Changed the colour of the Forgot Password text. I think "red" colour suits better.
**Demo Link:** https://pr-1108-fossasia-susi-web-chat.surge.sh
**Current state:**
**Updated state:**

Changes colour of Forgot Password Text

---

src/components/ChatApp/ChatApp.css

Fixes #1120 
**Changes:** Currently, the date has more indentation space in the dark theme than in the light theme.
This PR solves this inconsistency.
**Demo Link:** https://pr-1120-fossasia-susi-web-chat.surge.sh
The inconsistency is solved.

Solves inconsistent indentation of message date in Light and Dark theme

---

src/components/ChatApp/Settings/Settings.react.js
src/stores/UserPreferencesStore.js

Fixes #1107 
Changes: Added functionality for theme preview as soon as the user selects a 
theme, and reverts back to last saved theme if the setting are not saved.
Implemented by saving the state of current theme into original Theme variable, 
and changing it only when user saves settings.
Demo Link: https://theme-preview.surge.sh

Live Theme preview 

---

src/actions/API.actions.js

Added a default message that is displayed when response of
query is empty, i.e answer was not generated (processed).
Fixes #1150 
Changes: IN  src/actions/API.actions.js :  Added default error message to 
server as response when and empty response is received from server.
Demo Link: http://susi-defaultmsg.surge.sh/

Default message for empty responses. Fix #1150

---

src/components/Blog/Blog.css

Fixes #1112 
Fixes #1117 
Changes:Made code blocks width responsive 
Demo Link: http://pale-plant.surge.sh/
Before:
Now:

Fix issue with code blocks and title on blog page

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes #1194 
**Changes:** Changed the by default keyboard focus state of Save and Reset button so that they are not in focus by default.

Removes the by default keyboard focus on the Reset Button

---

src/components/ChatApp/MessageSection/DialogSection.js

Fixes #1187 
**Changes:** Centred the welcome text because it looks better when it is centred in the dialog box that pops up at the starting of the webpage.
**Demo Link:** https://pr-1187-fossasia-susi-web-chat.surge.sh

Centres the welcome text

---

src/components/ChatApp/ChatApp.css

Fixes #1173 
Changes: Changed the max width limit for search option, that causes image to disappear, to 460px. I changed it from 860px to 460px because at 860px the browser was wide enough to accommodate both SUSI.AI logo and search bar. Please have a look at issue for screenshot of that.
When width is greater than 460px (around 462px in this screenshot) -
When width is less than 460px(around 420px in this screenshot) -

Change the max width limit for search option that causes image to disappear to 460px

---

src/components/ChatApp/TopBar.react.js

Related #1241 
Changes: Add botbuilder to dropdown menu, moved theme above settings.
Demo Link: https://pr-1247-fossasia-susi-web-chat.surge.sh
PS: The botbuilder route will work when https://github.com/fossasia/susi_skill_cms/pull/497 is merged.

Add Botbuilder to the Hamburger menu

---

src/components/ChatApp/TopBar.react.js

Fixes #1253 
Changes: Use correct cookie name to render user EmailID on the AppBar.
Demo Link: https://pr-1254-fossasia-susi-web-chat.surge.sh

Update cookie key to render emailId on the AppBar

---

src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1241 
Changes: Speeds up the drop-down menu animation. 
The official documentation of the Popover component didn't have any Props to customise the duration of the animation in terms of milliseconds. It had Prop only to either turn the animation on or off completely.
Demo Link: https://pr-1241-fossasia-susi-web-chat.surge.sh

Speeds up the Drop-Down Menu Animation

---

src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/TopBar.react.js

Fixes #1248 
Changes:
- remove the "Case Sensitive" toggle option during search.
- make search case insensitive always.
- fix the bug with the `SnackBar` abnormally opening
Demo Link: https://pr-1251-fossasia-susi-web-chat.surge.sh
Before:
After:

fix #1248 - remove toggle case sensitive option in search

---

src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js

Fixes #1222 
**Changes:** Corrects the alignment of left navigation bar of Settings.
**Demo Link:** https://pr-1265-fossasia-susi-web-chat.surge.sh
Settings page when we are logged in -  
Settings page when we are not logged in -

Corrects alignment of left navigation bar of Settings

---

src/components/Auth/Login/Login.react.js

Fixes #1280 
Changes: Fixed bug on login page. Earlier login button is enable even if password field is empty. Now we need to enter both email and password to enable it.
Demo Link: https://pr-1281-fossasia-susi-web-chat.surge.sh
Earlier
Now

Fix bug on login page when password field is empty

---

src/components/ChatApp/TopBar.react.js

Fixes #1292 
Changes: SUSI Logo now routes to "/" instead of redirecting to https://chat.susi.ai when clicked.
Demo Link: https://pr-1293-fossasia-susi-web-chat.surge.sh

Used React Routing instead of anchor tag for SUSI logo

---

src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #1290 
**Changes:** Made the styling of the Login and Signup forms on https://chat.susi.ai consistent with each other, and also consistent with that on https://skills.susi.ai. This involved changing font styling of the text on Signup form, and removal of the icons next to the TextFields on Login form.
**Demo Link:** https://pr-1291-fossasia-susi-web-chat.surge.sh
**Current Login Form:** 
**New Login Form:** 
**Current Signup Form:**
**New Signup Form:**

Consistent styling on Login and SignUp forms

---

src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1296 
Changes: Do not display settings menu item on other pages.
Demo Link: http://susi-chat-pr-1297.surge.sh/

Fixes #1296: Resolve bug of settings menu item appearing on other routes

---

src/components/ChatApp/TopBar.css
src/components/ChatApp/TopBar.react.js

Fixes #1302
Changes: Hide display of email on mobile view as currently susi logo shrinks and disappear while decreasing the size or on mobile view.
Demo Link: https://pr-1304-fossasia-susi-web-chat.surge.sh

Hide email on top bar on mobile view to avoid overlapping with susi logo

---

src/components/ChatApp/MessageComposer.react.js

Fixes #1163 
Changes: Fixed minor issue in the speech recognition toast message which was causing the toast message to show even when speech recogniser didn't start yet. 
To test the changes, open https://chat.susi.ai in an incognito tab, and then click on the mic icon. You'll see a popup asking for mic access. If you don't do anything, you'll see the toast message which shouldn't be the case. This is what is being fixed in this PR. Test the same thing on the demo link to test the changes.
Demo Link: https://pr-1307-fossasia-susi-web-chat.surge.sh

Fixed issues in the speech recognition toast message when mic access is yet to be allowed

---

src/actions/API.actions.js

Fixes 
Send country name and country code in chat.json API #1308
Changes: 
1. Fetched country name and country code along with latitude and longitude from the following API
`https://cors-anywhere.herokuapp.com/http://freegeoip.net/json/`
2. Append country_name and country_code in the chat.json API call.
Demo Link: https://susi--cms.surge.sh

Send country name and code in chat.json query

---

src/actions/API.actions.js

Fixes 
Send device type in chat.json API #1328 
Changes: 
1. Append device_type="Web Client" in the chat.json API call.
Demo Link: https://susi-ai-chat.surge.sh

Send device type in chat.json query

---

src/actions/API.actions.js
src/components/ChatApp/Settings/Settings.react.js
src/stores/UserPreferencesStore.js

Fixes #1330 
Changes: 
- Add user name option in accounts tab
- Implement box type input field for Email
- Add divider between tab heading and content
Demo Link: https://pr-1331-fossasia-susi-web-chat.surge.sh

Add user name in settings and minor UI improvements

---

src/components/ChatApp/MessageComposer.react.js

Fixes #1333 
Changes: 
* Add support for example testing of skill through CMS by extracting URL param and creating a message for it.
Demo Link: https://pr-1336-fossasia-susi-web-chat.surge.sh
NA

Fixes #1333: Add support for example testing of skill through CMS

---

src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1346 
Changes:
- Added "Dashboard" to the top.
- "About" is on the bottom just above login/logout.
- "Botbuilder" is at the current place of "Dashboard".
Demo Link: https://pr-1349-fossasia-susi-web-chat.surge.sh
Not logged in:
Logged in:

Rearrange hamburger menu

---

src/components/Auth/Login/Login.react.js
src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1337
Changes: Now the name of the user is displayed on the top bar instead of the email.
Demo Link: https://pr-1350-fossasia-susi-web-chat.surge.sh

Display name of the user instead of email on top bar

---

package.json
src/components/ChatApp/Settings/Settings.react.js
src/components/TableComplex/TableComplex.react.js

Partially fixes #1361 
**Changes:** Added "Geolocation" and "Room" columns in the Devices table and other minor improvements as mentioned above.
**Note:** Currently, I'm using data for the first two columns in the newly added columns. I'll modify the `/aaa/addNewDevice.json` endpoint on the server to accept 2 more parameters - `room` and `geolocation`. After that is done, then the data for the newly added columns could be added using that.
**Demo Link:** https://pr-1364-fossasia-susi-web-chat.surge.sh

Added "Geolocation" and "Room" columns in the Devices table + Minor improvements

---

package.json
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1346 
Changes: Rearranged hamburger menu for all routes
Demo Link: https://pr-1365-fossasia-susi-web-chat.surge.sh
Not logged in:
Logged in:

Rearrange hamburger menu for all routes

---

src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1360 
Changes: Now the email of the user would be displayed on the top bar if he hasn't saved his name yet.
Demo Link: https://pr-1362-fossasia-susi-web-chat.surge.sh

Display email of the user on the top bar if name hasn't been saved yet

---

src/actions/API.actions.js

Fixes 
Send feedback data for creating logs on server #1347
Strictly merge the server side PR before this one : https://github.com/fossasia/susi_server/pull/835
Changes: 
Created sendFeedbackLogs() function to send the feedback related data for creating logs on the server. The requests sends the following data:
- model
- group
- language
- skill
- feedback
- user_query
- susi_reply
- country_name
- country_code
Demo Link: https://susi-ai-chat.surge.sh
NA

Send feedback logs for analysis

---

src/components/ChatApp/Settings/Settings.css

Fixes #1363 
Changes: Put background of settings to be gray (`rgb(242, 242, 242)`) by default. I didn't change the background of chat page because the chat window is already gray.
Demo Link: https://pr-1372-fossasia-susi-web-chat.surge.sh

Put gray background by default in settings

---

src/components/ChatApp/Settings/Settings.react.js
src/components/TableComplex/TableComplex.react.js

Partially fixes #1361 
Changes: Now, the "room" and "geolocation" columns of the Devices table will display data fetched from the API (as https://github.com/fossasia/susi_server/pull/873 is merged now).
Demo Link: https://pr-1377-fossasia-susi-web-chat.surge.sh

Fetched data from API instead of using data of first 2 columns in Devices table

---

src/components/ChatApp/Settings/Settings.react.js

Partially solves #1361
Changes: Now, clicking on the delete icon deletes the info of the device from the server.
Demo Link: https://pr-1381-fossasia-susi-web-chat.surge.sh

Delete device info from server when Delete icon is clicked

---

src/components/ChatApp/Settings/Settings.react.js
src/components/TableComplex/TableComplex.react.js

Partially solves #1361
Changes: Now, editing info of the device using the Edit icon would save the updated device info on the server.
Demo Link: https://pr-1383-fossasia-susi-web-chat.surge.sh

Update device info on server when Edit icon is used in the Devices table

---

src/components/ChatApp/Settings/Settings.react.js
src/components/TableComplex/RemoveDeviceDialog.css
src/components/TableComplex/RemoveDeviceDialog.react.js
src/components/TableComplex/TableComplex.react.js

Partially solves #1361
Changes: Now, for removing devices, user will have to enter the name of the device as a confirmation (as discussed in the meeting)
Demo Link: https://pr-1385-fossasia-susi-web-chat.surge.sh

Added a confirmation dialog for removing devices

---

package.json
public/index.html
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js
src/config.js

Fixes #1344 
Added google reCAPTCHA v2 with 2 options, audio and image.
Note: The captcha challenges wont resize if we resize the page due to material ui dialog box. Its not a problem from the captcha side. We can either make a new route for sign up page, without a dialog box after this.
**Changes:** [Add here what changes were made in this issue and if possible provide links.]
**Demo Link:** https://pr-1344-fossasia-susi-web-chat.surge.sh

reCAPTCHA in sign-up page #1344

---

package.json

Fixes #1394 
Changes: Format code before running through ESLint checks which saves an extra step of using `npm run format` when ESLint checks fail.
Demo Link: https://pr-1395-fossasia-susi-web-chat.surge.sh

Format code before running through ESLint checks

---

package.json
src/components/ChatApp/Settings/Settings.react.js
src/components/MapContainer/MapContainer.react.js

Fixes #1392 
Changes: Now the message `You do not have any devices connected yet!` is displayed instead of the Table view and Map view, when no connected devices are present. Currently, if no devices are there, then this message is displayed in the Table view, and a map with no markers is displayed in the Map view.
Demo Link: https://pr-1393-fossasia-susi-web-chat.surge.sh

Handled the case with Map view when no connected devices are there

---

package.json
src/components/ChatApp/MessageListItem/MessageListItem.react.js

Fixes #1396 
Changes: Now the queries whose result has an action type "video_play" will result in a video which will be autoplayed. For example, queries like `Play despacito` will now result in a video which will be autoplayed.
Demo Link: https://pr-1397-fossasia-susi-web-chat.surge.sh

Autoplaying of videos of action type 'video_play'

---

src/components/ChatApp/Settings/Settings.react.js
src/components/MapContainer/MapContainer.react.js

Fixes #1399 
Changes: Now clicking on the markers in the map would display the device information. This way we can also figure out which marker corresponds to which device.
Demo Link: https://pr-1403-fossasia-susi-web-chat.surge.sh

Display device information on clicking the marker in the map

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1406 
Changes: Now the swipe gesture first scrolls through the Table View contents, and switches tabs only when we are at the extreme end of the Table View. This makes the Table View contents easily accessible on mobile devices.
Demo Link: https://pr-1407-fossasia-susi-web-chat.surge.sh
To test the changes: 
Add devices to your account and then check the Table View on your mobile device. You'll notice that currently (on chat.susi.ai) you aren't able to access the contents of the Table View as the overflow is set to 'hidden', but setting overflow to 'auto' (as done in this PR) makes the Table View contents accessible even on the mobile devices.
To add device to your account, make API calls like `https://api.susi.ai/aaa/addNewDevice.json?macid=8C-39-45-cc-eb-95&name=DeviceName&room=Ro …

Fixed issues with the swipe gesture interfering with scrolling through Table View contents on mobile devices

---

src/components/ChatApp/ChatApp.css

Partially fixes issue #1398
Changes: Applied same shadow for all top bars.
Demo Link: https://pr-1410-fossasia-susi-web-chat.surge.sh
Top bar of overview page:
Before:
After:

Same top bar shadow everywhere

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1416 
**Changes:** Now clicking on the icons for each tab displays the corresponding section on the right side.
**Demo Link:** https://pr-1418-fossasia-susi-web-chat.surge.sh
**Before:**
**After:**

Fixed issues with clicking of icons in settings

---

src/actions/API.actions.js

Fixes #1422 
* Websearch is now working
*  Add https to duckduckgo url
Demo Link: https://pr-1423-fossasia-susi-web-chat.surge.sh

Fixes #1422: Add https to duckduckgo url

---

src/components/ChatApp/MessageListItem/helperFunctions.react.js

Fixes #1466 
Changes: Removed horizontal scroll from Table responses by breaking text at the end of the window
Demo Link: https://pr-1469-fossasia-susi-web-chat.surge.sh
Before:
After:

Used automatic line break for text in Table response

---

src/components/ChatApp/Settings/TextToSpeechSettings.react.js

Fixes #1462
Changes: For me, on chrome it was working fine. But on firefox it was as reported by @mariobehling.
Material-Ui needs injectTapEventPlugin to create a 300ms tap delay(browsers are fixing/removing the click delay)
See the following stack overflow answer:
https://stackoverflow.com/questions/33541949/react-material-ui-dropdown-menu-not-working
This problem is solved in React 16.4, we can update our existing app, for time being this solution works.
Demo Link: https://pr-1462-fossasia-susi-web-chat.surge.sh

Speech output language not showing up in settings

---

src/actions/History.actions.js

Ref: #1512 
Changes: Used `https` instead of `http` for duckduckgo API calls
Demo Link: https://pr-1516-fossasia-susi-web-chat.surge.sh

Used https instead of http for duckduckgo API calls

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/Settings/TextToSpeechSettings.react.js

Fixes #1538 
Changes: Fixed issues with font colors in dark theme.
Demo Link: https://pr-1539-fossasia-susi-web-chat.surge.sh
Before:
After:

Fixed issues with font colors in dark theme

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #1371 
Changes: Fixed the bug - whenever a user enters same password on new password and verify password section and then changes the new password, the form validation is still set true.
Demo Link: https://pr-1542-fossasia-susi-web-chat.surge.sh
Bug:
Fix:

Fix bug in signup form validation

---

src/components/ChatApp/MessageListItem/MessageListItem.react.js
src/components/ChatApp/MessageSection/MessageSection.react.js

First steps for issue #1515
Changes: 
player state (an array) was added to MessageSection component. addYouTube function was created to add to the player state. addYouTube prop was passed down and bindings in getMessageListitems fucntion were changed for this. Created pauseAllVideos function to pause all playing videos. In MessageListitems component _onReady was created to call addYouTube.. 
net change is that MessageSection has an array which is called player which contains objects that have playVideo() and pauseVideo() functions defined and can be used to play and pause video.
Demo Link: https://pr-1534-fossasia-susi-web-chat.surge.sh

Pause all existing youtube videos when new one is created #1515

---

public/index.html
src/config.js

By mistake, I rebased the commits before updating the branch for PR https://github.com/fossasia/chat.susi.ai/pull/1519
Fixes #1513 
Changes: 
Solves below 2:
1. Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
2. reCAPTCHA couldn't find user-provided function: onloadCallback
Demo Link: https://pr-1513-fossasia-susi-web-chat.surge.sh (Updated)

Fixes Recaptcha console error message, XHR warning #1513

---

src/components/StaticAppBar/StaticAppBar.css
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1549
Changes: 
Username disappears when screen width is less. This hinders the elements in StaticAppBar from overlapping each other when screen width is decreased
Demo Link: https://pr-1550-fossasia-susi-web-chat.surge.sh

StaticAppBar fixes

---

src/components/ChatApp/Settings/Settings.css

Fixes #1554 
Changes: made float "right" in the settings-toggle class. This right aligns the buttons
Demo Link: https://pr-1555-fossasia-susi-web-chat.surge.sh

Buttons aligned

---

src/components/ChatApp/Settings/Settings.css
src/components/ChatApp/Settings/Settings.react.js
src/components/ChatApp/Settings/TextToSpeechSettings.react.js

Fixes #1560 
Changes: When screen size is decreased, the radio buttons aren't misaligned in the speech tab of the settings page.
Demo Link: https://pr-1561-fossasia-susi-web-chat.surge.sh
@anshumanv @akshatnitd @Akshat-Jain  please review, Thanks!

Fixed radio buttons misalignment on decreasing screen size in Speech settings

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1577 
Changes: Edit theme is disabled when the theme chosen is light/dark
Demo Link: https://pr-1581-fossasia-susi-web-chat.surge.sh

edit theme disabled for light/dark theme

---

.gitignore
src/components/Support/Support.react.js

Fixes #1570 
Changes: 'Get started today' banner doesn't show up now when user is logged in.
Demo Link: https://pr-1572-fossasia-susi-web-chat.surge.sh
When logged in:
When not logged in:

Remove 'Get started today' banner when logged in

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1605 
Changes: Username and Email gets displayed in Custom Theme as well
`this.intialSettings` undefined type error is resolved
Demo Link: http://pr-number-1606-fossasia-susi-web-chat.surge.sh/
GIF of the changes:

Text input displays in custom theme and TypeError resolved-(Solves issue#1605)

---

package.json
src/components/ChatApp/TopBar.react.js

Fixes #1588 
Changes: 
The red outline that appeared on the logo on click does not appear now
Demo-Link:  http://1596-fossasia-susi-web-chat.surge.sh/
GIF for the change:

Removed red outline on logo onClick-Solves issue(#1588)

---

src/components/Footer/Footer.css

Fixes #1584 
Changes: The next button at the bottom of the blog page gets aligned properly when screen is squeezed
Demo Link: https://pr-1586-fossasia-susi-web-chat.surge.sh

The next button on the blog page gets aligned properly when screen is squeezed

---

src/components/ChatApp/Settings/Settings.react.js

Fixes #1587 
Changes: Background colour behind settings-menu doesn't change now if another theme was selected other than current theme.
Demo Link: https://pr-1593-fossasia-susi-web-chat.surge.sh
Initially, the theme was light
Now I selected dark theme radiobutton but didn't saved changes
Now when I move to other setting, the bakground remains same of light theme
Same happens in the case of dark theme

fixed background change in settings-menu when theme gets changed

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes #1612 
Changes: When search is at last index and after that clicking the next button , the search start from starting . Similarly for previous button.
Demo Link: https://pr-1613-fossasia-susi-web-chat.surge.sh

Modify next and previous button in search bar

---

src/components/Auth/Login/Login.react.js

Fixes #1582 
Changes: 
1. Removed the check for min password character limit
2. Warning message changed to "Enter a valid password" (showed only when password field is empty)
Demo Link: https://pr-1589-fossasia-susi-web-chat.surge.sh

Remove min password character limit warning when logging in (#1582)

---

src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #1624 
Changes: Placeholder text added in password tab fields
Demo Link: https://pr-1625-fossasia-susi-web-chat.surge.sh

Placeholder text added in password tab fields

---

.gitignore

Fixes #1637 
Changes: Added .vscode into `.gitignore`.
Demo Link: https://pr-1638-fossasia-susi-web-chat.surge.sh

Fixes #1637: vscode is not present in .gitignore

---

src/components/Auth/ChangePassword/ChangePassword.react.js

** Fixes #1635 **
Changes: Updated color check for custom theme in src/components/Auth/ChangePassword/ChangePassword.react.js
Demo Link: https://pr-1636-fossasia-susi-web-chat.surge.sh

Fixes field text color  in password tab (default custom theme)

---

src/components/Overview/Overview.css
src/components/Overview/Overview.react.js

Fixes #1647 
Changes: 
- Adds black space to sides of video to allow the close button to show up
- Moves the close button to the side so that it no longer overlaps with the video
Demo Link: https://pr-1649-fossasia-susi-web-chat.surge.sh

Moved Close Button in Video

---

src/components/MapContainer/MapContainer.react.js

Fixes #1652 
Changes: 
- Use callback refs instead of legacy string ref which leads to use of ReactDOM.findDOMNode( )
- Use arrow function in event listener
Demo Link: https://pr-1652-fossasia-susi-web-chat.surge.sh

Remove legacy String Refs and findDOMNode #1652

---

src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #1730 
Changes: Password warning removed from the Current Password field. Now it only checks whether the field is blank or not.
Demo Link: https://pr-1731-fossasia-susi-web-chat.surge.sh

Minimum password length warning removed from the Current password field

---

src/components/Auth/Login/Login.react.js
src/index.js

Fixes #1758 
Changes: Loading = {false} in catch block and also in then block if login fails.
Demo Link: https://pr-1756-fossasia-susi-web-chat.surge.sh

Fixes #1758: Login loading animation stops if login fails

---

package.json
src/helpers/ajax.js

Fixes #1778 
Changes: Due to ajax.js, using queryString, the npm run build was giving an error. It is fixed now, user can build without any error.
queryString has issues with React 
Demo Link: https://pr-1778-fossasia-susi-web-chat.surge.sh

Fix npm run build error, remove queryString #1778

---

src/constants/SettingsVoiceConstants.js

Fixes #[1868](https://github.com/fossasia/chat.susi.ai/issues/1868)
Changes: The default languages are now arranged alphabetically.
Demo Link: https://pr-1872-fossasia-susi-web-chat.surge.sh
Before:
After

The default languages are arranged alphabetically

---

src/App.js
src/components/Auth/Login/Login.react.js
src/components/Auth/Logout.react.js
src/components/ChatApp/TopBar.react.js
src/components/StaticAppBar/StaticAppBar.react.js

Fixes #1958 
Changes: The changes I have made are as follows:
Demo Link: https://pr-1961-fossasia-susi-web-chat.surge.sh

Fixes #1958: Redundant getAdmin Api calls removed from StaticAppBar and TopBar

---

src/components/ProtectedRoute/index.js

Fixes #1995 
Changes: Currently, in ProtectedRoute component, when the user is not logged in, it is redirecting to /error-404. Instead, it should display not found for that page.
Demo Link: https://pr-1998-fossasia-susi-web-chat.surge.sh

ProtectedRoute: prevent unwanted redirect

---

src/__tests__/components/NotFound/NotFound.js
src/__tests__/components/Support/Support.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/NotFound/NotFound.react.js
src/components/Support/Support.react.js

Fixes #1976 
Changes:
- Used app store to get user details
- Connected redux with NotFound, Support
- Added Tests for NotFound, Support
Demo Link: https://pr-1977-1-fossasia-susi-web-chat.surge.sh

Use app store to get user details instead of cookie #1976

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #1947 
Changes: The changes I have made are as follows:
Demo Link: https://pr-1957-fossasia-susi-web-chat.surge.sh

Fixes #1947: Workaround for captcha key loading failure

---

src/components/ChatApp/Settings/ShareOnSocialMedia.js

Fixes #2032
Changes: Removed Google+ share option from Settings->Share on Social Media.
Reason being no Google+ share option on Share tab from header scroll down list. Erasing Google+ is a better solution since it is going to end its feature due 2nd April 2019.
Commented the undesired part.
After changes:-
Before Modification:-
Objective:- Equalizing Share tab in scroll down list and 'Share on Social Media' tab in settings from scroll down list.

Omitted Google+ from 'Settings'->'Share on Social Media'.  Fixes #2032 

---

src/components/NotFound/NotFound.react.js

Fixes #1997 
Changes: When user is logged in, login and signup buttons should not be visible on 404 page
Demo Link: https://pr-2000-fossasia-susi-web-chat.surge.sh

notFound: hide login and signup buttons when logged in

---

src/helpers/ajax.js

Fixes #2063
Changes: Added additional check for access_token.
Reason: Currently, if the user is logged in, the helper AJAX method appends access_token to payload. Due to this, if someone is calling external API, unnecessary accessToken is added, which can give error
Demo Link: https://pr-2064-1-fossasia-susi-web-chat.surge.sh
Thanks to @akshatnitd for helping me out!

Add option to control accessToken in AJAX helper

---

src/components/Blog/Blog.react.js
src/components/Button/ToTopButton.react.js
src/components/Team/Team.react.js

Fixes #2067 
Changes: I initially just wanted to add a scroll To Top button on the 'Team' page, but since we already had such a button, and I figured it could be reused on multiple pages, I abstracted it out in `ToTopButton.react.js`, and inserted it back into the 'Blog' and 'Team' pages. 
Demo Link: https://pr-2068-fossasia-susi-web-chat.surge.sh

Add scroll ToTopButton to Team page

---

src/components/StaticAppBar/StaticAppBar.react.js

Fixes #2213 
Changes: Remove the timeDuration taken to open the dropDown in static app bar
Demo Link: https://pr-2220-fossasia-susi-web-chat.surge.sh

Take out the ripple effect from the dropdown in static app bar

---

src/App.js
src/__tests__/components/Auth/DeleteAccount/ConfirmDeleteAccount.js
src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Dialog/DialogSection.react.js
src/components/Settings/AccountTab.react.js

Fixes #2225 
Changes:
- Use 2 dialog confirmation approach for DeleteAccount
- Remove separate page
Demo Link: https://pr-2226-fossasia-susi-web-chat.surge.sh

 Use 2 dialog confirmation approach for DeleteAccount #2225

---

src/App.js
src/components/Privacy/Privacy.react.js

Fixes #2212 
Changes: Added content for Privacy page similar to Google's privacy page.(https://policies.google.com/privacy?hl=en-US)
Demo Link: https://pr-2251-fossasia-susi-web-chat.surge.sh

Separate privacy and terms page

---

src/components/cms/BotBuilder/BotWizard.js
src/components/cms/SkillCardList/SkillCardList.js
src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js

Fixes #2318 , #2317 , #2322 
Changes: 
Now clicking on `show all reviews` in Rating Popover redirects to correct link.
Corrected the error in calling the draft API.
Corrected the display of author skills in Skill Feedback page.
Demo Link: https://pr-2323-fossasia-susi-web-chat.surge.sh

Fix Bugs in Skill Feedback, Drafts and Rating Popover

---

src/__tests__/Admin/SystemSettings/SystemSettings.js
src/components/Admin/SystemSettings/SystemSettings.js

Fixes #2295 
Changes: 
Used the create API to update. 
Restricted admin to create an API key without name or value.
Demo Link: https://pr-2303-fossasia-susi-web-chat.surge.sh

Add option to Update API Keys in Admin

---

.gitignore
src/components/Settings/DevicesTab/index.js

Fixes #2338 
Changes: Added a new circular loader in place of the default loader
Demo Link: https://pr-2378-fossasia-susi-web-chat.surge.sh
* Before change
* After change

Fixes:#2338: Added Circular loader in place of Default loader

---

src/App.js
src/__tests__/components/StaticAppBar/LeftMenu.js
src/__tests__/components/StaticAppBar/TopMenu.js
src/components/Admin/Admin.js
src/components/Footer/Footer.react.js
src/components/StaticAppBar/LeftMenu.js
src/components/StaticAppBar/StaticAppBar.react.js
src/components/StaticAppBar/TopMenu.js
src/components/StaticAppBar/constants.js

Fixes #2345, #2388
Changes: 
- Fix scroll on IconButton Click in AppBar
- The scroll was blocked when the menu was open on the top right, fixed that as well
- Reimplemented Top Menu and Left menu connecting the application and improving the navigation.
Demo Link: https://pr-2370-fossasia-susi-web-chat.surge.sh
Top Menu:
Left Menu for mobile view:

Reimplement App Navigation Menu #2345

---

src/components/cms/BotBuilder/Preview/Preview.js

Fixes #2432
Changes: Fix preview chat response based on live skill
Demo Link: https://pr-2443-fossasia-susi-web-chat.surge.sh

Fix preview chat response based on live skill #2432

---

src/components/Admin/ListSkills/ListSkills.js

Fixes #2476
Changes: Fix line break for smaller laptop screens the action buttons disappear in the admin table. Expected: A line break happens in enough space.
Demo Link: https://pr-2479-fossasia-susi-web-chat.surge.sh
On larger laptop:

Add line break in Admin skills on enough space #2476

---

src/App.js
src/__tests__/components/SkillCreator/SkillWizard.js
src/__tests__/components/SkillHistory/SkillHistory.js
src/__tests__/components/SkillRollBack/SkillRollBack.js
src/__tests__/components/SkillVersion/SkillVersion.js
src/components/NavigationBar/TopMenu.js
src/components/NavigationBar/constants.js
src/components/cms/AuthorSkills/AuthorSkills.js
src/components/cms/BotBuilder/BotBuilder.js
src/components/cms/BotBuilder/BotWizard.js
src/components/cms/BrowseSkill/BrowseSkill.js
src/components/cms/BrowseSkill/BrowseSkillByCategory.js
src/components/cms/BrowseSkill/BrowseSkillByLanguage.js
src/components/cms/Dashboard/MyRatings.js
src/components/cms/Dashboard/MySkills.js
src/components/cms/Dashboard/index.js
src/components/cms/SkillCardGrid/SkillCardGrid.js
src/components/cms/SkillCardList/SkillCardList.js
src/components/cms/SkillCardScrollList/SkillCard.js
src/components/cms/SkillCreator/SkillCreator.js
src/components/cms/SkillCreator/SkillWizard.js
src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
src/components/cms/SkillHistory/SkillHistory.js
src/components/cms/SkillPage/SkillListing.js
src/components/cms/SkillRollBack/SkillRollBack.js
src/components/cms/SkillVersion/SkillVersion.js

Fixes #2489
Changes: Remove slug `/skills` across web-app. The skills slug is no longer needed to distinguish parts of the system
Demo Link: https://pr-2490-fossasia-susi-web-chat.surge.sh

Remove slug /skills across web-app

---

src/components/NavigationBar/Styles.js
src/components/NavigationBar/constants.js
src/components/NavigationBar/index.js
src/components/shared/CircleImage/index.js

Fixes #2425
Changes: 
- Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in
- made a dropdown on the (?) symbol on the menu and showed "Support" and "About" 
Demo Link: https://pr-2482-fossasia-susi-web-chat.surge.sh

Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in

---

src/components/cms/SkillCardScrollList/SkillCardScrollList.js
src/redux/reducers/skills.js

Fixes #2514 
Changes: Display system skills above staff picks.
Demo Link: https://pr-2526-fossasia-susi-web-chat.surge.sh

Add list of System Skills on start page

---

src/components/cms/BrowseSkill/BrowseSkill.js
src/components/cms/SkillCardScrollList/SkillCard.js
src/components/cms/SkillCardScrollList/SkillCardScrollList.js

Fixes #2597 
Changes:
- Remove FAB from skill slider in mobile view
Demo Link: https://pr-2598-fossasia-susi-web-chat.surge.sh

Fixes #2597: Remove FAB from skill slider in mobile view

---

src/components/cms/SkillSlideshow/index.js

Fixes #2605 
Changes: Slides: Skills linked on the slideshow should open on the same page in chat instead of /chat
Demo Link: https://pr-2607-fossasia-susi-web-chat.surge.sh

Fix Slider Skill to open in chat example

---

src/components/NavigationBar/SearchBar.js
src/components/NavigationBar/index.js

Fixes #2656 
Changes: if username or email is greater than 21 character then first 21 characters + ".." will be displayed.
Changed the search bar width to 39rem.
Demo Link: https://pr-2659-fossasia-susi-web-chat.surge.sh

Fix Menu Bar icons on the right disappear on small screens

---

src/apis/index.js
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes #2663, #2662
Changes: 
Demo Link: https://pr-2664-fossasia-susi-web-chat.surge.sh

Add server side validation for SignUp user, session storage for user

---

src/components/NavigationBar/index.js
src/components/cms/MyDevices/DeviceWizard.js

Fixes #2667 
Changes: 
Fixed username width in navigation bar.
Deleting the device on device wizard redirects to `mydevices` page.
Demo Link: https://pr-2668-fossasia-susi-web-chat.surge.sh

Fix username width in navigation bar and redirect on device delete

---

src/apis/index.js
src/components/Admin/ListUser/index.js
src/components/NavigationBar/index.js

Fixes #2734 #2726 
Changes: Fixed delete user account by admin and click on `?` icon on the navigation bar redirects to `/about` route.
Demo Link: https://pr-2735-fossasia-susi-web-chat.surge.sh

Fix Admin: Not able to delete account and top menu link ? to /about

---

src/apis/index.js
src/components/cms/MyDevices/ControlSection.js
src/components/cms/MyDevices/index.js

Fixes #2743
Changes: Added device configuration options to the control page for the Smart Speaker
Demo Link: https://pr-2768-fossasia-susi-web-chat.surge.sh

Add device configuration options to the control page for the Smart Speaker

---

src/App.js
src/components/cms/SkillCreator/SkillWizard.js
src/components/shared/DeviceProtectedRoute.js
src/utils/urls.js

Fixes #2744, #2767
Changes:
Demo Link: https://pr-2776-fossasia-susi-web-chat.surge.sh

Add Device protected route to disable skill edit in local mode #2744

---

src/components/Admin/Admin.js
src/components/Admin/Messages/index.js
src/components/Admin/Messages/message-config.js
src/components/Admin/Messages/table-config.js

Fixes #2547 
Changes: Add email messages sent from admin under messages tab in admin panel
Demo Link: https://pr-2777-fossasia-susi-web-chat.surge.sh

Add email messages #2547

---

src/utils/urls.js

Fixes #2769
Changes: Add a function which checks if `LOCAL_ENV` variable is `true` and use the correct API URL accordingly
Demo Link: https://pr-2804-fossasia-susi-web-chat.surge.sh

use correct host address for SUSI Sever API URL[WIP]

---

src/components/cms/MyDevices/ControlSection.js
src/components/cms/MyDevices/DeviceWizard.js
src/components/shared/AppBanner.js
src/components/shared/Dialog/index.js
src/index.js

Fixes #2784
Changes: Make SUSI Smart Speaker Device Control page independent of login
Demo Link: https://pr-2820-fossasia-susi-web-chat.surge.sh

SUSI Smart Speaker Device Control page independent of login #2784

---

src/components/cms/BrowseSkill/BrowseSkill.js
src/redux/reducers/skills.js

Fixes #2826 
Changes: Replaced `throw new Error` with console.log
`metricSkills ` will be an empty object is `metrics` from  payload is undefined.
Demo Link: https://pr-2855-fossasia-susi-web-chat.surge.sh

Load groups action failed + Cannot read property 'staffPicks' of undefined

---

src/components/NavigationBar/SearchBar.js
src/components/NavigationBar/index.js

Fixes #2671 
Changes: `?` menu is completely inside the screen.
Demo Link: https://pr-2856-fossasia-susi-web-chat.surge.sh

Fix menu under ? is not completely inside the screen

---

src/components/cms/SkillCardScrollList/SkillCard.js

Fixes #2900 
Changes: Scroll button appears when the scroll cards exceed maxwidth of the window
Demo Link: https://pr-2910-fossasia-susi-web-chat.surge.sh
**Before**
**After**

made changes to scroll in skillcard

---

src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js

Fixes #2894 
Changes: Wrapped the table inside a div with overflow-x set to auto
Demo Link: https://pr-2908-fossasia-susi-web-chat.surge.sh

fix table overflow for bot builder configuration UI View

---

src/components/shared/ColorPickerComponent/index.js

Fixes #2935 
Changes: The colorValue was not getting reset as its value was initially set to `defaultValue` instead of just `value`.
Demo Link: https://pr-2939-fossasia-susi-web-chat.surge.sh

Color reset bug solved

---

src/redux/reducers/settings.js

Fixes #2919 
Changes: Set the default avatar as "default" when initially no avatar is selected by a new user.
Demo Link: https://pr-2927-fossasia-susi-web-chat.surge.sh
**Before**
**After**

Set "default" avatar selected by default

---

src/components/cms/Dashboard/MyRatings.js
src/components/cms/Dashboard/MySkills.js

Fixes #2990 
Changes: 
Updated the `MyRatings.js` and `MySkills.js` to hide table headers when there are no ratings or skills of the user to display.
Demo Link: https://pr-2991-fossasia-susi-web-chat.surge.sh
**Before**
**After**

Fixes #2990: Hide table headers when there are no values to show

---

src/components/Settings/AccountTab.react.js
src/components/Settings/Settings.react.js

Fixes #2977 
Changes: 
1) Changed the overflow property of the root container in settings page from 'hidden' to 'scroll', enabling the page to be scrolled.
2) Changed the position property of the Timezone styled component from absolute to relative. 
Demo Link: http://enchanting-run.surge.sh/

Fixes 2977 - Making the settings page scrollable

---

src/components/NavigationBar/index.js

Fixes #2975 
Changes: 
1) The "ExpandMore" icon is now displayed only in screen widths above 400. 
2) Added some margin to the left of the "CreateDetail" button.
3) Changed the color of the "Add" icon to white.
For the context this was how the AppBar looked **previously**
This is how the it will look in different widths with the changes.(The width is at the top of the image).
Demo Link: http://ruddy-cow.surge.sh/

Fixes 2975 - Restyled AppBar for mobileviews with small width

---

src/utils/urls.js

Fixes #2986 
Changes: 
-Changed all urls https://susi.ai/chat  and  https://susi.ai/skills -> https://susi.ai
Demo Link: https://pr-2988-fossasia-susi-web-chat.surge.sh

updated chat urls to susi.ai

---

src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
src/components/cms/SkillCardScrollList/SkillCard.js
src/components/cms/SkillPage/SkillListing.js
src/components/shared/Badges.js

Fixes #3028
Changes: 
1) Added a tooltip for the staff pick image.
2) Added a badge in skill listings page to identify staff pick skills.
Demo Link: https://pr-3030-fossasia-susi-web-chat.surge.sh

Fixes #3028 - Improved Staff Pick Badge

---

src/components/cms/BrowseSkill/BrowseSkill.js

Fixes #3003 
Changes: Earlier the no skills text was inside the grid which had defined columns so it wasn't possible to center align the the individual grid with respect to the screen. Have placed the text in a new division (instead of reusing that in grid) which shows up in case of no skills found.
Demo Link: https://pr-3020-fossasia-susi-web-chat.surge.sh

Center aligned no skills text

---

src/components/cms/SkillCreator/SkillWizard.js

Fixes #3012
Changes: Tooltips added to the icon buttons of `Code`,`Conversation` and `Tree` in **Create Skill Page**
Demo Link: https://pr-3013-fossasia-susi-web-chat.surge.sh
**Screenshots**

Fixes #3012 :Tooltips added to iconbuttons in createSkillPage

---

src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
src/components/shared/Dialog/index.js

Fixes #2948 
Changes: 
**In SkillFeedbackCard.js**
-A `componentDidMount` life cycle hook is used to intialise the `newFeedbackValue` to the previous feedback submitted by the user.
**In index.js**
-`EditFeedbackDialog` component was imported from `EditFeedbackDialog.js` instead of `EditFeedback`.
Demo Link: https://pr-2956-fossasia-susi-web-chat.surge.sh

Fixes edit feedback issue 

---

src/components/cms/SkillCreator/SkillWizard.js

Fixes #3067 
Changes: 
Instead of hardcoding the warning message when no `category`,`language` or `skill name` is provided changes are done such that it displays warning messages accordingly.
Demo Link: https://pr-3068-fossasia-susi-web-chat.surge.sh

Set warning messages separately for category,language and Skill name

---

src/components/ChatApp/MessageSection/MessageSection.react.js
src/components/ChatApp/SearchField.react.js

Fixes #3079 
Changes: The icons on the chat window now have titles like 'search', 'Full screen','Exit' and when in full screen it shows 'Exit full screen' for full screen option
Demo Link: https://pr-3092-fossasia-susi-web-chat.surge.sh

Fixes: #3079 Now the icons on the chat window have titles

---

src/components/cms/SkillCardGrid/SkillCardGrid.js

Fixes #3117 
Changes: Added CSS properties to truncate long author names
Demo Link: https://pr-3118-fossasia-susi-web-chat.surge.sh

fix(skillCard): added property to truncate text in card

---

src/components/cms/SkillRating/SkillRatingCard.js
src/utils/getSkillNameFromSkillTag.js

Fixes #3123
Changes: 
Created a new function to implement correct rendering of name to be diplayed
Demo Link: https://pr-3131-fossasia-susi-web-chat.surge.sh

Fixes #3123 Now Skill Names are correctly displayed

---

package.json
src/components/cms/BrowseSkill/BrowseSkill.js
src/components/cms/BrowseSkill/skillLoader.js

Fixes #3063 
Changes:  Have added react content loader. Instead of traditional spinner the content loader shows up just like in Facebook, youtube etc. From UI perspective content loaders look better when there are cards present on the page
Demo Link: https://pr-3090-fossasia-susi-web-chat.surge.sh

feat(): added content loader for cards

---

src/components/ChatApp/MessageComposer.react.js
src/components/cms/BotBuilder/Preview/Preview.js
src/utils/onChatComposerKeyDown.js

Fixes #3145 
Changes: 
- View the previous message in the chat by calling function `bringPreviousMessage()`.
- When `UP_KEY_CODE` or `DOWN_KEY_CODE` is the `keyCode` user entered it will call the conditions accordingly.
Demo Link: https://pr-3146-fossasia-susi-web-chat.surge.sh

Made changes in Preview to view previous chat message

---

src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js

Fixes #3070 
Changes: Changed the skill feedback pagination check `skillFeedbacks` already contains  user feedback information and the other feedback info as well so the check  `(userFeedbackCard && skillFeedbacks.length >= 4)` is redundant and instead the check should straight away be skillFeedbacks.length >= 5. And with this change pagination works fine
Demo Link: https://pr-3202-fossasia-susi-web-chat.surge.sh

fix(): changed skill feedback check

---

src/components/cms/Dashboard/MyAnalytics.js
src/components/cms/Dashboard/MyRatings.js
src/components/cms/Dashboard/MySkills.js

Fixes #3229  
Changes: 
- Set proper conditions in `Analytics`, `Skills` and `Ratings` section to display `Material Table` only when some content is available to show.
Demo Link: https://pr-3230-fossasia-susi-web-chat.surge.sh
**Before Changes**
**After Changes**

Show table in Analytics only when content is available

---

src/components/cms/SkillCreator/SkillWizard.js

Fixes #3233 
Changes: 
- Trimmed `skill_name` after fetching from props in `saveClick()`.
Demo Link: https://pr-3234-fossasia-susi-web-chat.surge.sh
**Screenshots**

Trim skill_name before submitting the skill

---

src/redux/reducers/skills.js

Fixes #3087 
Changes: Fixed not landing into 1st page of search results
Demo Link: https://pr-3247-fossasia-susi-web-chat.surge.sh
Screenshots of the change: [
Incorrect landing
Correct landing

Fixed not landing into 1st page of search results

---

src/components/NavigationBar/index.js
src/components/shared/Dialog/dialogTypes/ConfirmDialog.js

Fixes #3261 
Changes: 
- Added `ConfirmLogOut` dialog for the modal which opens when the **Logout** link is clicked.
Demo Link: https://pr-3262-fossasia-susi-web-chat.surge.sh

Added logout confirm check

---

src/components/cms/SkillCreator/SkillWizard.js

Fixes #3296
Changes:
- Used image crop modal to crop the bot image before upload.
Demo Link: https://pr-3297-fossasia-susi-web-chat.surge.sh

Added image crop to crop bot image

---

src/components/cms/BrowseSkill/skillLoader.js

Fixes #3168 
Changes: 
- Set limits to display loaders according to `window.innerWidth()`.
Demo Link: https://pr-3302-fossasia-susi-web-chat.surge.sh
**After Changes**

Set content-loaders limit with respect to the window-width

---

src/components/About/Overview/index.js

Fixes #3088 
Changes: Changed CSS made the button grid more uniform across all devices.
Demo Link: https://pr-3344-fossasia-susi-web-chat.surge.sh

fix(): made buttons symmetric/uniform

---

src/components/Settings/ShareOnSocialMedia.js
src/utils/CopyWithButton.js

Fixes #3328 and Fixes #3326
Changes: [Fixed uniformity in Susi share menu and others
Fixed Social icons in Susi share menu
Fixed hovering action of these in chrome
Fixed overlapping of on hover and click actions]
Link : http://pr3342foss.surge.sh/settings
Susi Share menu and On Click :
On hover:

Fixed Social media buttons on share susi menu

---

public/css/material_icons.css
public/index.html

Fixes #3459 
Changes: 
The font now displayed immediately is a system font. Once the custom font is ready, it replaces the system font.
Demo Link: https://pr-3460-fossasia-susi-web-chat.surge.sh

The text remains visible now during webfont load

---

src/components/NavigationBar/index.js

Fixes #3449 
Fixes #3450
Changes: 
1. Fixed about menu overflowing outside
2. Fixed drop down alignments.
3. Fixed navigation bar for mobiles. Now navigation bar on mobiles is less congested.
Demo Link: http://abcdabcd.surge.sh/

Fixed navigation bar for mobiles

---

src/components/cms/BrowseSkill/SideDrawer.js

Fixes #3096 
Changes: The sidebar toggler on smaller screens should remain fixed for smaller screens. The CSS in JS was changed to allow this to happen.
__Before__ :
__After__
Demo Link: https://pr-3474-fossasia-susi-web-chat.surge.sh

Fixed sidebar toggler position (#3096)

---

src/components/cms/BrowseSkill/BrowseSkill.js

Fixes #3456 
Fixes #3469 
Changes: The sidebar link was styled as button before. However it should be link. This was causing links not to work.

Fixes category reset link

---

src/components/About/Blog/BlogItem.js

Fixes #3483 
Changes: 
Adding Space between icon and text in the footer of each blog i the Blog Section.
Demo Link: https://pr-[3484]-fossasia-susi-web-chat.surge.sh
**Before**
**After**

Adding Space between icon and text in the footer of each blog

---

src/components/NavigationBar/index.js

Fixes #3487
Changes: 
Removed unnecessary navigation on clicking "?".

Fixed unnecessary link in navbar to about menu

---

src/components/cms/SkillSlideshow/index.css

Fixes #3371
Changes: Previously, the button when clicked on extremes (top/bottom) navigated user to other pages which is not desirable from users perspective. When not visible, any image on slide show should not navigate the user to that link and rather show that image first.
Demo Link: 
Now : - 
Before : -

Fixed slide show button

---

src/components/Settings/Settings.react.js
src/components/cms/SkillCardScrollList/SkillCard.js

Fixes #3506 
Changes:
The current codebase only hid the horizontal scrollbars on the Browse Skills container in Chrome only. This PR enables that feature across Edge and Firefox as well. 
Demo Link: https://pr-3509-fossasia-susi-web-chat.surge.sh
__Mozilla Firefox__
__Microsoft Edge__

Removed horizontal scrollbars on Edge and Firefox

---

src/components/ChatApp/MessageSection/MessageSection.react.js

Fixes #3510 
Changes: markId variable in MessageSection.react.js is not an array typed. Removed Array.isArray() and markId.length from the if condition. If it's not null,relevant text will be highlighted in searching.
Demo Link: https://pr-3513-fossasia-susi-web-chat.surge.sh

Resolved highlighting error in chat

---

src/components/cms/SkillCardList/SkillCardList.js

Fixes #3541 
Changes: 
- Removed the react-tooltip ```delay``` property to immediately hide the rating tooltip instead of being dragged around with the cursor 
Demo Link: https://pr-3543-fossasia-susi-web-chat.surge.sh
Changes made:

fix: tooltip delay to avoid moving with cursor - I3541

---

src/components/cms/SkillCardList/SkillCardList.js

Fixes #3539 
Demo Link: https://pr-3539-fossasia-susi-web-chat.surge.sh
Changes:
Grouping Rating.widget at one place and then added the ReactTooltip after that.

Fixed: Rating star doesn't matches with original one on applying rating filters

---

src/components/cms/BrowseSkill/BrowseSkill.js

Fixes #3594 
Changes: Passed parameter as 768 to isMobileView function for getting burger menu icon to be displayed for screen width less than 768px.
Demo Link: https://pr-3600-fossasia-susi-web-chat.surge.sh
**Before**
Here, No icon is present for screen width less than 768px.
**After**
Here, menu icon is visible for screen width less than 768px.

fix: burger menu icon shows up between 768px and  520 px 

---

package.json
yarn.lock

Fixes #3584 
Changes: "*material-ui-password-field": "2.1.1"* has been changed to *"material-ui-password-field": "2.1.2"* which fixes toggle password in newer react versions. [Material-ui-password-field](https://github.com/TeamWertarbyte/material-ui-password-field)
Demo Link: http://pr-3608-fossasia-susi-web-chat.surge.sh/
> Before
> After

Toggle fix

---

src/components/Admin/ListBots/index.js
src/components/Admin/ListSkills/SkillTable.js
src/components/Admin/ListUser/index.js

Changes:
- Admin shows now upto 500 entries, available options 25, 50, 100, 200, 500
- I modified Material Table props to add 25, 50, 100 , 200, 500 entries option
- I imported Material Icons to fix icons not showing issue in the table's pagination
Demo Link: https://pr-3624-fossasia-susi-web-chat.surge.sh
I have used dummy data for the screenshots.
* Users Page
* Skills Page
* Bots Page

Admin shows upto 500 entries fixes (#3518)

---

src/components/NavigationBar/index.js

Fixes #3619
SUSI.AI logo reloads the entire web app which leads to slower user experience, unneccessary network usage and performance issues
Changes: 
* SUSI.AI logo doesnot reloads the entire web app
Demo Link: https://pr-3620-fossasia-susi-web-chat.surge.sh
Before:
Now:

SUSI.AI logo doesnot reloads entire page now fixes (#3619)

---

src/components/cms/BrowseSkill/BrowseSkill.js
src/components/cms/SkillCardScrollList/SkillCard.js

Content disappering on resolution > 2400px is fixed with this PR.
- Content at home page which used to disappear at width > 2400px doesn't disappear now.
- Width of right container on home page was only defined upto 2400px.
- Due to lack of specified width for screens > 2400px, the right container div gets automatically enlarged.
width="400px" />
- Which results in disappearing of content for the user.
- I removed the media queries specifying different widths for different screen sizes.
- Instead I used relative width for sidebar(15%) and right container(85%) with flexbox .
- Now the width changes properly with different screen sizes.
Before:
At 2401px:
At 4000px:
Now:
At 2401px:
At 4000px:
Demo Link: https://pr-3621-fossasia-susi-web-chat.surge.sh

High resolution content disappearing bug fix (fossasia#3519)

---

deploy.sh
surge_deploy.sh

Fixes #3625 
Changes: 
- travis.ci updates recaptcha.js during deployment.
What I did:
- I scripted Travis CI to download recaptch library using wget, rename and move it into public/js/ folder.
Demo Link: https://pr-3626-fossasia-susi-web-chat.surge.sh
I have used `cat public/js/recaptcha.js` in .travis.yml during screenshot to test whether the file is at required location.
This command is removed now and is not part of the pr.
Line 488 will not appear after merge.

Automated updation of recaptcha.js during deployment. fixes (#3625)

---

src/components/Admin/ListSkills/SkillTable.js

**Fixes #3517**
- Deleting skills is not working for Admins issue fixed  
-   Wrong data was sent to handleDelete action.
-   Data coming from props of Action Component has to be sent to onDelete() but instead data from props of SkillTable component was sent.
-  I corrected the data source.
Demo Link: https://pr-3628-fossasia-susi-web-chat.surge.sh
**Screenshots of the change:**
I have used dummy data for screenshots.

Deleting skills not working issue fixed. Fixes(#3517)
